import type { TablePlayerSpec } from "../../../_viz/player/StepPlayer";

/**
 * `deep.walk`(수행으로 알아보는 알고리즘) 절과 **같은 입력**을 쓴다 — `N = 194` · `K = 10`.
 * `free` 는 DP 테이블을 까는 T1 부터 풀린 상태가 자리 2 · 자리 1 의 칸을 채우는 T7 까지이고,
 * `tight` 는 첫 호출이 `x = digits[0]` 을 놓아 붙은 채 자리 1 로 들어가는 T8 부터 답을 내는 T12 까지다.
 * 한 벌에 모으면 정적 필름이 열두 장이라 둘로 가른다. `result` 는 앞 벌이 마지막에 적은 칸의 값,
 * 뒤 벌이 반환값이다.
 *
 * `player: "stage"` 가 걸음 재생 패널(`src/_viz/player/StepPlayer.tsx`)을 고르고, `stage: "table"` 이
 * 2 차원 표 무대(`tableStage.ts`)를 고른다. 열은 앞 숫자의 합 `sum = 0 … K` 이고, 줄은 자리마다 둘 —
 * 붙은 상태(`tight` 참)와 풀린 상태(`tight` 거짓)다. 풀린 줄이 DP 테이블 `memo[pos]` 이고 붙은 줄은
 * DP 테이블 밖이다. 이 입력에서 한 번도 들어가지 않는 상태는 `out`(이번 걸음 밖)이다. `write` 는 이번에
 * 값을 정한 칸, `read` 는 그 값을 만들려고 읽은 칸, `target` 은 이번에 들어갔지만 아직 값을 정하지 않은
 * 상태(열 머리만 반전)다. 표 아래 괄호(`pieces`)는 놓아 본 숫자 `x` 가 다음 자리의 합을 어디까지
 * 보냈는가다.
 *
 * `steps` 는 **인라인 배열 리터럴**이어야 한다(spread·변수 참조·함수 호출 금지).
 * 정적 계수가 실제보다 적게 세면 얇은 전개가 P3 을 그냥 지나간다. 리터럴은 그림 사이드카의
 * `simStepsFromRef()`(정본 실행에서 만든 걸음)를 글자 그대로 옮긴 것이고, 둘이 같은지는
 * `digitDp-guide.test.ts` 가 잰다.
 */

export const free = {
  player: "stage",
  stage: "table",
  rowHeads: [
    "자리 0 붙음",
    "자리 0 풀림",
    "자리 1 붙음",
    "자리 1 풀림",
    "자리 2 붙음",
    "자리 2 풀림",
  ],
  colHeads: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  colLabel: "합 sum",
  title: "digitDp(194, 10) — 풀린 상태가 DP 테이블을 채운다",
  result: "9",
  steps: [
    {
      title: "T1 DP 테이블 3 × 11 을 깐다",
      text: "N = 194 를 자리로 가르면 digits = [1, 9, 4] 이고 L = 3 입니다. DP 테이블 memo 를 3 × 11 로 만들어 전부 -1(아직 안 정함)로 둡니다. 무대의 풀린 줄이 그 DP 테이블이고, 붙은 줄은 DP 테이블 밖입니다. 이 입력에서 한 번도 들어가지 않는 상태는 대시로 그렸습니다.",
      table: [
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
      ],
      out: [
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [0, 5],
        [0, 6],
        [0, 7],
        [0, 8],
        [0, 9],
        [0, 10],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [1, 6],
        [1, 7],
        [1, 8],
        [1, 9],
        [1, 10],
        [2, 0],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 5],
        [2, 6],
        [2, 7],
        [2, 8],
        [2, 9],
        [2, 10],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [3, 5],
        [3, 6],
        [3, 7],
        [3, 8],
        [3, 9],
        [3, 10],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4],
        [4, 5],
        [4, 6],
        [4, 7],
        [4, 8],
        [4, 9],
        [5, 10],
      ],
      rowSide: [
        "상한 1 · DP 테이블 밖",
        "상한 9 · 채움 0 / 0",
        "상한 9 · DP 테이블 밖",
        "상한 9 · 채움 0 / 1",
        "상한 4 · DP 테이블 밖",
        "상한 9 · 채움 0 / 10",
      ],
      calc: {
        expr: "DP 테이블 L × (K+1) =",
        result: "3 × 11",
      },
      vars: "digits = [1, 9, 4] · K = 10",
    },
    {
      title: "T2 자리 0 · 합 0 · 붙음 — 상한 1",
      text: "자리 0 · 합 0 · 붙은 상태로 들어왔습니다. 붙은 상태라 상한이 digits[0] = 1 입니다. x = 0 을 놓으면 1 보다 작아 다음 자리가 풀린 상태가 되고, x = 1 을 놓으면 digits[0] = 1 과 같아 붙은 채로 갑니다.",
      table: [
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
      ],
      target: [[0, 0]],
      out: [
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [0, 5],
        [0, 6],
        [0, 7],
        [0, 8],
        [0, 9],
        [0, 10],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [1, 6],
        [1, 7],
        [1, 8],
        [1, 9],
        [1, 10],
        [2, 0],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 5],
        [2, 6],
        [2, 7],
        [2, 8],
        [2, 9],
        [2, 10],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [3, 5],
        [3, 6],
        [3, 7],
        [3, 8],
        [3, 9],
        [3, 10],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4],
        [4, 5],
        [4, 6],
        [4, 7],
        [4, 8],
        [4, 9],
        [5, 10],
      ],
      pieces: [
        {
          label: "놓은 x",
          from: 0,
          to: 1,
          tone: "query",
          text: "x = 0 · 1",
          side: "상한 1",
        },
      ],
      rowSide: [
        "상한 1 · DP 테이블 밖",
        "상한 9 · 채움 0 / 0",
        "상한 9 · DP 테이블 밖",
        "상한 9 · 채움 0 / 1",
        "상한 4 · DP 테이블 밖",
        "상한 9 · 채움 0 / 10",
      ],
      calc: {
        expr: "상한 = digits[0] =",
        result: "1",
      },
      vars: "앞 숫자 없음 · N 의 숫자 1 9 4",
    },
    {
      title: "T3 자리 1 · 합 0 · 풀림 — 상한 9",
      text: "앞에 0 을 놓고 자리 1 · 합 0 · 풀린 상태로 들어왔습니다. 풀린 상태라 상한이 9 입니다. memo[1][0] 이 아직 -1 이라 ③ 이 읽을 값이 없습니다. x = 0 … 9 를 놓은 다음 자리도 모두 풀린 상태입니다.",
      table: [
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
      ],
      target: [[3, 0]],
      out: [
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [0, 5],
        [0, 6],
        [0, 7],
        [0, 8],
        [0, 9],
        [0, 10],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [1, 6],
        [1, 7],
        [1, 8],
        [1, 9],
        [1, 10],
        [2, 0],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 5],
        [2, 6],
        [2, 7],
        [2, 8],
        [2, 9],
        [2, 10],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [3, 5],
        [3, 6],
        [3, 7],
        [3, 8],
        [3, 9],
        [3, 10],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4],
        [4, 5],
        [4, 6],
        [4, 7],
        [4, 8],
        [4, 9],
        [5, 10],
      ],
      pieces: [
        {
          label: "놓은 x",
          from: 0,
          to: 9,
          tone: "query",
          text: "x = 0 … 9",
          side: "상한 9",
        },
      ],
      rowSide: [
        "상한 1 · DP 테이블 밖",
        "상한 9 · 채움 0 / 0",
        "상한 9 · DP 테이블 밖",
        "상한 9 · 채움 0 / 1",
        "상한 4 · DP 테이블 밖",
        "상한 9 · 채움 0 / 10",
      ],
      calc: {
        expr: "상한 =",
        result: "9",
      },
      vars: "앞 숫자 0 · N 의 숫자 1 9 4",
    },
    {
      title: "T4 자리 2 · 합 0 · 풀림 → 0 ①",
      text: "앞에 0 0 을 놓고 자리 2 · 합 0 · 풀린 상태로 왔습니다. 남은 1 자리를 전부 9 로 채워도 0 + 9 × 1 = 9 가 K = 10 보다 작아 ① 이 0 을 돌려줍니다. DP 테이블에는 적지 않습니다.",
      table: [
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
      ],
      target: [[5, 0]],
      out: [
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [0, 5],
        [0, 6],
        [0, 7],
        [0, 8],
        [0, 9],
        [0, 10],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [1, 6],
        [1, 7],
        [1, 8],
        [1, 9],
        [1, 10],
        [2, 0],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 5],
        [2, 6],
        [2, 7],
        [2, 8],
        [2, 9],
        [2, 10],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [3, 5],
        [3, 6],
        [3, 7],
        [3, 8],
        [3, 9],
        [3, 10],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4],
        [4, 5],
        [4, 6],
        [4, 7],
        [4, 8],
        [4, 9],
        [5, 10],
      ],
      rowSide: [
        "상한 1 · DP 테이블 밖",
        "상한 9 · 채움 0 / 0",
        "상한 9 · DP 테이블 밖",
        "상한 9 · 채움 0 / 1",
        "상한 4 · DP 테이블 밖",
        "상한 9 · 채움 0 / 10",
      ],
      calc: {
        expr: "0 + 9 × 1 < 10 →",
        result: "0",
      },
      vars: "앞 숫자 0 0 · N 의 숫자 1 9 4",
    },
    {
      title: "T5 memo[2][1] = 1 ⑤",
      text: "앞에 0 1 을 놓고 자리 2 · 합 1 · 풀린 상태의 반복을 끝냅니다. x = 0 … 8 은 합이 10 에 못 미쳐 ① 이 0 을, x = 9 는 합이 10 이라 ② 가 1 을 돌려줍니다. 풀린 상태라 memo[2][1] 에 1 을 적습니다 ⑤.",
      table: [
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, "1", null, null, null, null, null, null, null, null, null],
      ],
      write: [[5, 1]],
      out: [
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [0, 5],
        [0, 6],
        [0, 7],
        [0, 8],
        [0, 9],
        [0, 10],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [1, 6],
        [1, 7],
        [1, 8],
        [1, 9],
        [1, 10],
        [2, 0],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 5],
        [2, 6],
        [2, 7],
        [2, 8],
        [2, 9],
        [2, 10],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [3, 5],
        [3, 6],
        [3, 7],
        [3, 8],
        [3, 9],
        [3, 10],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4],
        [4, 5],
        [4, 6],
        [4, 7],
        [4, 8],
        [4, 9],
        [5, 10],
      ],
      pieces: [
        {
          label: "놓은 x",
          from: 1,
          to: 10,
          tone: "query",
          text: "x = 0 … 9",
          side: "상한 9",
        },
      ],
      rowSide: [
        "상한 1 · DP 테이블 밖",
        "상한 9 · 채움 0 / 0",
        "상한 9 · DP 테이블 밖",
        "상한 9 · 채움 0 / 1",
        "상한 4 · DP 테이블 밖",
        "상한 9 · 채움 1 / 10",
      ],
      calc: {
        expr: "0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 0 + 1 =",
        result: "1",
      },
      vars: "앞 숫자 0 1 · N 의 숫자 1 9 4",
    },
    {
      title: "T6 memo[2][2] … memo[2][9] = 1 ⑤",
      text: "memo[2][2] … memo[2][9] 8 칸이 같은 모양입니다. 칸마다 합을 10 으로 만드는 숫자 하나에서 ② 가 1 을, 그보다 작은 숫자에서 ① 이 0 을 돌려주고, 그보다 큰 숫자는 ④ 로 끊습니다. 8 칸 모두 1 을 적습니다 ⑤.",
      table: [
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, "1", "1", "1", "1", "1", "1", "1", "1", "1", null],
      ],
      write: [
        [5, 2],
        [5, 3],
        [5, 4],
        [5, 5],
        [5, 6],
        [5, 7],
        [5, 8],
        [5, 9],
      ],
      out: [
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [0, 5],
        [0, 6],
        [0, 7],
        [0, 8],
        [0, 9],
        [0, 10],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [1, 6],
        [1, 7],
        [1, 8],
        [1, 9],
        [1, 10],
        [2, 0],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 5],
        [2, 6],
        [2, 7],
        [2, 8],
        [2, 9],
        [2, 10],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [3, 5],
        [3, 6],
        [3, 7],
        [3, 8],
        [3, 9],
        [3, 10],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4],
        [4, 5],
        [4, 6],
        [4, 7],
        [4, 8],
        [4, 9],
        [5, 10],
      ],
      rowSide: [
        "상한 1 · DP 테이블 밖",
        "상한 9 · 채움 0 / 0",
        "상한 9 · DP 테이블 밖",
        "상한 9 · 채움 0 / 1",
        "상한 4 · DP 테이블 밖",
        "상한 9 · 채움 9 / 10",
      ],
      calc: {
        expr: "memo[2][2] … memo[2][9] =",
        result: "1",
      },
      vars: "앞 숫자 0 2 · N 의 숫자 1 9 4",
    },
    {
      title: "T7 memo[1][0] = 9 ⑤",
      text: "앞에 0 을 놓고 자리 1 · 합 0 · 풀린 상태의 반복을 끝냅니다. x = 0 … 9 를 놓아 얻은 값 0 · 1 · 1 · 1 · 1 · 1 · 1 · 1 · 1 · 1 을 더하면 9 입니다. 풀린 상태라 memo[1][0] 에 9 를 적습니다 ⑤.",
      table: [
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        ["9", null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, "1", "1", "1", "1", "1", "1", "1", "1", "1", null],
      ],
      read: [
        [5, 1],
        [5, 2],
        [5, 3],
        [5, 4],
        [5, 5],
        [5, 6],
        [5, 7],
        [5, 8],
        [5, 9],
      ],
      write: [[3, 0]],
      out: [
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [0, 5],
        [0, 6],
        [0, 7],
        [0, 8],
        [0, 9],
        [0, 10],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [1, 6],
        [1, 7],
        [1, 8],
        [1, 9],
        [1, 10],
        [2, 0],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 5],
        [2, 6],
        [2, 7],
        [2, 8],
        [2, 9],
        [2, 10],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [3, 5],
        [3, 6],
        [3, 7],
        [3, 8],
        [3, 9],
        [3, 10],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4],
        [4, 5],
        [4, 6],
        [4, 7],
        [4, 8],
        [4, 9],
        [5, 10],
      ],
      pieces: [
        {
          label: "놓은 x",
          from: 0,
          to: 9,
          tone: "query",
          text: "x = 0 … 9",
          side: "상한 9",
        },
      ],
      rowSide: [
        "상한 1 · DP 테이블 밖",
        "상한 9 · 채움 0 / 0",
        "상한 9 · DP 테이블 밖",
        "상한 9 · 채움 1 / 1",
        "상한 4 · DP 테이블 밖",
        "상한 9 · 채움 9 / 10",
      ],
      calc: {
        expr: "0 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 =",
        result: "9",
      },
      vars: "앞 숫자 0 · N 의 숫자 1 9 4",
    },
  ],
} satisfies TablePlayerSpec;

export const tight = {
  player: "stage",
  stage: "table",
  rowHeads: [
    "자리 0 붙음",
    "자리 0 풀림",
    "자리 1 붙음",
    "자리 1 풀림",
    "자리 2 붙음",
    "자리 2 풀림",
  ],
  colHeads: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  colLabel: "합 sum",
  title: "digitDp(194, 10) — 붙은 상태가 N 을 따라가며 DP 테이블을 읽는다",
  result: "19",
  steps: [
    {
      title: "T8 자리 1 · 합 1 · 붙음 — 상한 9",
      text: "앞에 1 을 놓고 자리 1 · 합 1 · 붙은 상태로 들어왔습니다. 붙은 상태라 상한이 digits[1] = 9 입니다. x = 0 … 8 을 놓으면 9 보다 작아 다음 자리가 풀린 상태가 되고, x = 9 를 놓으면 digits[1] = 9 와 같아 붙은 채로 갑니다.",
      table: [
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        ["9", null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, "1", "1", "1", "1", "1", "1", "1", "1", "1", null],
      ],
      target: [[2, 1]],
      out: [
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [0, 5],
        [0, 6],
        [0, 7],
        [0, 8],
        [0, 9],
        [0, 10],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [1, 6],
        [1, 7],
        [1, 8],
        [1, 9],
        [1, 10],
        [2, 0],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 5],
        [2, 6],
        [2, 7],
        [2, 8],
        [2, 9],
        [2, 10],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [3, 5],
        [3, 6],
        [3, 7],
        [3, 8],
        [3, 9],
        [3, 10],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4],
        [4, 5],
        [4, 6],
        [4, 7],
        [4, 8],
        [4, 9],
        [5, 10],
      ],
      pieces: [
        {
          label: "놓은 x",
          from: 1,
          to: 10,
          tone: "query",
          text: "x = 0 … 9",
          side: "상한 9",
        },
      ],
      rowSide: [
        "상한 1 · DP 테이블 밖",
        "상한 9 · 채움 0 / 0",
        "상한 9 · DP 테이블 밖",
        "상한 9 · 채움 1 / 1",
        "상한 4 · DP 테이블 밖",
        "상한 9 · 채움 9 / 10",
      ],
      calc: {
        expr: "상한 = digits[1] =",
        result: "9",
      },
      vars: "앞 숫자 1 · N 의 숫자 1 9 4",
    },
    {
      title: "T9 memo[2][1] … memo[2][9] 읽기 ③ × 9",
      text: "x = 0 … 8 을 놓은 다음 상태는 자리 2 · 합 1 … 9 · 풀린 상태이고, T5 · T6 이 이미 정한 칸입니다. ③ 이 memo[2][1] … memo[2][9] 를 9 번 읽어 합 9 를 받습니다.",
      table: [
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        ["9", null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, "1", "1", "1", "1", "1", "1", "1", "1", "1", null],
      ],
      read: [
        [5, 1],
        [5, 2],
        [5, 3],
        [5, 4],
        [5, 5],
        [5, 6],
        [5, 7],
        [5, 8],
        [5, 9],
      ],
      out: [
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [0, 5],
        [0, 6],
        [0, 7],
        [0, 8],
        [0, 9],
        [0, 10],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [1, 6],
        [1, 7],
        [1, 8],
        [1, 9],
        [1, 10],
        [2, 0],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 5],
        [2, 6],
        [2, 7],
        [2, 8],
        [2, 9],
        [2, 10],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [3, 5],
        [3, 6],
        [3, 7],
        [3, 8],
        [3, 9],
        [3, 10],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4],
        [4, 5],
        [4, 6],
        [4, 7],
        [4, 8],
        [4, 9],
        [5, 10],
      ],
      rowSide: [
        "상한 1 · DP 테이블 밖",
        "상한 9 · 채움 0 / 0",
        "상한 9 · DP 테이블 밖",
        "상한 9 · 채움 1 / 1",
        "상한 4 · DP 테이블 밖",
        "상한 9 · 채움 9 / 10",
      ],
      calc: {
        expr: "1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 =",
        result: "9",
      },
      vars: "앞 숫자 1 0 · N 의 숫자 1 9 4",
    },
    {
      title: "T10 자리 2 · 합 10 · 붙음 = 1",
      text: "앞에 1 9 를 놓고 자리 2 · 합 10 · 붙은 상태의 반복을 끝냅니다. x = 0 은 합이 10 이라 ② 가 1 을 돌려줍니다. x = 1 은 합이 11 이라 ④ 로 끊습니다. 수 190 하나입니다. 붙은 상태라 DP 테이블에 적지 않고 1 을 돌려주기만 합니다.",
      table: [
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        ["9", null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, "1"],
        [null, "1", "1", "1", "1", "1", "1", "1", "1", "1", null],
      ],
      write: [[4, 10]],
      out: [
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [0, 5],
        [0, 6],
        [0, 7],
        [0, 8],
        [0, 9],
        [0, 10],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [1, 6],
        [1, 7],
        [1, 8],
        [1, 9],
        [1, 10],
        [2, 0],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 5],
        [2, 6],
        [2, 7],
        [2, 8],
        [2, 9],
        [2, 10],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [3, 5],
        [3, 6],
        [3, 7],
        [3, 8],
        [3, 9],
        [3, 10],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4],
        [4, 5],
        [4, 6],
        [4, 7],
        [4, 8],
        [4, 9],
        [5, 10],
      ],
      pieces: [
        {
          label: "놓은 x",
          from: 10,
          to: 10,
          tone: "query",
          text: "x = 0",
          side: "상한 4 · x=1 에서 ④",
        },
      ],
      rowSide: [
        "상한 1 · DP 테이블 밖",
        "상한 9 · 채움 0 / 0",
        "상한 9 · DP 테이블 밖",
        "상한 9 · 채움 1 / 1",
        "상한 4 · DP 테이블 밖",
        "상한 9 · 채움 9 / 10",
      ],
      calc: {
        expr: "1 =",
        result: "1",
      },
      vars: "앞 숫자 1 9 · N 의 숫자 1 9 4",
    },
    {
      title: "T11 자리 1 · 합 1 · 붙음 = 10",
      text: "앞에 1 을 놓고 자리 1 · 합 1 · 붙은 상태의 반복을 끝냅니다. x = 0 … 9 를 놓아 얻은 값 1 · 1 · 1 · 1 · 1 · 1 · 1 · 1 · 1 · 1 을 더하면 10 입니다. 붙은 상태라 DP 테이블에 적지 않고 10 을 돌려주기만 합니다.",
      table: [
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, "10", null, null, null, null, null, null, null, null, null],
        ["9", null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, "1"],
        [null, "1", "1", "1", "1", "1", "1", "1", "1", "1", null],
      ],
      read: [
        [5, 1],
        [5, 2],
        [5, 3],
        [5, 4],
        [5, 5],
        [5, 6],
        [5, 7],
        [5, 8],
        [5, 9],
        [4, 10],
      ],
      write: [[2, 1]],
      out: [
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [0, 5],
        [0, 6],
        [0, 7],
        [0, 8],
        [0, 9],
        [0, 10],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [1, 6],
        [1, 7],
        [1, 8],
        [1, 9],
        [1, 10],
        [2, 0],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 5],
        [2, 6],
        [2, 7],
        [2, 8],
        [2, 9],
        [2, 10],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [3, 5],
        [3, 6],
        [3, 7],
        [3, 8],
        [3, 9],
        [3, 10],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4],
        [4, 5],
        [4, 6],
        [4, 7],
        [4, 8],
        [4, 9],
        [5, 10],
      ],
      pieces: [
        {
          label: "놓은 x",
          from: 1,
          to: 10,
          tone: "query",
          text: "x = 0 … 9",
          side: "상한 9",
        },
      ],
      rowSide: [
        "상한 1 · DP 테이블 밖",
        "상한 9 · 채움 0 / 0",
        "상한 9 · DP 테이블 밖",
        "상한 9 · 채움 1 / 1",
        "상한 4 · DP 테이블 밖",
        "상한 9 · 채움 9 / 10",
      ],
      calc: {
        expr: "1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 =",
        result: "10",
      },
      vars: "앞 숫자 1 · N 의 숫자 1 9 4",
    },
    {
      title: "T12 자리 0 · 합 0 · 붙음 = 19",
      text: "자리 0 · 합 0 · 붙은 상태의 반복을 끝냅니다. x = 0 · 1 을 놓아 얻은 값 9 · 10 을 더하면 19 입니다. 붙은 상태라 DP 테이블에 적지 않고 19 를 돌려주기만 합니다. K = 10 이 0 이 아니라 ⑥ 은 빼지 않고, 답은 19 입니다.",
      table: [
        ["19", null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, null],
        [null, "10", null, null, null, null, null, null, null, null, null],
        ["9", null, null, null, null, null, null, null, null, null, null],
        [null, null, null, null, null, null, null, null, null, null, "1"],
        [null, "1", "1", "1", "1", "1", "1", "1", "1", "1", null],
      ],
      read: [
        [3, 0],
        [2, 1],
      ],
      write: [[0, 0]],
      out: [
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [0, 5],
        [0, 6],
        [0, 7],
        [0, 8],
        [0, 9],
        [0, 10],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5],
        [1, 6],
        [1, 7],
        [1, 8],
        [1, 9],
        [1, 10],
        [2, 0],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 5],
        [2, 6],
        [2, 7],
        [2, 8],
        [2, 9],
        [2, 10],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [3, 5],
        [3, 6],
        [3, 7],
        [3, 8],
        [3, 9],
        [3, 10],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4],
        [4, 5],
        [4, 6],
        [4, 7],
        [4, 8],
        [4, 9],
        [5, 10],
      ],
      pieces: [
        {
          label: "놓은 x",
          from: 0,
          to: 1,
          tone: "query",
          text: "x = 0 · 1",
          side: "상한 1",
        },
      ],
      rowSide: [
        "상한 1 · DP 테이블 밖",
        "상한 9 · 채움 0 / 0",
        "상한 9 · DP 테이블 밖",
        "상한 9 · 채움 1 / 1",
        "상한 4 · DP 테이블 밖",
        "상한 9 · 채움 9 / 10",
      ],
      calc: {
        expr: "9 + 10 =",
        result: "19",
      },
      vars: "앞 숫자 없음 · N 의 숫자 1 9 4",
    },
  ],
} satisfies TablePlayerSpec;
