import type { ArrayPlayerSpec } from "../../../_viz/player/StepPlayer";

/**
 * `deep.walk`(수행으로 알아보는 알고리즘) 절과 **같은 입력**(`millerRabin(49141n)`)을 쓴다. 걸음은 `n < 2`
 * 검사(T1) · 밑 목록으로 나눠 보기(T2) · `n − 1` 가르기(T3) · 밑마다 첫 값과 제곱(T4~T7) · 증인(T8)이다.
 *
 * `player: "stage"` 가 걸음 재생 패널(`src/_viz/player/StepPlayer.tsx`)을 고르고, `stage: "array"` 가 배열
 * 무대(`arrayStage.ts`)를 고른다. 칸 `i` 가 밑 목록의 `i` 번째 밑이다. 괄호 「남은 밑」은 아직 판정을 내지 않은
 * 밑이고 ▲ 는 이번에 보는 밑이다. 그 아래 줄들이 알고리즘이 쌓는 값이다 — `n mod a` 줄은 사전 나눗셈의 나머지,
 * `x₀` · `x₁` 줄은 밑마다의 제곱 수열이다. `d` · `s` · 나머지 연산 수는 무대에 자리가 없어 남는 변수다.
 *
 * 옛 패널(`view: ["keyValue"]`)은 변수 여덟을 나열했다. 밑 목록이 무대에 없어서 「밑 2 (12 개 중 1 번째)」처럼
 * 자리를 글로 적어야 했고, 끝까지 안 본 밑 열이 보이지 않았다(SPEC `L48`).
 *
 * `steps` 는 **인라인 배열 리터럴**이어야 한다(spread·변수 참조·함수 호출 금지). 리터럴은 그림 사이드카의
 * `simStepsFromRef()`(정본과 같은 절차를 따라가며 만든 걸음)를 글자 그대로 옮긴 것이고, 둘이 같은지는
 * `millerRabin-guide.test.ts` 가 잰다.
 */

export const mrWalk = {
  player: "stage",
  stage: "array",
  arrayName: "밑 a",
  rangeLabel: "남은 밑",
  title: "millerRabin(49141n)",
  result: "false",
  steps: [
    {
      title: "T1 n < 2 검사",
      text: "49,141 은 2 이상이라 n < 2 가 거짓입니다. 나머지 연산은 아직 한 번도 하지 않았습니다.",
      array: [
        "2",
        "3",
        "5",
        "7",
        "11",
        "13",
        "17",
        "19",
        "23",
        "29",
        "31",
        "37",
      ],
      range: [0, 11],
      read: [],
      write: [],
      calc: {
        expr: "49,141 < 2",
        result: "거짓",
      },
      vars: "나머지 연산 0",
      layers: [
        {
          name: "n mod a",
          values: [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [],
        },
        {
          name: "x₀ = a^d",
          values: [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [],
        },
        {
          name: "x₁ = x₀²",
          values: [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [],
        },
      ],
    },
    {
      title: "T2 밑 목록으로 나눠 보기",
      text: "49,141 을 밑 열둘로 한 번씩 나눕니다. 나머지가 0 인 밑이 0 개라 여기서 답하지 않고, 49,141 의 소인수는 전부 37 보다 큽니다.",
      array: [
        "2",
        "3",
        "5",
        "7",
        "11",
        "13",
        "17",
        "19",
        "23",
        "29",
        "31",
        "37",
      ],
      range: [0, 11],
      read: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
      write: [],
      calc: {
        expr: "49,141 mod 2 … 37",
        result: "0 인 칸 0 개",
      },
      vars: "나머지 연산 12",
      layers: [
        {
          name: "n mod a",
          values: [
            "1",
            "1",
            "1",
            "1",
            "4",
            "1",
            "11",
            "7",
            "13",
            "15",
            "6",
            "5",
          ],
          read: [],
          write: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        },
        {
          name: "x₀ = a^d",
          values: [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [],
        },
        {
          name: "x₁ = x₀²",
          values: [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [],
        },
      ],
    },
    {
      title: "T3 n − 1 가르기",
      text: "n − 1 = 49,140 을 2 로 2 번 나누면 홀수 12,285 가 됩니다. d = 12,285, s = 2 입니다.",
      array: [
        "2",
        "3",
        "5",
        "7",
        "11",
        "13",
        "17",
        "19",
        "23",
        "29",
        "31",
        "37",
      ],
      range: [0, 11],
      read: [],
      write: [],
      calc: {
        expr: "49,140 = 12,285 × 2^2",
        result: "d = 12,285 · s = 2",
      },
      vars: "d = 12,285 · s = 2 · 나머지 연산 12",
      layers: [
        {
          name: "n mod a",
          values: [
            "1",
            "1",
            "1",
            "1",
            "4",
            "1",
            "11",
            "7",
            "13",
            "15",
            "6",
            "5",
          ],
          read: [],
          write: [],
        },
        {
          name: "x₀ = a^d",
          values: [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [],
        },
        {
          name: "x₁ = x₀²",
          values: [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [],
        },
      ],
    },
    {
      title: "T4 밑 2 의 첫 값",
      text: "x₀ = 2^12,285 mod 49,141 = 32,527 입니다. 1 도 n − 1 도 아니라 제곱 루프로 내려갑니다. 이 거듭제곱 하나가 나머지 연산 28 번입니다.",
      array: [
        "2",
        "3",
        "5",
        "7",
        "11",
        "13",
        "17",
        "19",
        "23",
        "29",
        "31",
        "37",
      ],
      range: [0, 11],
      read: [0],
      write: [],
      calc: {
        expr: "2^12,285 mod 49,141",
        result: "32,527",
      },
      vars: "d = 12,285 · s = 2 · 나머지 연산 40",
      layers: [
        {
          name: "n mod a",
          values: [
            "1",
            "1",
            "1",
            "1",
            "4",
            "1",
            "11",
            "7",
            "13",
            "15",
            "6",
            "5",
          ],
          read: [],
          write: [],
        },
        {
          name: "x₀ = a^d",
          values: [
            "32,527",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [0],
        },
        {
          name: "x₁ = x₀²",
          values: [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [],
        },
      ],
    },
    {
      title: "T5 밑 2 를 제곱",
      text: "32,527² mod 49,141 = 49,140 입니다. n − 1 이라 이 밑은 통과하고 다음 밑으로 갑니다.",
      array: [
        "2",
        "3",
        "5",
        "7",
        "11",
        "13",
        "17",
        "19",
        "23",
        "29",
        "31",
        "37",
      ],
      range: [0, 11],
      read: [0],
      write: [],
      calc: {
        expr: "32,527² mod 49,141",
        result: "49,140 = n − 1",
      },
      vars: "d = 12,285 · s = 2 · 나머지 연산 41",
      layers: [
        {
          name: "n mod a",
          values: [
            "1",
            "1",
            "1",
            "1",
            "4",
            "1",
            "11",
            "7",
            "13",
            "15",
            "6",
            "5",
          ],
          read: [],
          write: [],
        },
        {
          name: "x₀ = a^d",
          values: [
            "32,527",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [0],
          write: [],
        },
        {
          name: "x₁ = x₀²",
          values: [
            "49,140",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [0],
        },
      ],
    },
    {
      title: "T6 밑 3 의 첫 값",
      text: "x₀ = 3^12,285 mod 49,141 = 627 입니다. 1 도 n − 1 도 아니라 제곱 루프로 내려갑니다. 이 거듭제곱 하나가 나머지 연산 28 번입니다.",
      array: [
        "2",
        "3",
        "5",
        "7",
        "11",
        "13",
        "17",
        "19",
        "23",
        "29",
        "31",
        "37",
      ],
      range: [1, 11],
      read: [1],
      write: [],
      calc: {
        expr: "3^12,285 mod 49,141",
        result: "627",
      },
      vars: "d = 12,285 · s = 2 · 나머지 연산 69",
      layers: [
        {
          name: "n mod a",
          values: [
            "1",
            "1",
            "1",
            "1",
            "4",
            "1",
            "11",
            "7",
            "13",
            "15",
            "6",
            "5",
          ],
          read: [],
          write: [],
        },
        {
          name: "x₀ = a^d",
          values: [
            "32,527",
            "627",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [1],
        },
        {
          name: "x₁ = x₀²",
          values: [
            "49,140",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [],
        },
      ],
    },
    {
      title: "T7 밑 3 을 제곱",
      text: "627² mod 49,141 = 1 입니다. n − 1 이 아닙니다.",
      array: [
        "2",
        "3",
        "5",
        "7",
        "11",
        "13",
        "17",
        "19",
        "23",
        "29",
        "31",
        "37",
      ],
      range: [1, 11],
      read: [1],
      write: [],
      calc: {
        expr: "627² mod 49,141",
        result: "1",
      },
      vars: "d = 12,285 · s = 2 · 나머지 연산 70",
      layers: [
        {
          name: "n mod a",
          values: [
            "1",
            "1",
            "1",
            "1",
            "4",
            "1",
            "11",
            "7",
            "13",
            "15",
            "6",
            "5",
          ],
          read: [],
          write: [],
        },
        {
          name: "x₀ = a^d",
          values: [
            "32,527",
            "627",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [1],
          write: [],
        },
        {
          name: "x₁ = x₀²",
          values: [
            "49,140",
            "1",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [1],
        },
      ],
    },
    {
      title: "T8 밑 3 이 증인",
      text: "제곱 수열 627 → 1 이 n − 1 을 한 번도 거치지 않고 끝났습니다. 밑 3 이 증인이라 남은 밑 10 개는 보지 않고 false 를 돌려줍니다.",
      array: [
        "2",
        "3",
        "5",
        "7",
        "11",
        "13",
        "17",
        "19",
        "23",
        "29",
        "31",
        "37",
      ],
      range: [1, 11],
      read: [],
      write: [1],
      calc: {
        expr: "627 → 1 · n − 1 없음",
        result: "증인 → false",
      },
      vars: "d = 12,285 · s = 2 · 나머지 연산 70",
      layers: [
        {
          name: "n mod a",
          values: [
            "1",
            "1",
            "1",
            "1",
            "4",
            "1",
            "11",
            "7",
            "13",
            "15",
            "6",
            "5",
          ],
          read: [],
          write: [],
        },
        {
          name: "x₀ = a^d",
          values: [
            "32,527",
            "627",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [],
        },
        {
          name: "x₁ = x₀²",
          values: [
            "49,140",
            "1",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [1],
          write: [],
        },
      ],
    },
  ],
} satisfies ArrayPlayerSpec;
