import type { Frame } from "#guide-sim";

/**
 * `deep.walk`(수행으로 알아보는 알고리즘) 절과 **같은 입력**을 쓴다 — 도시 넷짜리 거리 행렬
 * `[[0,10,15,20],[10,0,35,25],[15,35,0,30],[20,25,30,0]]` 이고 답이 80 이다. 프레임 수(17)가
 * 그 절의 T# 단계 수(17)와 같다 — P3 이 그 관계를 잰다. **T# 하나에 프레임 하나를 둔다.**
 * 본문이 특정 걸음을 이름으로 짚는 자리가 있어서(「T8 이 적은 75 를 T12 가 다시 쓰지 않는다」)
 * 프레임을 묶으면 그 걸음을 화면에서 찾을 수 없다.
 *
 * `keyValue` 와 `matrix` 조합을 고른 이유를 적어 둔다.
 *
 * 1. **`matrix` 가 상태 표를, `keyValue` 가 지금 하는 일을 진다.** 상태 표는 행이 방문 집합
 *    `mask`, 열이 현재 위치 `v` 라 그대로 격자다. 지금 어느 방문 집합을 처리하는지 · 값이
 *    든 위치가 어디인지 · 어떤 전이를 만들었는지는 격자의 칸이 아니라 그 옆의 상태라
 *    `entries` 한 줄씩으로 둔다.
 * 2. **행을 15 개 전부 싣는다.** 도시 0 을 담지 않은 방문 집합 일곱 줄이 끝까지 INF 로 남는
 *    것이 이 알고리즘의 비용 이야기 그 자체다 — 그 줄을 지우면 「잡은 칸의 23.8 % 만 쓴다」가
 *    화면에서 사라진다.
 * 3. **`INF` 를 빈 칸으로 적지 않는다.** 코드가 그 칸에 `Number.POSITIVE_INFINITY` 를 실제로
 *    적어 두므로 본문 증명 블록의 표기와 같은 글자로 보인다.
 * 4. **아무 일도 하지 않는 걸음도 프레임 하나다.** 그 걸음의 강조는 그 방문 집합의 줄 전체에
 *    두어 「여기를 지나갔고 아무것도 안 적었다」를 보인다.
 *
 * `steps` 는 **인라인 배열 리터럴**이어야 한다(spread·변수 참조·함수 호출 금지).
 * 정적 계수가 실제보다 적게 세면 얇은 전개가 P3 을 그냥 지나간다.
 *
 * **이 파일은 `tspBitmask-guide.proof.ts` 의 기록 사본이 낸 값으로 만들어졌다.**
 * 값을 손으로 고치면 본문 증명 블록과 어긋난다.
 */
export const tspWalk = {
  view: ["keyValue", "matrix"] as const,
  title: "도시 넷을 열일곱 걸음으로 순회한다",
  result: "80",
  steps: [
    {
      title: "T1 출발 상태를 놓는다",
      detail:
        "상태 표를 전부 INF 로 채우고 dp[0001][0] 에만 0 을 적는다. 도시 0 만 방문했고 위치가 0 이며 비용이 0 인 상태다.",
      entries: [
        { label: "방문 집합", value: "0001" },
        { label: "위치", value: 0 },
        { label: "쌓인 비용", value: 0 },
        { label: "값이 든 상태", value: 1 },
      ],
      matrix: [
        [0, "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
      ],
      rowLabels: [
        "0001",
        "0010",
        "0011",
        "0100",
        "0101",
        "0110",
        "0111",
        "1000",
        "1001",
        "1010",
        "1011",
        "1100",
        "1101",
        "1110",
        "1111",
      ],
      colLabels: ["v=0", "v=1", "v=2", "v=3"],
      cells: [[0, 0]] as [number, number][],
    },
    {
      title: "T2 방문 집합 0001",
      detail:
        "방문 집합 0001 에서 값이 든 위치는 0 이다. 아직 안 간 도시로 3 개의 전이를 만든다: dp[0011][1] 후보 10, dp[0101][2] 후보 15, dp[1001][3] 후보 20.",
      entries: [
        { label: "방문 집합", value: "0001" },
        { label: "값이 든 위치", value: "0" },
        { label: "이 걸음의 전이", value: 3 },
        {
          label: "새로 적은 값",
          value: "dp[0011][1] = 10 · dp[0101][2] = 15 · dp[1001][3] = 20",
        },
        { label: "값이 든 상태", value: 4 },
      ],
      matrix: [
        [0, "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 10, "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 15, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 20],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
      ],
      rowLabels: [
        "0001",
        "0010",
        "0011",
        "0100",
        "0101",
        "0110",
        "0111",
        "1000",
        "1001",
        "1010",
        "1011",
        "1100",
        "1101",
        "1110",
        "1111",
      ],
      colLabels: ["v=0", "v=1", "v=2", "v=3"],
      cells: [
        [2, 1],
        [4, 2],
        [8, 3],
      ] as [number, number][],
    },
    {
      title: "T3 방문 집합 0010",
      detail:
        "방문 집합 0010 에는 도시 0 이 없다. 도시 0 은 출발점이라 어떤 방문 집합에도 들어 있어야 하므로, 이 줄의 네 칸은 끝까지 INF 로 남는다.",
      entries: [
        { label: "방문 집합", value: "0010" },
        { label: "값이 든 위치", value: "없다 — ③ 이 네 번 걸러 낸다" },
        { label: "이 걸음의 전이", value: 0 },
        { label: "값이 든 상태", value: 4 },
      ],
      matrix: [
        [0, "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 10, "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 15, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 20],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
      ],
      rowLabels: [
        "0001",
        "0010",
        "0011",
        "0100",
        "0101",
        "0110",
        "0111",
        "1000",
        "1001",
        "1010",
        "1011",
        "1100",
        "1101",
        "1110",
        "1111",
      ],
      colLabels: ["v=0", "v=1", "v=2", "v=3"],
      cells: [
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
      ] as [number, number][],
    },
    {
      title: "T4 방문 집합 0011",
      detail:
        "방문 집합 0011 에서 값이 든 위치는 1 이다. 아직 안 간 도시로 2 개의 전이를 만든다: dp[0111][2] 후보 45, dp[1011][3] 후보 35.",
      entries: [
        { label: "방문 집합", value: "0011" },
        { label: "값이 든 위치", value: "1" },
        { label: "이 걸음의 전이", value: 2 },
        { label: "새로 적은 값", value: "dp[0111][2] = 45 · dp[1011][3] = 35" },
        { label: "값이 든 상태", value: 6 },
      ],
      matrix: [
        [0, "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 10, "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 15, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 45, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 20],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 35],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
      ],
      rowLabels: [
        "0001",
        "0010",
        "0011",
        "0100",
        "0101",
        "0110",
        "0111",
        "1000",
        "1001",
        "1010",
        "1011",
        "1100",
        "1101",
        "1110",
        "1111",
      ],
      colLabels: ["v=0", "v=1", "v=2", "v=3"],
      cells: [
        [6, 2],
        [10, 3],
      ] as [number, number][],
    },
    {
      title: "T5 방문 집합 0100",
      detail:
        "방문 집합 0100 에는 도시 0 이 없다. 도시 0 은 출발점이라 어떤 방문 집합에도 들어 있어야 하므로, 이 줄의 네 칸은 끝까지 INF 로 남는다.",
      entries: [
        { label: "방문 집합", value: "0100" },
        { label: "값이 든 위치", value: "없다 — ③ 이 네 번 걸러 낸다" },
        { label: "이 걸음의 전이", value: 0 },
        { label: "값이 든 상태", value: 6 },
      ],
      matrix: [
        [0, "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 10, "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 15, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 45, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 20],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 35],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
      ],
      rowLabels: [
        "0001",
        "0010",
        "0011",
        "0100",
        "0101",
        "0110",
        "0111",
        "1000",
        "1001",
        "1010",
        "1011",
        "1100",
        "1101",
        "1110",
        "1111",
      ],
      colLabels: ["v=0", "v=1", "v=2", "v=3"],
      cells: [
        [3, 0],
        [3, 1],
        [3, 2],
        [3, 3],
      ] as [number, number][],
    },
    {
      title: "T6 방문 집합 0101",
      detail:
        "방문 집합 0101 에서 값이 든 위치는 2 이다. 아직 안 간 도시로 2 개의 전이를 만든다: dp[0111][1] 후보 50, dp[1101][3] 후보 45.",
      entries: [
        { label: "방문 집합", value: "0101" },
        { label: "값이 든 위치", value: "2" },
        { label: "이 걸음의 전이", value: 2 },
        { label: "새로 적은 값", value: "dp[0111][1] = 50 · dp[1101][3] = 45" },
        { label: "값이 든 상태", value: 8 },
      ],
      matrix: [
        [0, "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 10, "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 15, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 50, 45, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 20],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 35],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 45],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
      ],
      rowLabels: [
        "0001",
        "0010",
        "0011",
        "0100",
        "0101",
        "0110",
        "0111",
        "1000",
        "1001",
        "1010",
        "1011",
        "1100",
        "1101",
        "1110",
        "1111",
      ],
      colLabels: ["v=0", "v=1", "v=2", "v=3"],
      cells: [
        [6, 1],
        [12, 3],
      ] as [number, number][],
    },
    {
      title: "T7 방문 집합 0110",
      detail:
        "방문 집합 0110 에는 도시 0 이 없다. 도시 0 은 출발점이라 어떤 방문 집합에도 들어 있어야 하므로, 이 줄의 네 칸은 끝까지 INF 로 남는다.",
      entries: [
        { label: "방문 집합", value: "0110" },
        { label: "값이 든 위치", value: "없다 — ③ 이 네 번 걸러 낸다" },
        { label: "이 걸음의 전이", value: 0 },
        { label: "값이 든 상태", value: 8 },
      ],
      matrix: [
        [0, "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 10, "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 15, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 50, 45, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 20],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 35],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 45],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
      ],
      rowLabels: [
        "0001",
        "0010",
        "0011",
        "0100",
        "0101",
        "0110",
        "0111",
        "1000",
        "1001",
        "1010",
        "1011",
        "1100",
        "1101",
        "1110",
        "1111",
      ],
      colLabels: ["v=0", "v=1", "v=2", "v=3"],
      cells: [
        [5, 0],
        [5, 1],
        [5, 2],
        [5, 3],
      ] as [number, number][],
    },
    {
      title: "T8 방문 집합 0111",
      detail:
        "방문 집합 0111 에서 값이 든 위치는 1 · 2 이다. 아직 안 간 도시로 2 개의 전이를 만든다: dp[1111][3] 후보 75, dp[1111][3] 후보 75 (적지 않는다).",
      entries: [
        { label: "방문 집합", value: "0111" },
        { label: "값이 든 위치", value: "1 · 2" },
        { label: "이 걸음의 전이", value: 2 },
        { label: "새로 적은 값", value: "dp[1111][3] = 75" },
        { label: "값이 든 상태", value: 9 },
      ],
      matrix: [
        [0, "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 10, "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 15, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 50, 45, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 20],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 35],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 45],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 75],
      ],
      rowLabels: [
        "0001",
        "0010",
        "0011",
        "0100",
        "0101",
        "0110",
        "0111",
        "1000",
        "1001",
        "1010",
        "1011",
        "1100",
        "1101",
        "1110",
        "1111",
      ],
      colLabels: ["v=0", "v=1", "v=2", "v=3"],
      cells: [[14, 3]] as [number, number][],
    },
    {
      title: "T9 방문 집합 1000",
      detail:
        "방문 집합 1000 에는 도시 0 이 없다. 도시 0 은 출발점이라 어떤 방문 집합에도 들어 있어야 하므로, 이 줄의 네 칸은 끝까지 INF 로 남는다.",
      entries: [
        { label: "방문 집합", value: "1000" },
        { label: "값이 든 위치", value: "없다 — ③ 이 네 번 걸러 낸다" },
        { label: "이 걸음의 전이", value: 0 },
        { label: "값이 든 상태", value: 9 },
      ],
      matrix: [
        [0, "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 10, "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 15, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 50, 45, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 20],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 35],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 45],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 75],
      ],
      rowLabels: [
        "0001",
        "0010",
        "0011",
        "0100",
        "0101",
        "0110",
        "0111",
        "1000",
        "1001",
        "1010",
        "1011",
        "1100",
        "1101",
        "1110",
        "1111",
      ],
      colLabels: ["v=0", "v=1", "v=2", "v=3"],
      cells: [
        [7, 0],
        [7, 1],
        [7, 2],
        [7, 3],
      ] as [number, number][],
    },
    {
      title: "T10 방문 집합 1001",
      detail:
        "방문 집합 1001 에서 값이 든 위치는 3 이다. 아직 안 간 도시로 2 개의 전이를 만든다: dp[1011][1] 후보 45, dp[1101][2] 후보 50.",
      entries: [
        { label: "방문 집합", value: "1001" },
        { label: "값이 든 위치", value: "3" },
        { label: "이 걸음의 전이", value: 2 },
        { label: "새로 적은 값", value: "dp[1011][1] = 45 · dp[1101][2] = 50" },
        { label: "값이 든 상태", value: 11 },
      ],
      matrix: [
        [0, "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 10, "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 15, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 50, 45, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 20],
        ["INF", "INF", "INF", "INF"],
        ["INF", 45, "INF", 35],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 50, 45],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 75],
      ],
      rowLabels: [
        "0001",
        "0010",
        "0011",
        "0100",
        "0101",
        "0110",
        "0111",
        "1000",
        "1001",
        "1010",
        "1011",
        "1100",
        "1101",
        "1110",
        "1111",
      ],
      colLabels: ["v=0", "v=1", "v=2", "v=3"],
      cells: [
        [10, 1],
        [12, 2],
      ] as [number, number][],
    },
    {
      title: "T11 방문 집합 1010",
      detail:
        "방문 집합 1010 에는 도시 0 이 없다. 도시 0 은 출발점이라 어떤 방문 집합에도 들어 있어야 하므로, 이 줄의 네 칸은 끝까지 INF 로 남는다.",
      entries: [
        { label: "방문 집합", value: "1010" },
        { label: "값이 든 위치", value: "없다 — ③ 이 네 번 걸러 낸다" },
        { label: "이 걸음의 전이", value: 0 },
        { label: "값이 든 상태", value: 11 },
      ],
      matrix: [
        [0, "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 10, "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 15, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 50, 45, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 20],
        ["INF", "INF", "INF", "INF"],
        ["INF", 45, "INF", 35],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 50, 45],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 75],
      ],
      rowLabels: [
        "0001",
        "0010",
        "0011",
        "0100",
        "0101",
        "0110",
        "0111",
        "1000",
        "1001",
        "1010",
        "1011",
        "1100",
        "1101",
        "1110",
        "1111",
      ],
      colLabels: ["v=0", "v=1", "v=2", "v=3"],
      cells: [
        [9, 0],
        [9, 1],
        [9, 2],
        [9, 3],
      ] as [number, number][],
    },
    {
      title: "T12 방문 집합 1011",
      detail:
        "방문 집합 1011 에서 값이 든 위치는 1 · 3 이다. 아직 안 간 도시로 2 개의 전이를 만든다: dp[1111][2] 후보 80, dp[1111][2] 후보 65.",
      entries: [
        { label: "방문 집합", value: "1011" },
        { label: "값이 든 위치", value: "1 · 3" },
        { label: "이 걸음의 전이", value: 2 },
        { label: "새로 적은 값", value: "dp[1111][2] = 80 · dp[1111][2] = 65" },
        { label: "값이 든 상태", value: 12 },
      ],
      matrix: [
        [0, "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 10, "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 15, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 50, 45, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 20],
        ["INF", "INF", "INF", "INF"],
        ["INF", 45, "INF", 35],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 50, 45],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 65, 75],
      ],
      rowLabels: [
        "0001",
        "0010",
        "0011",
        "0100",
        "0101",
        "0110",
        "0111",
        "1000",
        "1001",
        "1010",
        "1011",
        "1100",
        "1101",
        "1110",
        "1111",
      ],
      colLabels: ["v=0", "v=1", "v=2", "v=3"],
      cells: [
        [14, 2],
        [14, 2],
      ] as [number, number][],
    },
    {
      title: "T13 방문 집합 1100",
      detail:
        "방문 집합 1100 에는 도시 0 이 없다. 도시 0 은 출발점이라 어떤 방문 집합에도 들어 있어야 하므로, 이 줄의 네 칸은 끝까지 INF 로 남는다.",
      entries: [
        { label: "방문 집합", value: "1100" },
        { label: "값이 든 위치", value: "없다 — ③ 이 네 번 걸러 낸다" },
        { label: "이 걸음의 전이", value: 0 },
        { label: "값이 든 상태", value: 12 },
      ],
      matrix: [
        [0, "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 10, "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 15, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 50, 45, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 20],
        ["INF", "INF", "INF", "INF"],
        ["INF", 45, "INF", 35],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 50, 45],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 65, 75],
      ],
      rowLabels: [
        "0001",
        "0010",
        "0011",
        "0100",
        "0101",
        "0110",
        "0111",
        "1000",
        "1001",
        "1010",
        "1011",
        "1100",
        "1101",
        "1110",
        "1111",
      ],
      colLabels: ["v=0", "v=1", "v=2", "v=3"],
      cells: [
        [11, 0],
        [11, 1],
        [11, 2],
        [11, 3],
      ] as [number, number][],
    },
    {
      title: "T14 방문 집합 1101",
      detail:
        "방문 집합 1101 에서 값이 든 위치는 2 · 3 이다. 아직 안 간 도시로 2 개의 전이를 만든다: dp[1111][1] 후보 85, dp[1111][1] 후보 70.",
      entries: [
        { label: "방문 집합", value: "1101" },
        { label: "값이 든 위치", value: "2 · 3" },
        { label: "이 걸음의 전이", value: 2 },
        { label: "새로 적은 값", value: "dp[1111][1] = 85 · dp[1111][1] = 70" },
        { label: "값이 든 상태", value: 13 },
      ],
      matrix: [
        [0, "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 10, "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 15, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 50, 45, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 20],
        ["INF", "INF", "INF", "INF"],
        ["INF", 45, "INF", 35],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 50, 45],
        ["INF", "INF", "INF", "INF"],
        ["INF", 70, 65, 75],
      ],
      rowLabels: [
        "0001",
        "0010",
        "0011",
        "0100",
        "0101",
        "0110",
        "0111",
        "1000",
        "1001",
        "1010",
        "1011",
        "1100",
        "1101",
        "1110",
        "1111",
      ],
      colLabels: ["v=0", "v=1", "v=2", "v=3"],
      cells: [
        [14, 1],
        [14, 1],
      ] as [number, number][],
    },
    {
      title: "T15 방문 집합 1110",
      detail:
        "방문 집합 1110 에는 도시 0 이 없다. 도시 0 은 출발점이라 어떤 방문 집합에도 들어 있어야 하므로, 이 줄의 네 칸은 끝까지 INF 로 남는다.",
      entries: [
        { label: "방문 집합", value: "1110" },
        { label: "값이 든 위치", value: "없다 — ③ 이 네 번 걸러 낸다" },
        { label: "이 걸음의 전이", value: 0 },
        { label: "값이 든 상태", value: 13 },
      ],
      matrix: [
        [0, "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 10, "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 15, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 50, 45, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 20],
        ["INF", "INF", "INF", "INF"],
        ["INF", 45, "INF", 35],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 50, 45],
        ["INF", "INF", "INF", "INF"],
        ["INF", 70, 65, 75],
      ],
      rowLabels: [
        "0001",
        "0010",
        "0011",
        "0100",
        "0101",
        "0110",
        "0111",
        "1000",
        "1001",
        "1010",
        "1011",
        "1100",
        "1101",
        "1110",
        "1111",
      ],
      colLabels: ["v=0", "v=1", "v=2", "v=3"],
      cells: [
        [13, 0],
        [13, 1],
        [13, 2],
        [13, 3],
      ] as [number, number][],
    },
    {
      title: "T16 방문 집합 1111",
      detail:
        "방문 집합 1111 은 모든 도시를 담았다. 갈 수 있는 도시가 없어 ⑤ 가 후보를 전부 걸러 내고, 이 상태들은 마지막 복귀 계산에서 쓰인다.",
      entries: [
        { label: "방문 집합", value: "1111" },
        { label: "값이 든 위치", value: 3 },
        { label: "이 걸음의 전이", value: 0 },
        { label: "값이 든 상태", value: 13 },
      ],
      matrix: [
        [0, "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 10, "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 15, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 50, 45, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 20],
        ["INF", "INF", "INF", "INF"],
        ["INF", 45, "INF", 35],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 50, 45],
        ["INF", "INF", "INF", "INF"],
        ["INF", 70, 65, 75],
      ],
      rowLabels: [
        "0001",
        "0010",
        "0011",
        "0100",
        "0101",
        "0110",
        "0111",
        "1000",
        "1001",
        "1010",
        "1011",
        "1100",
        "1101",
        "1110",
        "1111",
      ],
      colLabels: ["v=0", "v=1", "v=2", "v=3"],
      cells: [
        [14, 0],
        [14, 1],
        [14, 2],
        [14, 3],
      ] as [number, number][],
    },
    {
      title: "T17 복귀 비용을 더해 답을 고른다",
      detail:
        "방문 집합 1111 의 네 위치마다 도시 0 으로 돌아오는 비용을 더한다. 0: INF + 0 = INF, 1: 70 + 10 = 80, 2: 65 + 15 = 80, 3: 75 + 20 = 95. 가장 작은 값이 답이다.",
      entries: [
        { label: "마지막 도시 0", value: "INF + 0 = INF" },
        { label: "마지막 도시 1", value: "70 + 10 = 80" },
        { label: "마지막 도시 2", value: "65 + 15 = 80" },
        { label: "마지막 도시 3", value: "75 + 20 = 95" },
        { label: "반환값", value: 80 },
      ],
      matrix: [
        [0, "INF", "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 10, "INF", "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 15, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", 50, 45, "INF"],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", "INF", 20],
        ["INF", "INF", "INF", "INF"],
        ["INF", 45, "INF", 35],
        ["INF", "INF", "INF", "INF"],
        ["INF", "INF", 50, 45],
        ["INF", "INF", "INF", "INF"],
        ["INF", 70, 65, 75],
      ],
      rowLabels: [
        "0001",
        "0010",
        "0011",
        "0100",
        "0101",
        "0110",
        "0111",
        "1000",
        "1001",
        "1010",
        "1011",
        "1100",
        "1101",
        "1110",
        "1111",
      ],
      colLabels: ["v=0", "v=1", "v=2", "v=3"],
      cells: [
        [14, 0],
        [14, 1],
        [14, 2],
        [14, 3],
      ] as [number, number][],
    },
  ] satisfies Frame[],
};
