import type { TablePlayerSpec } from "../../../_viz/player/StepPlayer";

/**
 * `deep.walk`(수행으로 알아보는 알고리즘) 절과 **같은 입력**을 쓴다 — 도시 넷짜리 거리 행렬
 * `[[0,10,15,20],[10,0,35,25],[15,35,0,30],[20,25,30,0]]` 이고 답이 80 이다. 걸음은 열일곱이다 — T1 이 출발
 * 칸을 놓고, T2~T16 이 방문 집합 0001₂~1111₂ 를 하나씩 처리하고, T17 이 복귀 비용을 더해 답을 고른다. 한 벌에
 * 모으면 정적 필름이 열일곱 장이라 `walk1`(T1~T6) · `walk2`(T7~T12) · `walk3`(T13~T17)로 가른다.
 * `result` 는 앞의 둘이 그 벌을 마친 뒤 값이 든 칸의 수, `walk3` 이 반환값이다.
 *
 * `player: "stage"` 가 걸음 재생 패널(`src/_viz/player/StepPlayer.tsx`)을 고르고, `stage: "table"` 이 2 차원 표
 * 무대(`tableStage.ts`)를 고른다. 줄은 들른 도시 집합(비트마스크), 열은 지금 도시다. `table` 은 그 걸음이 끝난
 * 뒤의 DP 테이블(값이 INF 인 칸은 `null` — 점선), `read` 는 이번 걸음에 전이를 만든 값 든 칸, `write` 는 값을
 * 바꾼 칸, `out` 은 ③ 이 늘 건너뛰는 칸(방문 집합 0 의 줄과 위치가 방문 집합 밖인 칸)이다.
 *
 * `steps` 는 **인라인 배열 리터럴**이어야 한다(spread·변수 참조·함수 호출 금지). 리터럴은 그림 사이드카의
 * `simStepsFromRef()`(정본 소스에서 만든 계측 사본을 실행해 만든 걸음)를 글자 그대로 옮긴 것이고, 둘이
 * 같은지는 `tspBitmask-guide.test.ts` 가 잰다.
 */

export const walk1 = {
  player: "stage",
  stage: "table",
  rowHeads: [
    "0000₂ {}",
    "0001₂ {0}",
    "0010₂ {1}",
    "0011₂ {0,1}",
    "0100₂ {2}",
    "0101₂ {0,2}",
    "0110₂ {1,2}",
    "0111₂ {0,1,2}",
    "1000₂ {3}",
    "1001₂ {0,3}",
    "1010₂ {1,3}",
    "1011₂ {0,1,3}",
    "1100₂ {2,3}",
    "1101₂ {0,2,3}",
    "1110₂ {1,2,3}",
    "1111₂ {0,1,2,3}",
  ],
  colHeads: [0, 1, 2, 3],
  colLabel: "지금 도시 v",
  title: "tspBitmask(전개 입력)",
  result: "8",
  steps: [
    {
      title: "T1 출발 칸 놓기",
      text: "DP 테이블을 16 줄 × 4 칸으로 잡아 모두 INF 로 채우고, 도시 0 만 들러 도시 0 에 있는 칸 dp[0001₂][0] 에 0 을 적습니다.",
      table: [
        [null, null, null, null],
        [0, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
      ],
      write: [[1, 0]],
      out: [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 2],
        [2, 3],
        [3, 2],
        [3, 3],
        [4, 0],
        [4, 1],
        [4, 3],
        [5, 1],
        [5, 3],
        [6, 0],
        [6, 3],
        [7, 3],
        [8, 0],
        [8, 1],
        [8, 2],
        [9, 1],
        [9, 2],
        [10, 0],
        [10, 2],
        [11, 2],
        [12, 0],
        [12, 1],
        [13, 1],
        [14, 0],
      ],
      rowSide: [
        "쓰지 않는 줄",
        "채움 1 / 1",
        "도시 0 없음",
        "채움 0 / 2",
        "도시 0 없음",
        "채움 0 / 2",
        "도시 0 없음",
        "채움 0 / 3",
        "도시 0 없음",
        "채움 0 / 2",
        "도시 0 없음",
        "채움 0 / 3",
        "도시 0 없음",
        "채움 0 / 3",
        "도시 0 없음",
        "채움 0 / 4",
      ],
      calc: {
        expr: "dp[0001₂][0] =",
        result: "0",
      },
    },
    {
      title: "T2 줄 0001₂ — 전이 3 개",
      text: "값 든 칸 v = 0 에서 아직 안 간 도시로 전이 3 개를 만듭니다. dp[0001₂][0] + dist[0][1] = 0 + 10 = 10 이 dp[0011₂][1] 의 INF 보다 작아 적습니다. dp[0001₂][0] + dist[0][2] = 0 + 15 = 15 가 dp[0101₂][2] 의 INF 보다 작아 적습니다. dp[0001₂][0] + dist[0][3] = 0 + 20 = 20 이 dp[1001₂][3] 의 INF 보다 작아 적습니다.",
      table: [
        [null, null, null, null],
        [0, null, null, null],
        [null, null, null, null],
        [null, 10, null, null],
        [null, null, null, null],
        [null, null, 15, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, 20],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
      ],
      read: [[1, 0]],
      write: [
        [3, 1],
        [5, 2],
        [9, 3],
      ],
      out: [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 2],
        [2, 3],
        [3, 2],
        [3, 3],
        [4, 0],
        [4, 1],
        [4, 3],
        [5, 1],
        [5, 3],
        [6, 0],
        [6, 3],
        [7, 3],
        [8, 0],
        [8, 1],
        [8, 2],
        [9, 1],
        [9, 2],
        [10, 0],
        [10, 2],
        [11, 2],
        [12, 0],
        [12, 1],
        [13, 1],
        [14, 0],
      ],
      rowSide: [
        "쓰지 않는 줄",
        "채움 1 / 1",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 0 / 3",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 0 / 3",
        "도시 0 없음",
        "채움 0 / 3",
        "도시 0 없음",
        "채움 0 / 4",
      ],
      calc: {
        expr: "전이 3 개 중 값을 바꾼 것",
        result: "3 개",
      },
    },
    {
      title: "T3 줄 0010₂ — 도시 0 없음",
      text: "줄 0010₂ 에는 도시 0 이 없어 방문 집합 안의 위치 1 의 칸이 INF 입니다. ④ 가 건너뛰어 전이가 없습니다.",
      table: [
        [null, null, null, null],
        [0, null, null, null],
        [null, null, null, null],
        [null, 10, null, null],
        [null, null, null, null],
        [null, null, 15, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, 20],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
      ],
      read: [],
      out: [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 2],
        [2, 3],
        [3, 2],
        [3, 3],
        [4, 0],
        [4, 1],
        [4, 3],
        [5, 1],
        [5, 3],
        [6, 0],
        [6, 3],
        [7, 3],
        [8, 0],
        [8, 1],
        [8, 2],
        [9, 1],
        [9, 2],
        [10, 0],
        [10, 2],
        [11, 2],
        [12, 0],
        [12, 1],
        [13, 1],
        [14, 0],
      ],
      rowSide: [
        "쓰지 않는 줄",
        "채움 1 / 1",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 0 / 3",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 0 / 3",
        "도시 0 없음",
        "채움 0 / 3",
        "도시 0 없음",
        "채움 0 / 4",
      ],
      calc: null,
    },
    {
      title: "T4 줄 0011₂ — 전이 2 개",
      text: "값 든 칸 v = 1 에서 아직 안 간 도시로 전이 2 개를 만듭니다. dp[0011₂][1] + dist[1][2] = 10 + 35 = 45 가 dp[0111₂][2] 의 INF 보다 작아 적습니다. dp[0011₂][1] + dist[1][3] = 10 + 25 = 35 가 dp[1011₂][3] 의 INF 보다 작아 적습니다.",
      table: [
        [null, null, null, null],
        [0, null, null, null],
        [null, null, null, null],
        [null, 10, null, null],
        [null, null, null, null],
        [null, null, 15, null],
        [null, null, null, null],
        [null, null, 45, null],
        [null, null, null, null],
        [null, null, null, 20],
        [null, null, null, null],
        [null, null, null, 35],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
      ],
      read: [[3, 1]],
      write: [
        [7, 2],
        [11, 3],
      ],
      out: [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 2],
        [2, 3],
        [3, 2],
        [3, 3],
        [4, 0],
        [4, 1],
        [4, 3],
        [5, 1],
        [5, 3],
        [6, 0],
        [6, 3],
        [7, 3],
        [8, 0],
        [8, 1],
        [8, 2],
        [9, 1],
        [9, 2],
        [10, 0],
        [10, 2],
        [11, 2],
        [12, 0],
        [12, 1],
        [13, 1],
        [14, 0],
      ],
      rowSide: [
        "쓰지 않는 줄",
        "채움 1 / 1",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 3",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 3",
        "도시 0 없음",
        "채움 0 / 3",
        "도시 0 없음",
        "채움 0 / 4",
      ],
      calc: {
        expr: "전이 2 개 중 값을 바꾼 것",
        result: "2 개",
      },
    },
    {
      title: "T5 줄 0100₂ — 도시 0 없음",
      text: "줄 0100₂ 에는 도시 0 이 없어 방문 집합 안의 위치 2 의 칸이 INF 입니다. ④ 가 건너뛰어 전이가 없습니다.",
      table: [
        [null, null, null, null],
        [0, null, null, null],
        [null, null, null, null],
        [null, 10, null, null],
        [null, null, null, null],
        [null, null, 15, null],
        [null, null, null, null],
        [null, null, 45, null],
        [null, null, null, null],
        [null, null, null, 20],
        [null, null, null, null],
        [null, null, null, 35],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
        [null, null, null, null],
      ],
      read: [],
      out: [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 2],
        [2, 3],
        [3, 2],
        [3, 3],
        [4, 0],
        [4, 1],
        [4, 3],
        [5, 1],
        [5, 3],
        [6, 0],
        [6, 3],
        [7, 3],
        [8, 0],
        [8, 1],
        [8, 2],
        [9, 1],
        [9, 2],
        [10, 0],
        [10, 2],
        [11, 2],
        [12, 0],
        [12, 1],
        [13, 1],
        [14, 0],
      ],
      rowSide: [
        "쓰지 않는 줄",
        "채움 1 / 1",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 3",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 3",
        "도시 0 없음",
        "채움 0 / 3",
        "도시 0 없음",
        "채움 0 / 4",
      ],
      calc: null,
    },
    {
      title: "T6 줄 0101₂ — 전이 2 개",
      text: "값 든 칸 v = 2 에서 아직 안 간 도시로 전이 2 개를 만듭니다. dp[0101₂][2] + dist[2][1] = 15 + 35 = 50 이 dp[0111₂][1] 의 INF 보다 작아 적습니다. dp[0101₂][2] + dist[2][3] = 15 + 30 = 45 가 dp[1101₂][3] 의 INF 보다 작아 적습니다.",
      table: [
        [null, null, null, null],
        [0, null, null, null],
        [null, null, null, null],
        [null, 10, null, null],
        [null, null, null, null],
        [null, null, 15, null],
        [null, null, null, null],
        [null, 50, 45, null],
        [null, null, null, null],
        [null, null, null, 20],
        [null, null, null, null],
        [null, null, null, 35],
        [null, null, null, null],
        [null, null, null, 45],
        [null, null, null, null],
        [null, null, null, null],
      ],
      read: [[5, 2]],
      write: [
        [7, 1],
        [13, 3],
      ],
      out: [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 2],
        [2, 3],
        [3, 2],
        [3, 3],
        [4, 0],
        [4, 1],
        [4, 3],
        [5, 1],
        [5, 3],
        [6, 0],
        [6, 3],
        [7, 3],
        [8, 0],
        [8, 1],
        [8, 2],
        [9, 1],
        [9, 2],
        [10, 0],
        [10, 2],
        [11, 2],
        [12, 0],
        [12, 1],
        [13, 1],
        [14, 0],
      ],
      rowSide: [
        "쓰지 않는 줄",
        "채움 1 / 1",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 3",
        "도시 0 없음",
        "채움 1 / 3",
        "도시 0 없음",
        "채움 0 / 4",
      ],
      calc: {
        expr: "전이 2 개 중 값을 바꾼 것",
        result: "2 개",
      },
    },
  ],
} satisfies TablePlayerSpec;

export const walk2 = {
  player: "stage",
  stage: "table",
  rowHeads: [
    "0000₂ {}",
    "0001₂ {0}",
    "0010₂ {1}",
    "0011₂ {0,1}",
    "0100₂ {2}",
    "0101₂ {0,2}",
    "0110₂ {1,2}",
    "0111₂ {0,1,2}",
    "1000₂ {3}",
    "1001₂ {0,3}",
    "1010₂ {1,3}",
    "1011₂ {0,1,3}",
    "1100₂ {2,3}",
    "1101₂ {0,2,3}",
    "1110₂ {1,2,3}",
    "1111₂ {0,1,2,3}",
  ],
  colHeads: [0, 1, 2, 3],
  colLabel: "지금 도시 v",
  title: "tspBitmask(전개 입력)",
  result: "12",
  steps: [
    {
      title: "T7 줄 0110₂ — 도시 0 없음",
      text: "줄 0110₂ 에는 도시 0 이 없어 방문 집합 안의 위치 1 · 2 의 칸이 모두 INF 입니다. ④ 가 건너뛰어 전이가 없습니다.",
      table: [
        [null, null, null, null],
        [0, null, null, null],
        [null, null, null, null],
        [null, 10, null, null],
        [null, null, null, null],
        [null, null, 15, null],
        [null, null, null, null],
        [null, 50, 45, null],
        [null, null, null, null],
        [null, null, null, 20],
        [null, null, null, null],
        [null, null, null, 35],
        [null, null, null, null],
        [null, null, null, 45],
        [null, null, null, null],
        [null, null, null, null],
      ],
      read: [],
      out: [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 2],
        [2, 3],
        [3, 2],
        [3, 3],
        [4, 0],
        [4, 1],
        [4, 3],
        [5, 1],
        [5, 3],
        [6, 0],
        [6, 3],
        [7, 3],
        [8, 0],
        [8, 1],
        [8, 2],
        [9, 1],
        [9, 2],
        [10, 0],
        [10, 2],
        [11, 2],
        [12, 0],
        [12, 1],
        [13, 1],
        [14, 0],
      ],
      rowSide: [
        "쓰지 않는 줄",
        "채움 1 / 1",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 3",
        "도시 0 없음",
        "채움 1 / 3",
        "도시 0 없음",
        "채움 0 / 4",
      ],
      calc: null,
    },
    {
      title: "T8 줄 0111₂ — 전이 2 개",
      text: "값 든 칸 v = 1 · 2 에서 아직 안 간 도시로 전이 2 개를 만듭니다. dp[0111₂][1] + dist[1][3] = 50 + 25 = 75 가 dp[1111₂][3] 의 INF 보다 작아 적습니다. dp[0111₂][2] + dist[2][3] = 45 + 30 = 75 가 dp[1111₂][3] 의 75 보다 작지 않아 적지 않습니다.",
      table: [
        [null, null, null, null],
        [0, null, null, null],
        [null, null, null, null],
        [null, 10, null, null],
        [null, null, null, null],
        [null, null, 15, null],
        [null, null, null, null],
        [null, 50, 45, null],
        [null, null, null, null],
        [null, null, null, 20],
        [null, null, null, null],
        [null, null, null, 35],
        [null, null, null, null],
        [null, null, null, 45],
        [null, null, null, null],
        [null, null, null, 75],
      ],
      read: [
        [7, 1],
        [7, 2],
      ],
      write: [[15, 3]],
      out: [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 2],
        [2, 3],
        [3, 2],
        [3, 3],
        [4, 0],
        [4, 1],
        [4, 3],
        [5, 1],
        [5, 3],
        [6, 0],
        [6, 3],
        [7, 3],
        [8, 0],
        [8, 1],
        [8, 2],
        [9, 1],
        [9, 2],
        [10, 0],
        [10, 2],
        [11, 2],
        [12, 0],
        [12, 1],
        [13, 1],
        [14, 0],
      ],
      rowSide: [
        "쓰지 않는 줄",
        "채움 1 / 1",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 3",
        "도시 0 없음",
        "채움 1 / 3",
        "도시 0 없음",
        "채움 1 / 4",
      ],
      calc: {
        expr: "전이 2 개 중 값을 바꾼 것",
        result: "1 개",
      },
    },
    {
      title: "T9 줄 1000₂ — 도시 0 없음",
      text: "줄 1000₂ 에는 도시 0 이 없어 방문 집합 안의 위치 3 의 칸이 INF 입니다. ④ 가 건너뛰어 전이가 없습니다.",
      table: [
        [null, null, null, null],
        [0, null, null, null],
        [null, null, null, null],
        [null, 10, null, null],
        [null, null, null, null],
        [null, null, 15, null],
        [null, null, null, null],
        [null, 50, 45, null],
        [null, null, null, null],
        [null, null, null, 20],
        [null, null, null, null],
        [null, null, null, 35],
        [null, null, null, null],
        [null, null, null, 45],
        [null, null, null, null],
        [null, null, null, 75],
      ],
      read: [],
      out: [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 2],
        [2, 3],
        [3, 2],
        [3, 3],
        [4, 0],
        [4, 1],
        [4, 3],
        [5, 1],
        [5, 3],
        [6, 0],
        [6, 3],
        [7, 3],
        [8, 0],
        [8, 1],
        [8, 2],
        [9, 1],
        [9, 2],
        [10, 0],
        [10, 2],
        [11, 2],
        [12, 0],
        [12, 1],
        [13, 1],
        [14, 0],
      ],
      rowSide: [
        "쓰지 않는 줄",
        "채움 1 / 1",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 3",
        "도시 0 없음",
        "채움 1 / 3",
        "도시 0 없음",
        "채움 1 / 4",
      ],
      calc: null,
    },
    {
      title: "T10 줄 1001₂ — 전이 2 개",
      text: "값 든 칸 v = 3 에서 아직 안 간 도시로 전이 2 개를 만듭니다. dp[1001₂][3] + dist[3][1] = 20 + 25 = 45 가 dp[1011₂][1] 의 INF 보다 작아 적습니다. dp[1001₂][3] + dist[3][2] = 20 + 30 = 50 이 dp[1101₂][2] 의 INF 보다 작아 적습니다.",
      table: [
        [null, null, null, null],
        [0, null, null, null],
        [null, null, null, null],
        [null, 10, null, null],
        [null, null, null, null],
        [null, null, 15, null],
        [null, null, null, null],
        [null, 50, 45, null],
        [null, null, null, null],
        [null, null, null, 20],
        [null, null, null, null],
        [null, 45, null, 35],
        [null, null, null, null],
        [null, null, 50, 45],
        [null, null, null, null],
        [null, null, null, 75],
      ],
      read: [[9, 3]],
      write: [
        [11, 1],
        [13, 2],
      ],
      out: [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 2],
        [2, 3],
        [3, 2],
        [3, 3],
        [4, 0],
        [4, 1],
        [4, 3],
        [5, 1],
        [5, 3],
        [6, 0],
        [6, 3],
        [7, 3],
        [8, 0],
        [8, 1],
        [8, 2],
        [9, 1],
        [9, 2],
        [10, 0],
        [10, 2],
        [11, 2],
        [12, 0],
        [12, 1],
        [13, 1],
        [14, 0],
      ],
      rowSide: [
        "쓰지 않는 줄",
        "채움 1 / 1",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 1 / 4",
      ],
      calc: {
        expr: "전이 2 개 중 값을 바꾼 것",
        result: "2 개",
      },
    },
    {
      title: "T11 줄 1010₂ — 도시 0 없음",
      text: "줄 1010₂ 에는 도시 0 이 없어 방문 집합 안의 위치 1 · 3 의 칸이 모두 INF 입니다. ④ 가 건너뛰어 전이가 없습니다.",
      table: [
        [null, null, null, null],
        [0, null, null, null],
        [null, null, null, null],
        [null, 10, null, null],
        [null, null, null, null],
        [null, null, 15, null],
        [null, null, null, null],
        [null, 50, 45, null],
        [null, null, null, null],
        [null, null, null, 20],
        [null, null, null, null],
        [null, 45, null, 35],
        [null, null, null, null],
        [null, null, 50, 45],
        [null, null, null, null],
        [null, null, null, 75],
      ],
      read: [],
      out: [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 2],
        [2, 3],
        [3, 2],
        [3, 3],
        [4, 0],
        [4, 1],
        [4, 3],
        [5, 1],
        [5, 3],
        [6, 0],
        [6, 3],
        [7, 3],
        [8, 0],
        [8, 1],
        [8, 2],
        [9, 1],
        [9, 2],
        [10, 0],
        [10, 2],
        [11, 2],
        [12, 0],
        [12, 1],
        [13, 1],
        [14, 0],
      ],
      rowSide: [
        "쓰지 않는 줄",
        "채움 1 / 1",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 1 / 4",
      ],
      calc: null,
    },
    {
      title: "T12 줄 1011₂ — 전이 2 개",
      text: "값 든 칸 v = 1 · 3 에서 아직 안 간 도시로 전이 2 개를 만듭니다. dp[1011₂][1] + dist[1][2] = 45 + 35 = 80 이 dp[1111₂][2] 의 INF 보다 작아 적습니다. dp[1011₂][3] + dist[3][2] = 35 + 30 = 65 가 dp[1111₂][2] 의 80 보다 작아 적습니다.",
      table: [
        [null, null, null, null],
        [0, null, null, null],
        [null, null, null, null],
        [null, 10, null, null],
        [null, null, null, null],
        [null, null, 15, null],
        [null, null, null, null],
        [null, 50, 45, null],
        [null, null, null, null],
        [null, null, null, 20],
        [null, null, null, null],
        [null, 45, null, 35],
        [null, null, null, null],
        [null, null, 50, 45],
        [null, null, null, null],
        [null, null, 65, 75],
      ],
      read: [
        [11, 1],
        [11, 3],
      ],
      write: [[15, 2]],
      out: [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 2],
        [2, 3],
        [3, 2],
        [3, 3],
        [4, 0],
        [4, 1],
        [4, 3],
        [5, 1],
        [5, 3],
        [6, 0],
        [6, 3],
        [7, 3],
        [8, 0],
        [8, 1],
        [8, 2],
        [9, 1],
        [9, 2],
        [10, 0],
        [10, 2],
        [11, 2],
        [12, 0],
        [12, 1],
        [13, 1],
        [14, 0],
      ],
      rowSide: [
        "쓰지 않는 줄",
        "채움 1 / 1",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 2 / 4",
      ],
      calc: {
        expr: "전이 2 개 중 값을 바꾼 것",
        result: "2 개",
      },
    },
  ],
} satisfies TablePlayerSpec;

export const walk3 = {
  player: "stage",
  stage: "table",
  rowHeads: [
    "0000₂ {}",
    "0001₂ {0}",
    "0010₂ {1}",
    "0011₂ {0,1}",
    "0100₂ {2}",
    "0101₂ {0,2}",
    "0110₂ {1,2}",
    "0111₂ {0,1,2}",
    "1000₂ {3}",
    "1001₂ {0,3}",
    "1010₂ {1,3}",
    "1011₂ {0,1,3}",
    "1100₂ {2,3}",
    "1101₂ {0,2,3}",
    "1110₂ {1,2,3}",
    "1111₂ {0,1,2,3}",
  ],
  colHeads: [0, 1, 2, 3],
  colLabel: "지금 도시 v",
  title: "tspBitmask(전개 입력)",
  result: "80",
  steps: [
    {
      title: "T13 줄 1100₂ — 도시 0 없음",
      text: "줄 1100₂ 에는 도시 0 이 없어 방문 집합 안의 위치 2 · 3 의 칸이 모두 INF 입니다. ④ 가 건너뛰어 전이가 없습니다.",
      table: [
        [null, null, null, null],
        [0, null, null, null],
        [null, null, null, null],
        [null, 10, null, null],
        [null, null, null, null],
        [null, null, 15, null],
        [null, null, null, null],
        [null, 50, 45, null],
        [null, null, null, null],
        [null, null, null, 20],
        [null, null, null, null],
        [null, 45, null, 35],
        [null, null, null, null],
        [null, null, 50, 45],
        [null, null, null, null],
        [null, null, 65, 75],
      ],
      read: [],
      out: [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 2],
        [2, 3],
        [3, 2],
        [3, 3],
        [4, 0],
        [4, 1],
        [4, 3],
        [5, 1],
        [5, 3],
        [6, 0],
        [6, 3],
        [7, 3],
        [8, 0],
        [8, 1],
        [8, 2],
        [9, 1],
        [9, 2],
        [10, 0],
        [10, 2],
        [11, 2],
        [12, 0],
        [12, 1],
        [13, 1],
        [14, 0],
      ],
      rowSide: [
        "쓰지 않는 줄",
        "채움 1 / 1",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 2 / 4",
      ],
      calc: null,
    },
    {
      title: "T14 줄 1101₂ — 전이 2 개",
      text: "값 든 칸 v = 2 · 3 에서 아직 안 간 도시로 전이 2 개를 만듭니다. dp[1101₂][2] + dist[2][1] = 50 + 35 = 85 가 dp[1111₂][1] 의 INF 보다 작아 적습니다. dp[1101₂][3] + dist[3][1] = 45 + 25 = 70 이 dp[1111₂][1] 의 85 보다 작아 적습니다.",
      table: [
        [null, null, null, null],
        [0, null, null, null],
        [null, null, null, null],
        [null, 10, null, null],
        [null, null, null, null],
        [null, null, 15, null],
        [null, null, null, null],
        [null, 50, 45, null],
        [null, null, null, null],
        [null, null, null, 20],
        [null, null, null, null],
        [null, 45, null, 35],
        [null, null, null, null],
        [null, null, 50, 45],
        [null, null, null, null],
        [null, 70, 65, 75],
      ],
      read: [
        [13, 2],
        [13, 3],
      ],
      write: [[15, 1]],
      out: [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 2],
        [2, 3],
        [3, 2],
        [3, 3],
        [4, 0],
        [4, 1],
        [4, 3],
        [5, 1],
        [5, 3],
        [6, 0],
        [6, 3],
        [7, 3],
        [8, 0],
        [8, 1],
        [8, 2],
        [9, 1],
        [9, 2],
        [10, 0],
        [10, 2],
        [11, 2],
        [12, 0],
        [12, 1],
        [13, 1],
        [14, 0],
      ],
      rowSide: [
        "쓰지 않는 줄",
        "채움 1 / 1",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 3 / 4",
      ],
      calc: {
        expr: "전이 2 개 중 값을 바꾼 것",
        result: "2 개",
      },
    },
    {
      title: "T15 줄 1110₂ — 도시 0 없음",
      text: "줄 1110₂ 에는 도시 0 이 없어 방문 집합 안의 위치 1 · 2 · 3 의 칸이 모두 INF 입니다. ④ 가 건너뛰어 전이가 없습니다.",
      table: [
        [null, null, null, null],
        [0, null, null, null],
        [null, null, null, null],
        [null, 10, null, null],
        [null, null, null, null],
        [null, null, 15, null],
        [null, null, null, null],
        [null, 50, 45, null],
        [null, null, null, null],
        [null, null, null, 20],
        [null, null, null, null],
        [null, 45, null, 35],
        [null, null, null, null],
        [null, null, 50, 45],
        [null, null, null, null],
        [null, 70, 65, 75],
      ],
      read: [],
      out: [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 2],
        [2, 3],
        [3, 2],
        [3, 3],
        [4, 0],
        [4, 1],
        [4, 3],
        [5, 1],
        [5, 3],
        [6, 0],
        [6, 3],
        [7, 3],
        [8, 0],
        [8, 1],
        [8, 2],
        [9, 1],
        [9, 2],
        [10, 0],
        [10, 2],
        [11, 2],
        [12, 0],
        [12, 1],
        [13, 1],
        [14, 0],
      ],
      rowSide: [
        "쓰지 않는 줄",
        "채움 1 / 1",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 3 / 4",
      ],
      calc: null,
    },
    {
      title: "T16 줄 1111₂ — 갈 도시 없음",
      text: "줄 1111₂ 의 값 든 칸 v = 1 · 2 · 3 에서 아직 안 간 도시가 없어, ⑤ 가 후보 12 개를 모두 거릅니다.",
      table: [
        [null, null, null, null],
        [0, null, null, null],
        [null, null, null, null],
        [null, 10, null, null],
        [null, null, null, null],
        [null, null, 15, null],
        [null, null, null, null],
        [null, 50, 45, null],
        [null, null, null, null],
        [null, null, null, 20],
        [null, null, null, null],
        [null, 45, null, 35],
        [null, null, null, null],
        [null, null, 50, 45],
        [null, null, null, null],
        [null, 70, 65, 75],
      ],
      read: [
        [15, 1],
        [15, 2],
        [15, 3],
      ],
      out: [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 2],
        [2, 3],
        [3, 2],
        [3, 3],
        [4, 0],
        [4, 1],
        [4, 3],
        [5, 1],
        [5, 3],
        [6, 0],
        [6, 3],
        [7, 3],
        [8, 0],
        [8, 1],
        [8, 2],
        [9, 1],
        [9, 2],
        [10, 0],
        [10, 2],
        [11, 2],
        [12, 0],
        [12, 1],
        [13, 1],
        [14, 0],
      ],
      rowSide: [
        "쓰지 않는 줄",
        "채움 1 / 1",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 3 / 4",
      ],
      calc: null,
    },
    {
      title: "T17 답 = 80",
      text: "모든 도시를 들른 줄 1111₂ 의 칸마다 도시 0 으로 돌아오는 비용을 더합니다. dp[1111₂][0] + dist[0][0] = INF + 0 = INF · dp[1111₂][1] + dist[1][0] = 70 + 10 = 80 · dp[1111₂][2] + dist[2][0] = 65 + 15 = 80 · dp[1111₂][3] + dist[3][0] = 75 + 20 = 95 이고, 가장 작은 80 이 답입니다.",
      table: [
        [null, null, null, null],
        [0, null, null, null],
        [null, null, null, null],
        [null, 10, null, null],
        [null, null, null, null],
        [null, null, 15, null],
        [null, null, null, null],
        [null, 50, 45, null],
        [null, null, null, null],
        [null, null, null, 20],
        [null, null, null, null],
        [null, 45, null, 35],
        [null, null, null, null],
        [null, null, 50, 45],
        [null, null, null, null],
        [null, 70, 65, 75],
      ],
      read: [
        [15, 0],
        [15, 1],
        [15, 2],
        [15, 3],
      ],
      out: [
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 2],
        [2, 3],
        [3, 2],
        [3, 3],
        [4, 0],
        [4, 1],
        [4, 3],
        [5, 1],
        [5, 3],
        [6, 0],
        [6, 3],
        [7, 3],
        [8, 0],
        [8, 1],
        [8, 2],
        [9, 1],
        [9, 2],
        [10, 0],
        [10, 2],
        [11, 2],
        [12, 0],
        [12, 1],
        [13, 1],
        [14, 0],
      ],
      rowSide: [
        "쓰지 않는 줄",
        "채움 1 / 1",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 1 / 2",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 2 / 3",
        "도시 0 없음",
        "채움 3 / 4",
      ],
      calc: {
        expr: "min(INF, 80, 80, 95) =",
        result: "80",
      },
    },
  ],
} satisfies TablePlayerSpec;
