import type { ArrayPlayerSpec } from "../../../_viz/player/StepPlayer";

/**
 * `deep.walk`(수행으로 알아보는 알고리즘) 절과 **같은 입력**(`fftMultiply([3, 1, 4, 1], [2, 5])`)을 쓴다. 걸음은
 * 길이 정하기(T1) · 채우기(T2) · A 의 재배치와 세 바퀴(T3~T6) · B 의 변환(T7) · 자리별 곱(T8) · 역방향 재배치와
 * 세 바퀴(T9 · T10) · 나눗셈(T11) · 반올림(T12)이다.
 *
 * `player: "stage"` 가 걸음 재생 패널(`src/_viz/player/StepPlayer.tsx`)을 고르고, `stage: "array"` 가 배열
 * 무대(`arrayStage.ts`)를 고른다. 첫 줄은 코드의 `aRe · aIm` 을 칸마다 복소수 하나로 적은 것이고(T8 부터 같은
 * 배열이 곱 다항식을 담는다), 그 아래 `bRe · bIm` 줄과 「반환」 줄이 쌓인다. 복소수 한 칸이 격자 두 칸 폭이라
 * 배열 칸과 두 줄 모두 `span: 2` 다. 나비 연산 누적 수는 남는 변수다.
 *
 * `steps` 는 **인라인 배열 리터럴**이어야 한다(spread·변수 참조·함수 호출 금지).
 * 정적 계수가 실제보다 적게 세면 얇은 전개가 P3 을 그냥 지나간다. 리터럴은 그림 사이드카의
 * `simStepsFromRef()`(정본 실행에서 만든 걸음)를 글자 그대로 옮긴 것이고, 둘이 같은지는
 * `fftMultiply-guide.test.ts` 가 잰다.
 */

export const fftWalk = {
  player: "stage",
  stage: "array",
  arrayName: "aRe · aIm",
  rangeLabel: "변환 길이 N",
  title: "fftMultiply([3, 1, 4, 1], [2, 5])",
  result: "[6, 17, 13, 22, 5]",
  steps: [
    {
      title: "T1 길이 정하기",
      text: "두 배열 다 비어 있지 않습니다. 결과 길이 L 은 4 + 2 − 1 = 5 이고, size 를 1 → 2 → 4 → 8 로 두 배씩 늘려 5 이상인 가장 작은 2 의 거듭제곱 8 을 얻습니다. 배열 넷은 아직 잡지 않았습니다.",
      range: [0, 7],
      pointers: {},
      span: 2,
      array: [null, null, null, null, null, null, null, null],
      rangeSide: "N = 8",
      write: [],
      read: [],
      calc: {
        expr: "4 + 2 − 1 = 5",
        result: "N = 8",
      },
      vars: "나비 0",
      layers: [
        {
          name: "bRe · bIm",
          values: [null, null, null, null, null, null, null, null],
          write: [],
          read: [],
          span: 2,
        },
        {
          name: "반환",
          values: [null, null, null, null, null],
          write: [],
          span: 2,
        },
      ],
    },
    {
      title: "T2 계수 채우기",
      text: "길이 8 짜리 배열 넷을 잡고 a 를 aRe 에, b 를 bRe 에 앞에서부터 옮깁니다. 남는 칸과 허수부는 모두 0 입니다.",
      range: [0, 7],
      pointers: {},
      span: 2,
      array: ["3", "1", "4", "1", "0", "0", "0", "0"],
      rangeSide: "N = 8",
      write: [0, 1, 2, 3, 4, 5, 6, 7],
      read: [],
      calc: {
        expr: "a → aRe · b → bRe",
        result: "허수부 0",
      },
      vars: "나비 0",
      layers: [
        {
          name: "bRe · bIm",
          values: ["2", "5", "0", "0", "0", "0", "0", "0"],
          write: [0, 1, 2, 3, 4, 5, 6, 7],
          read: [],
          span: 2,
        },
        {
          name: "반환",
          values: [null, null, null, null, null],
          write: [],
          span: 2,
        },
      ],
    },
    {
      title: "T3 A 재배치",
      text: "자리 i 의 값을 i 의 이진 표기 3 자리를 뒤집은 자리로 옮깁니다. 맞바뀌는 짝은 1 ↔ 4 · 3 ↔ 6 이고 나머지 자리는 뒤집어도 제자리입니다.",
      range: [0, 7],
      pointers: {},
      span: 2,
      array: ["3", "0", "4", "0", "1", "0", "1", "0"],
      rangeSide: "N = 8",
      write: [1, 3, 4, 6],
      read: [],
      calc: {
        expr: "1 ↔ 4 · 3 ↔ 6",
        result: "맞바꾼 짝 2",
      },
      vars: "나비 0",
      layers: [
        {
          name: "bRe · bIm",
          values: ["2", "5", "0", "0", "0", "0", "0", "0"],
          write: [],
          read: [],
          span: 2,
        },
        {
          name: "반환",
          values: [null, null, null, null, null],
          write: [],
          span: 2,
        },
      ],
    },
    {
      title: "T4 A 블록 길이 2",
      text: "배열을 2 칸 블록 4 개로 끊고, 블록마다 앞 절반의 칸 k 와 뒤 절반의 칸 k + 1 을 짝지어 나비 연산을 합니다. 블록 0 의 마지막 짝은 u = 3, v = 0, 회전 인자 ω^0 = 1 로 3 과 3 을 냅니다.",
      range: [0, 7],
      pointers: {},
      span: 2,
      array: ["3", "3", "4", "4", "1", "1", "1", "1"],
      rangeSide: "블록 길이 2 · 블록 4 개",
      write: [0, 1, 2, 3, 4, 5, 6, 7],
      read: [],
      calc: {
        expr: "3 ± (1)·(0)",
        result: "3 · 3",
      },
      vars: "나비 4",
      layers: [
        {
          name: "bRe · bIm",
          values: ["2", "5", "0", "0", "0", "0", "0", "0"],
          write: [],
          read: [],
          span: 2,
        },
        {
          name: "반환",
          values: [null, null, null, null, null],
          write: [],
          span: 2,
        },
      ],
    },
    {
      title: "T5 A 블록 길이 4",
      text: "배열을 4 칸 블록 2 개로 끊고, 블록마다 앞 절반의 칸 k 와 뒤 절반의 칸 k + 2 를 짝지어 나비 연산을 합니다. 블록 0 의 마지막 짝은 u = 3, v = 4, 회전 인자 ω^1 = i 로 3+4i 와 3-4i 를 냅니다.",
      range: [0, 7],
      pointers: {},
      span: 2,
      array: ["7", "3+4i", "-1", "3-4i", "2", "1+i", "0", "1-i"],
      rangeSide: "블록 길이 4 · 블록 2 개",
      write: [0, 1, 2, 3, 4, 5, 6, 7],
      read: [],
      calc: {
        expr: "3 ± (i)·(4)",
        result: "3+4i · 3-4i",
      },
      vars: "나비 8",
      layers: [
        {
          name: "bRe · bIm",
          values: ["2", "5", "0", "0", "0", "0", "0", "0"],
          write: [],
          read: [],
          span: 2,
        },
        {
          name: "반환",
          values: [null, null, null, null, null],
          write: [],
          span: 2,
        },
      ],
    },
    {
      title: "T6 A 블록 길이 8",
      text: "배열을 8 칸 블록 1 개로 끊고, 블록마다 앞 절반의 칸 k 와 뒤 절반의 칸 k + 4 를 짝지어 나비 연산을 합니다. 블록 0 의 마지막 짝은 u = 3-4i, v = 1-i, 회전 인자 ω^3 = -0.71+0.71i 로 3-2.59i 와 3-5.41i 를 냅니다.",
      range: [0, 7],
      pointers: {},
      span: 2,
      array: ["9", "3+5.41i", "-1", "3-2.59i", "5", "3+2.59i", "-1", "3-5.41i"],
      rangeSide: "블록 길이 8 · 블록 1 개",
      write: [0, 1, 2, 3, 4, 5, 6, 7],
      read: [],
      calc: {
        expr: "3-4i ± (-0.71+0.71i)·(1-i)",
        result: "3-2.59i · 3-5.41i",
      },
      vars: "나비 12",
      layers: [
        {
          name: "bRe · bIm",
          values: ["2", "5", "0", "0", "0", "0", "0", "0"],
          write: [],
          read: [],
          span: 2,
        },
        {
          name: "반환",
          values: [null, null, null, null, null],
          write: [],
          span: 2,
        },
      ],
    },
    {
      title: "T7 B 도 같은 3 바퀴",
      text: "B 에 같은 재배치와 블록 길이 2 · 4 · 8 바퀴를 한 번에 합니다. 끝나면 bRe · bIm 이 B 를 단위근 8 개에서 평가한 값입니다.",
      range: [0, 7],
      pointers: {},
      span: 2,
      array: ["9", "3+5.41i", "-1", "3-2.59i", "5", "3+2.59i", "-1", "3-5.41i"],
      rangeSide: "N = 8",
      write: [],
      read: [],
      calc: {
        expr: "재배치 → 바퀴 3",
        result: "나비 12",
      },
      vars: "나비 24",
      layers: [
        {
          name: "bRe · bIm",
          values: [
            "7",
            "5.54+3.54i",
            "2+5i",
            "-1.54+3.54i",
            "-3",
            "-1.54-3.54i",
            "2-5i",
            "5.54-3.54i",
          ],
          write: [0, 1, 2, 3, 4, 5, 6, 7],
          read: [],
          span: 2,
        },
        {
          name: "반환",
          values: [null, null, null, null, null],
          write: [],
          span: 2,
        },
      ],
    },
    {
      title: "T8 자리마다 곱",
      text: "같은 자리의 두 복소수를 한 번씩 곱해 aRe · aIm 에 씁니다. 이제 이 배열이 곱 다항식 C 를 단위근 8 개에서 평가한 값입니다. 자리 1 은 3+5.41i 와 5.54+3.54i 의 곱입니다.",
      range: [0, 7],
      pointers: {},
      span: 2,
      array: [
        "63",
        "-2.54+40.58i",
        "-2-5i",
        "4.54+14.58i",
        "-15",
        "4.54-14.58i",
        "-2+5i",
        "-2.54-40.58i",
      ],
      rangeSide: "N = 8",
      write: [0, 1, 2, 3, 4, 5, 6, 7],
      read: [],
      calc: {
        expr: "(3+5.41i)·(5.54+3.54i)",
        result: "-2.54+40.58i",
      },
      vars: "나비 24",
      layers: [
        {
          name: "bRe · bIm",
          values: [
            "7",
            "5.54+3.54i",
            "2+5i",
            "-1.54+3.54i",
            "-3",
            "-1.54-3.54i",
            "2-5i",
            "5.54-3.54i",
          ],
          write: [],
          read: [0, 1, 2, 3, 4, 5, 6, 7],
          span: 2,
        },
        {
          name: "반환",
          values: [null, null, null, null, null],
          write: [],
          span: 2,
        },
      ],
    },
    {
      title: "T9 역방향 재배치",
      text: "역변환도 같은 재배치로 시작합니다. 맞바뀌는 짝은 정방향과 같은 1 ↔ 4 · 3 ↔ 6 입니다.",
      range: [0, 7],
      pointers: {},
      span: 2,
      array: [
        "63",
        "-15",
        "-2-5i",
        "-2+5i",
        "-2.54+40.58i",
        "4.54-14.58i",
        "4.54+14.58i",
        "-2.54-40.58i",
      ],
      rangeSide: "N = 8",
      write: [1, 3, 4, 6],
      read: [],
      calc: {
        expr: "1 ↔ 4 · 3 ↔ 6",
        result: "맞바꾼 짝 2",
      },
      vars: "나비 24",
      layers: [
        {
          name: "bRe · bIm",
          values: [
            "7",
            "5.54+3.54i",
            "2+5i",
            "-1.54+3.54i",
            "-3",
            "-1.54-3.54i",
            "2-5i",
            "5.54-3.54i",
          ],
          write: [],
          read: [],
          span: 2,
        },
        {
          name: "반환",
          values: [null, null, null, null, null],
          write: [],
          span: 2,
        },
      ],
    },
    {
      title: "T10 역방향 3 바퀴",
      text: "각도의 부호만 뒤집어 같은 나비 연산을 블록 길이 2 · 4 · 8 로 합니다. 허수부가 모두 0 근방으로 모이고 실수부에 계수의 8 배가 남습니다.",
      range: [0, 7],
      pointers: {},
      span: 2,
      array: ["48", "136", "104", "176", "40", "0", "0", "0"],
      rangeSide: "N = 8",
      write: [0, 1, 2, 3, 4, 5, 6, 7],
      read: [],
      calc: {
        expr: "각도 × (−1)",
        result: "나비 12",
      },
      vars: "나비 36",
      layers: [
        {
          name: "bRe · bIm",
          values: [
            "7",
            "5.54+3.54i",
            "2+5i",
            "-1.54+3.54i",
            "-3",
            "-1.54-3.54i",
            "2-5i",
            "5.54-3.54i",
          ],
          write: [],
          read: [],
          span: 2,
        },
        {
          name: "반환",
          values: [null, null, null, null, null],
          write: [],
          span: 2,
        },
      ],
    },
    {
      title: "T11 8 로 나누기",
      text: "배열 전체를 길이 8 로 한 번 나눕니다. 나눗셈은 역변환의 끝에서 이 한 번뿐입니다.",
      range: [0, 7],
      pointers: {},
      span: 2,
      array: ["6", "17", "13", "22", "5", "0", "0", "0"],
      rangeSide: "N = 8",
      write: [0, 1, 2, 3, 4, 5, 6, 7],
      read: [],
      calc: {
        expr: "136 ÷ 8",
        result: "17",
      },
      vars: "나비 36",
      layers: [
        {
          name: "bRe · bIm",
          values: [
            "7",
            "5.54+3.54i",
            "2+5i",
            "-1.54+3.54i",
            "-3",
            "-1.54-3.54i",
            "2-5i",
            "5.54-3.54i",
          ],
          write: [],
          read: [],
          span: 2,
        },
        {
          name: "반환",
          values: [null, null, null, null, null],
          write: [],
          span: 2,
        },
      ],
    },
    {
      title: "T12 반올림해 돌려주기",
      text: "앞 5 칸의 실수부를 반올림해 반환 배열에 씁니다. 자리 2 의 값이 12.999999999999998 로 정수에서 가장 멀리 떨어져 있고, 반올림이 그 차이를 지웁니다.",
      range: [0, 7],
      pointers: {},
      span: 2,
      array: ["6", "17", "13", "22", "5", "0", "0", "0"],
      rangeSide: "N = 8",
      write: [],
      read: [0, 1, 2, 3, 4],
      calc: {
        expr: "Math.round(12.999999999999998)",
        result: "13",
      },
      vars: "나비 36",
      layers: [
        {
          name: "bRe · bIm",
          values: [
            "7",
            "5.54+3.54i",
            "2+5i",
            "-1.54+3.54i",
            "-3",
            "-1.54-3.54i",
            "2-5i",
            "5.54-3.54i",
          ],
          write: [],
          read: [],
          span: 2,
        },
        {
          name: "반환",
          values: ["6", "17", "13", "22", "5"],
          write: [0, 1, 2, 3, 4],
          span: 2,
        },
      ],
    },
  ],
} satisfies ArrayPlayerSpec;
