import type { ArrayPlayerSpec } from "../../../_viz/player/StepPlayer";

/**
 * `deep.walk`(수행으로 알아보는 알고리즘) 절과 **같은 입력**(`n = 4`)을 쓴다. 걸음 하나는 `place` 호출
 * 하나이고, 프레임 제목은 원고의 걸음 번호(`T#`)로 연다 — P3 이 그 자리를 잰다.
 *
 * `player: "stage"` 가 걸음 재생 패널(`src/_viz/player/StepPlayer.tsx`)을 고르고, `stage: "array"` 가
 * 배열 무대(`arrayStage.ts`)를 고른다. 「놓은 열」 줄이 행마다 놓은 퀸의 열(아직 안 채운 행은 빈 칸)이고,
 * 쥔 구간 `range` 는 이미 채운 행이다. 그 아래 `layers` 에 세 정수 `cols` · `diag1` · `diag2` 를 비트
 * 자리마다 칸 하나로 쌓고(읽음은 이번 판정에서 열을 막은 비트, 새로 씀은 부모가 방금 켠 비트), 맨 아래
 * 「판정」 줄에 행 `row` 의 열마다 판정을 적는다. 판(N×N)을 그리는 새 무대는 만들지 않았다.
 *
 * `steps` 는 **인라인 배열 리터럴**이어야 한다(spread·변수 참조·함수 호출 금지). 정적 계수가 실제보다
 * 적게 세면 얇은 전개가 P3 을 그냥 지나간다. 리터럴은 그림 사이드카의 `simStepsFromRef()`(정본 실행에서
 * 만든 걸음)를 글자 그대로 옮긴 것이고, 둘이 같은지는 `nQueens-guide.test.ts` 가 잰다.
 */
export const board = {
  player: "stage",
  stage: "array",
  arrayName: "놓은 열",
  rangeLabel: "채운 행",
  title: "nQueens(4) — 호출 17 번으로 배치 2 개를 센다",
  result: "2",
  steps: [
    {
      title: "T1 place(0) · 빈 판",
      text: "행 0 의 열 4 개를 판정합니다 — c=0 ③ · c=1 ③ · c=2 ③ · c=3 ③.",
      array: [null, null, null, null],
      range: null,
      rangeSide: "채운 행 0 개",
      read: [],
      write: [],
      pointers: {
        row: 0,
      },
      calc: null,
      vars: "count = 0",
      layers: [
        {
          name: "cols",
          values: [0, 0, 0, 0],
          read: [],
          write: [],
          side: "켜짐 0",
        },
        {
          name: "diag1",
          values: [0, 0, 0, 0, 0, 0, 0],
          read: [],
          write: [],
          side: "켜짐 0",
        },
        {
          name: "diag2",
          values: [0, 0, 0, 0, 0, 0, 0],
          read: [],
          write: [],
          side: "켜짐 0",
        },
        {
          name: "판정",
          values: ["③", "③", "③", "③"],
          write: [0, 1, 2, 3],
          side: "행 0",
        },
      ],
    },
    {
      title: "T2 place(1) · (0,0) 을 놓은 뒤",
      text: "행 1 의 열 4 개를 판정합니다 — c=0 은 cols 비트에 막혀 ② · c=1 은 diag1 비트에 막혀 ② · c=2 ③ · c=3 ③.",
      array: [0, null, null, null],
      range: [0, 0],
      rangeSide: "채운 행 1 개",
      read: [],
      write: [0],
      pointers: {
        row: 1,
      },
      calc: {
        expr: "(0,0) 의 d1 · d2",
        result: "3 · 0",
      },
      vars: "count = 0",
      layers: [
        {
          name: "cols",
          values: [1, 0, 0, 0],
          read: [0],
          write: [0],
          side: "켜짐 1",
        },
        {
          name: "diag1",
          values: [0, 0, 0, 1, 0, 0, 0],
          read: [3],
          write: [3],
          side: "켜짐 1",
        },
        {
          name: "diag2",
          values: [1, 0, 0, 0, 0, 0, 0],
          read: [],
          write: [0],
          side: "켜짐 1",
        },
        {
          name: "판정",
          values: ["②열", "②\\", "③", "③"],
          write: [0, 1, 2, 3],
          side: "행 1",
        },
      ],
    },
    {
      title: "T3 place(2) · (1,2) 를 놓은 뒤",
      text: "행 2 의 열 4 개를 판정합니다 — c=0 은 cols 비트에 막혀 ② · c=1 은 diag2 비트에 막혀 ② · c=2 는 cols 비트에 막혀 ② · c=3 은 diag1 비트에 막혀 ②. 놓을 열이 없어 자식 없이 돌아갑니다.",
      array: [0, 2, null, null],
      range: [0, 1],
      rangeSide: "채운 행 2 개",
      read: [],
      write: [1],
      pointers: {
        row: 2,
      },
      calc: {
        expr: "(1,2) 의 d1 · d2",
        result: "2 · 3",
      },
      vars: "count = 0",
      layers: [
        {
          name: "cols",
          values: [1, 0, 1, 0],
          read: [0, 2],
          write: [2],
          side: "켜짐 2",
        },
        {
          name: "diag1",
          values: [0, 0, 1, 1, 0, 0, 0],
          read: [2],
          write: [2],
          side: "켜짐 2",
        },
        {
          name: "diag2",
          values: [1, 0, 0, 1, 0, 0, 0],
          read: [3],
          write: [3],
          side: "켜짐 2",
        },
        {
          name: "판정",
          values: ["②열", "②/", "②열", "②\\"],
          write: [0, 1, 2, 3],
          side: "행 2",
        },
      ],
    },
    {
      title: "T4 place(2) · (1,3) 을 놓은 뒤",
      text: "행 2 의 열 4 개를 판정합니다 — c=0 은 cols 비트에 막혀 ② · c=1 ③ · c=2 는 diag1 비트에 막혀 ② · c=3 은 cols 비트에 막혀 ②.",
      array: [0, 3, null, null],
      range: [0, 1],
      rangeSide: "채운 행 2 개",
      read: [],
      write: [1],
      pointers: {
        row: 2,
      },
      calc: {
        expr: "(1,3) 의 d1 · d2",
        result: "1 · 4",
      },
      vars: "count = 0",
      layers: [
        {
          name: "cols",
          values: [1, 0, 0, 1],
          read: [0, 3],
          write: [3],
          side: "켜짐 2",
        },
        {
          name: "diag1",
          values: [0, 1, 0, 1, 0, 0, 0],
          read: [3],
          write: [1],
          side: "켜짐 2",
        },
        {
          name: "diag2",
          values: [1, 0, 0, 0, 1, 0, 0],
          read: [],
          write: [4],
          side: "켜짐 2",
        },
        {
          name: "판정",
          values: ["②열", "③", "②\\", "②열"],
          write: [0, 1, 2, 3],
          side: "행 2",
        },
      ],
    },
    {
      title: "T5 place(3) · (2,1) 을 놓은 뒤",
      text: "행 3 의 열 4 개를 판정합니다 — c=0 은 cols 비트에 막혀 ② · c=1 은 cols 비트에 막혀 ② · c=2 는 diag1 비트에 막혀 ② · c=3 은 cols 비트에 막혀 ②. 놓을 열이 없어 자식 없이 돌아갑니다.",
      array: [0, 3, 1, null],
      range: [0, 2],
      rangeSide: "채운 행 3 개",
      read: [],
      write: [2],
      pointers: {
        row: 3,
      },
      calc: {
        expr: "(2,1) 의 d1 · d2",
        result: "4 · 3",
      },
      vars: "count = 0",
      layers: [
        {
          name: "cols",
          values: [1, 1, 0, 1],
          read: [0, 1, 3],
          write: [1],
          side: "켜짐 3",
        },
        {
          name: "diag1",
          values: [0, 1, 0, 1, 1, 0, 0],
          read: [4],
          write: [4],
          side: "켜짐 3",
        },
        {
          name: "diag2",
          values: [1, 0, 0, 1, 1, 0, 0],
          read: [],
          write: [3],
          side: "켜짐 3",
        },
        {
          name: "판정",
          values: ["②열", "②열", "②\\", "②열"],
          write: [0, 1, 2, 3],
          side: "행 3",
        },
      ],
    },
    {
      title: "T6 place(1) · (0,1) 을 놓은 뒤",
      text: "행 1 의 열 4 개를 판정합니다 — c=0 은 diag2 비트에 막혀 ② · c=1 은 cols 비트에 막혀 ② · c=2 는 diag1 비트에 막혀 ② · c=3 ③.",
      array: [1, null, null, null],
      range: [0, 0],
      rangeSide: "채운 행 1 개",
      read: [],
      write: [0],
      pointers: {
        row: 1,
      },
      calc: {
        expr: "(0,1) 의 d1 · d2",
        result: "2 · 1",
      },
      vars: "count = 0",
      layers: [
        {
          name: "cols",
          values: [0, 1, 0, 0],
          read: [1],
          write: [1],
          side: "켜짐 1",
        },
        {
          name: "diag1",
          values: [0, 0, 1, 0, 0, 0, 0],
          read: [2],
          write: [2],
          side: "켜짐 1",
        },
        {
          name: "diag2",
          values: [0, 1, 0, 0, 0, 0, 0],
          read: [1],
          write: [1],
          side: "켜짐 1",
        },
        {
          name: "판정",
          values: ["②/", "②열", "②\\", "③"],
          write: [0, 1, 2, 3],
          side: "행 1",
        },
      ],
    },
    {
      title: "T7 place(2) · (1,3) 을 놓은 뒤",
      text: "행 2 의 열 4 개를 판정합니다 — c=0 ③ · c=1 은 cols 비트에 막혀 ② · c=2 는 diag2 비트에 막혀 ② · c=3 은 cols 비트에 막혀 ②.",
      array: [1, 3, null, null],
      range: [0, 1],
      rangeSide: "채운 행 2 개",
      read: [],
      write: [1],
      pointers: {
        row: 2,
      },
      calc: {
        expr: "(1,3) 의 d1 · d2",
        result: "1 · 4",
      },
      vars: "count = 0",
      layers: [
        {
          name: "cols",
          values: [0, 1, 0, 1],
          read: [1, 3],
          write: [3],
          side: "켜짐 2",
        },
        {
          name: "diag1",
          values: [0, 1, 1, 0, 0, 0, 0],
          read: [],
          write: [1],
          side: "켜짐 2",
        },
        {
          name: "diag2",
          values: [0, 1, 0, 0, 1, 0, 0],
          read: [4],
          write: [4],
          side: "켜짐 2",
        },
        {
          name: "판정",
          values: ["③", "②열", "②/", "②열"],
          write: [0, 1, 2, 3],
          side: "행 2",
        },
      ],
    },
    {
      title: "T8 place(3) · (2,0) 을 놓은 뒤",
      text: "행 3 의 열 4 개를 판정합니다 — c=0 은 cols 비트에 막혀 ② · c=1 은 cols 비트에 막혀 ② · c=2 ③ · c=3 은 cols 비트에 막혀 ②.",
      array: [1, 3, 0, null],
      range: [0, 2],
      rangeSide: "채운 행 3 개",
      read: [],
      write: [2],
      pointers: {
        row: 3,
      },
      calc: {
        expr: "(2,0) 의 d1 · d2",
        result: "5 · 2",
      },
      vars: "count = 0",
      layers: [
        {
          name: "cols",
          values: [1, 1, 0, 1],
          read: [0, 1, 3],
          write: [0],
          side: "켜짐 3",
        },
        {
          name: "diag1",
          values: [0, 1, 1, 0, 0, 1, 0],
          read: [],
          write: [5],
          side: "켜짐 3",
        },
        {
          name: "diag2",
          values: [0, 1, 1, 0, 1, 0, 0],
          read: [],
          write: [2],
          side: "켜짐 3",
        },
        {
          name: "판정",
          values: ["②열", "②열", "③", "②열"],
          write: [0, 1, 2, 3],
          side: "행 3",
        },
      ],
    },
    {
      title: "T9 place(4) · 행 4 도달 ①",
      text: "row = 4 가 n 과 같아 ① count 가 1 이 됩니다. 판에 놓인 퀸은 (0,1)(1,3)(2,0)(3,2) 입니다.",
      array: [1, 3, 0, 2],
      range: [0, 3],
      rangeSide: "채운 행 4 개",
      read: [],
      write: [3],
      pointers: {
        row: 4,
      },
      calc: {
        expr: "(3,2) 의 d1 · d2",
        result: "4 · 5",
      },
      vars: "count = 1",
      layers: [
        {
          name: "cols",
          values: [1, 1, 1, 1],
          read: [],
          write: [2],
          side: "켜짐 4",
        },
        {
          name: "diag1",
          values: [0, 1, 1, 0, 1, 1, 0],
          read: [],
          write: [4],
          side: "켜짐 4",
        },
        {
          name: "diag2",
          values: [0, 1, 1, 0, 1, 1, 0],
          read: [],
          write: [5],
          side: "켜짐 4",
        },
        {
          name: "판정",
          values: [null, null, null, null],
          write: [],
          side: "row = 4 · 판정 없음",
        },
      ],
    },
    {
      title: "T10 place(1) · (0,2) 를 놓은 뒤",
      text: "행 1 의 열 4 개를 판정합니다 — c=0 ③ · c=1 은 diag2 비트에 막혀 ② · c=2 는 cols 비트에 막혀 ② · c=3 은 diag1 비트에 막혀 ②.",
      array: [2, null, null, null],
      range: [0, 0],
      rangeSide: "채운 행 1 개",
      read: [],
      write: [0],
      pointers: {
        row: 1,
      },
      calc: {
        expr: "(0,2) 의 d1 · d2",
        result: "1 · 2",
      },
      vars: "count = 1",
      layers: [
        {
          name: "cols",
          values: [0, 0, 1, 0],
          read: [2],
          write: [2],
          side: "켜짐 1",
        },
        {
          name: "diag1",
          values: [0, 1, 0, 0, 0, 0, 0],
          read: [1],
          write: [1],
          side: "켜짐 1",
        },
        {
          name: "diag2",
          values: [0, 0, 1, 0, 0, 0, 0],
          read: [2],
          write: [2],
          side: "켜짐 1",
        },
        {
          name: "판정",
          values: ["③", "②/", "②열", "②\\"],
          write: [0, 1, 2, 3],
          side: "행 1",
        },
      ],
    },
    {
      title: "T11 place(2) · (1,0) 을 놓은 뒤",
      text: "행 2 의 열 4 개를 판정합니다 — c=0 은 cols 비트에 막혀 ② · c=1 은 diag1 비트에 막혀 ② · c=2 는 cols 비트에 막혀 ② · c=3 ③.",
      array: [2, 0, null, null],
      range: [0, 1],
      rangeSide: "채운 행 2 개",
      read: [],
      write: [1],
      pointers: {
        row: 2,
      },
      calc: {
        expr: "(1,0) 의 d1 · d2",
        result: "4 · 1",
      },
      vars: "count = 1",
      layers: [
        {
          name: "cols",
          values: [1, 0, 1, 0],
          read: [0, 2],
          write: [0],
          side: "켜짐 2",
        },
        {
          name: "diag1",
          values: [0, 1, 0, 0, 1, 0, 0],
          read: [4],
          write: [4],
          side: "켜짐 2",
        },
        {
          name: "diag2",
          values: [0, 1, 1, 0, 0, 0, 0],
          read: [],
          write: [1],
          side: "켜짐 2",
        },
        {
          name: "판정",
          values: ["②열", "②\\", "②열", "③"],
          write: [0, 1, 2, 3],
          side: "행 2",
        },
      ],
    },
    {
      title: "T12 place(3) · (2,3) 을 놓은 뒤",
      text: "행 3 의 열 4 개를 판정합니다 — c=0 은 cols 비트에 막혀 ② · c=1 ③ · c=2 는 cols 비트에 막혀 ② · c=3 은 cols 비트에 막혀 ②.",
      array: [2, 0, 3, null],
      range: [0, 2],
      rangeSide: "채운 행 3 개",
      read: [],
      write: [2],
      pointers: {
        row: 3,
      },
      calc: {
        expr: "(2,3) 의 d1 · d2",
        result: "2 · 5",
      },
      vars: "count = 1",
      layers: [
        {
          name: "cols",
          values: [1, 0, 1, 1],
          read: [0, 2, 3],
          write: [3],
          side: "켜짐 3",
        },
        {
          name: "diag1",
          values: [0, 1, 1, 0, 1, 0, 0],
          read: [],
          write: [2],
          side: "켜짐 3",
        },
        {
          name: "diag2",
          values: [0, 1, 1, 0, 0, 1, 0],
          read: [],
          write: [5],
          side: "켜짐 3",
        },
        {
          name: "판정",
          values: ["②열", "③", "②열", "②열"],
          write: [0, 1, 2, 3],
          side: "행 3",
        },
      ],
    },
    {
      title: "T13 place(4) · 행 4 도달 ①",
      text: "row = 4 가 n 과 같아 ① count 가 2 가 됩니다. 판에 놓인 퀸은 (0,2)(1,0)(2,3)(3,1) 입니다.",
      array: [2, 0, 3, 1],
      range: [0, 3],
      rangeSide: "채운 행 4 개",
      read: [],
      write: [3],
      pointers: {
        row: 4,
      },
      calc: {
        expr: "(3,1) 의 d1 · d2",
        result: "5 · 4",
      },
      vars: "count = 2",
      layers: [
        {
          name: "cols",
          values: [1, 1, 1, 1],
          read: [],
          write: [1],
          side: "켜짐 4",
        },
        {
          name: "diag1",
          values: [0, 1, 1, 0, 1, 1, 0],
          read: [],
          write: [5],
          side: "켜짐 4",
        },
        {
          name: "diag2",
          values: [0, 1, 1, 0, 1, 1, 0],
          read: [],
          write: [4],
          side: "켜짐 4",
        },
        {
          name: "판정",
          values: [null, null, null, null],
          write: [],
          side: "row = 4 · 판정 없음",
        },
      ],
    },
    {
      title: "T14 place(1) · (0,3) 을 놓은 뒤",
      text: "행 1 의 열 4 개를 판정합니다 — c=0 ③ · c=1 ③ · c=2 는 diag2 비트에 막혀 ② · c=3 은 cols 비트에 막혀 ②.",
      array: [3, null, null, null],
      range: [0, 0],
      rangeSide: "채운 행 1 개",
      read: [],
      write: [0],
      pointers: {
        row: 1,
      },
      calc: {
        expr: "(0,3) 의 d1 · d2",
        result: "0 · 3",
      },
      vars: "count = 2",
      layers: [
        {
          name: "cols",
          values: [0, 0, 0, 1],
          read: [3],
          write: [3],
          side: "켜짐 1",
        },
        {
          name: "diag1",
          values: [1, 0, 0, 0, 0, 0, 0],
          read: [],
          write: [0],
          side: "켜짐 1",
        },
        {
          name: "diag2",
          values: [0, 0, 0, 1, 0, 0, 0],
          read: [3],
          write: [3],
          side: "켜짐 1",
        },
        {
          name: "판정",
          values: ["③", "③", "②/", "②열"],
          write: [0, 1, 2, 3],
          side: "행 1",
        },
      ],
    },
    {
      title: "T15 place(2) · (1,0) 을 놓은 뒤",
      text: "행 2 의 열 4 개를 판정합니다 — c=0 은 cols 비트에 막혀 ② · c=1 은 diag1 비트에 막혀 ② · c=2 ③ · c=3 은 cols 비트에 막혀 ②.",
      array: [3, 0, null, null],
      range: [0, 1],
      rangeSide: "채운 행 2 개",
      read: [],
      write: [1],
      pointers: {
        row: 2,
      },
      calc: {
        expr: "(1,0) 의 d1 · d2",
        result: "4 · 1",
      },
      vars: "count = 2",
      layers: [
        {
          name: "cols",
          values: [1, 0, 0, 1],
          read: [0, 3],
          write: [0],
          side: "켜짐 2",
        },
        {
          name: "diag1",
          values: [1, 0, 0, 0, 1, 0, 0],
          read: [4],
          write: [4],
          side: "켜짐 2",
        },
        {
          name: "diag2",
          values: [0, 1, 0, 1, 0, 0, 0],
          read: [],
          write: [1],
          side: "켜짐 2",
        },
        {
          name: "판정",
          values: ["②열", "②\\", "③", "②열"],
          write: [0, 1, 2, 3],
          side: "행 2",
        },
      ],
    },
    {
      title: "T16 place(3) · (2,2) 를 놓은 뒤",
      text: "행 3 의 열 4 개를 판정합니다 — c=0 은 cols 비트에 막혀 ② · c=1 은 diag2 비트에 막혀 ② · c=2 는 cols 비트에 막혀 ② · c=3 은 cols 비트에 막혀 ②. 놓을 열이 없어 자식 없이 돌아갑니다.",
      array: [3, 0, 2, null],
      range: [0, 2],
      rangeSide: "채운 행 3 개",
      read: [],
      write: [2],
      pointers: {
        row: 3,
      },
      calc: {
        expr: "(2,2) 의 d1 · d2",
        result: "3 · 4",
      },
      vars: "count = 2",
      layers: [
        {
          name: "cols",
          values: [1, 0, 1, 1],
          read: [0, 2, 3],
          write: [2],
          side: "켜짐 3",
        },
        {
          name: "diag1",
          values: [1, 0, 0, 1, 1, 0, 0],
          read: [],
          write: [3],
          side: "켜짐 3",
        },
        {
          name: "diag2",
          values: [0, 1, 0, 1, 1, 0, 0],
          read: [4],
          write: [4],
          side: "켜짐 3",
        },
        {
          name: "판정",
          values: ["②열", "②/", "②열", "②열"],
          write: [0, 1, 2, 3],
          side: "행 3",
        },
      ],
    },
    {
      title: "T17 place(2) · (1,1) 을 놓은 뒤",
      text: "행 2 의 열 4 개를 판정합니다 — c=0 은 diag2 비트에 막혀 ② · c=1 은 cols 비트에 막혀 ② · c=2 는 diag1 비트에 막혀 ② · c=3 은 cols 비트에 막혀 ②. 놓을 열이 없어 자식 없이 돌아갑니다.",
      array: [3, 1, null, null],
      range: [0, 1],
      rangeSide: "채운 행 2 개",
      read: [],
      write: [1],
      pointers: {
        row: 2,
      },
      calc: {
        expr: "(1,1) 의 d1 · d2",
        result: "3 · 2",
      },
      vars: "count = 2",
      layers: [
        {
          name: "cols",
          values: [0, 1, 0, 1],
          read: [1, 3],
          write: [1],
          side: "켜짐 2",
        },
        {
          name: "diag1",
          values: [1, 0, 0, 1, 0, 0, 0],
          read: [3],
          write: [3],
          side: "켜짐 2",
        },
        {
          name: "diag2",
          values: [0, 0, 1, 1, 0, 0, 0],
          read: [2],
          write: [2],
          side: "켜짐 2",
        },
        {
          name: "판정",
          values: ["②/", "②열", "②\\", "②열"],
          write: [0, 1, 2, 3],
          side: "행 2",
        },
      ],
    },
  ],
} satisfies ArrayPlayerSpec;
