import type { ArrayPlayerSpec } from "../../../_viz/player/StepPlayer";

/**
 * `deep.walk`(수행으로 알아보는 알고리즘) 절과 **같은 입력**을 쓴다 — 상한 `n = 30`. 걸음은 T1~T9 이고,
 * 본문의 걸음 표(증명 블록 `walk-trace`)와 번호가 같다.
 *
 * `player: "stage"` 가 걸음 재생 패널(`src/_viz/player/StepPlayer.tsx`)을 고르고, `stage: "array"` 가
 * 배열 무대(`arrayStage.ts`)를 고른다. 무대의 줄은 2 부터 30 까지의 수이고 칸의 값이 곧 수라
 * `valueAxis` 로 인덱스 줄을 뺀다. 앞 걸음이 이미 지운 칸은 `out`(이번 걸음 밖), 이번에 지우는 칸은
 * `write`, 바깥 반복이 읽는 칸 `i` 는 `read` 다. 소수 `p` 가 지우는 칸은 `p²` 부터 `n` 까지라 그
 * 범위를 조각 괄호(`pieces`)로 걸고, `p` 와 `p²` 는 포인터로 적는다. 아래 줄 「처음 지운 p」 는 수마다
 * 그 수를 처음 지운 소수다 — 정본은 이 값을 저장하지 않지만, 합성수가 가장 작은 소인수의 걸음에서
 * 처음 지워진다는 것을 무대에서 보이려고 걸음 기록에서 만든다.
 *
 * `steps` 는 **인라인 배열 리터럴**이어야 한다(spread·변수 참조·함수 호출 금지). 리터럴은 그림 사이드카의
 * `simStepsFromRef()`(정본과 같은 절차의 걸음 기록)를 글자 그대로 옮긴 것이고, 둘이 같은지는
 * `sieveOfEratosthenes-guide.test.ts` 가 잰다.
 */

export const sieveWalk = {
  player: "stage",
  stage: "array",
  arrayName: "체 배열",
  rangeLabel: "수",
  valueAxis: true,
  title: "sieveOfEratosthenes(30)",
  result: "[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]",
  steps: [
    {
      title: "T1 i = 2 · 지워지지 않았다",
      text: "칸 2 가 지워지지 않았습니다. 그래서 2 는 소수입니다.",
      array: [
        2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23, 24, 25, 26, 27, 28, 29, 30,
      ],
      range: [0, 28],
      out: [],
      read: [0],
      write: [],
      pointers: {
        i: 2,
      },
      calc: {
        expr: "isComposite[2]",
        result: "거짓",
      },
      rangeSide: "지운 칸 0 / 29",
      vars: "지우기 0 번",
      layers: [
        {
          name: "처음 지운 p",
          values: [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          write: [],
          caret: false,
        },
      ],
    },
    {
      title: "T2 p = 2 · 4 부터 14 칸",
      text: "4 부터 2 씩 더해 14 칸을 지웁니다. 처음 지운 칸이 14 개입니다.",
      array: [
        2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23, 24, 25, 26, 27, 28, 29, 30,
      ],
      range: [0, 28],
      out: [],
      read: [],
      write: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
      pointers: {
        p: 2,
        "p²": 4,
      },
      calc: {
        expr: "2 × 2",
        result: "4",
      },
      pieces: [
        {
          label: "p = 2",
          from: 2,
          to: 28,
          tone: "left",
          text: "4 부터 2 씩",
        },
      ],
      rangeSide: "지운 칸 14 / 29",
      vars: "지우기 14 번",
      layers: [
        {
          name: "처음 지운 p",
          values: [
            null,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
          ],
          write: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
          caret: false,
        },
      ],
    },
    {
      title: "T3 i = 3 · 지워지지 않았다",
      text: "칸 3 이 지워지지 않았습니다. 그래서 3 은 소수입니다.",
      array: [
        2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23, 24, 25, 26, 27, 28, 29, 30,
      ],
      range: [0, 28],
      out: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
      read: [1],
      write: [],
      pointers: {
        i: 3,
      },
      calc: {
        expr: "isComposite[3]",
        result: "거짓",
      },
      rangeSide: "지운 칸 14 / 29",
      vars: "지우기 14 번",
      layers: [
        {
          name: "처음 지운 p",
          values: [
            null,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
            null,
            2,
          ],
          write: [],
          caret: false,
        },
      ],
    },
    {
      title: "T4 p = 3 · 9 부터 8 칸",
      text: "9 부터 3 씩 더해 8 칸을 지웁니다. 처음 지운 칸이 4 개, 이미 지운 칸을 다시 지운 것이 4 개입니다.",
      array: [
        2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23, 24, 25, 26, 27, 28, 29, 30,
      ],
      range: [0, 28],
      out: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
      read: [],
      write: [7, 10, 13, 16, 19, 22, 25, 28],
      pointers: {
        p: 3,
        "p²": 9,
      },
      calc: {
        expr: "3 × 3",
        result: "9",
      },
      pieces: [
        {
          label: "p = 3",
          from: 7,
          to: 28,
          tone: "left",
          text: "9 부터 3 씩",
        },
      ],
      rangeSide: "지운 칸 18 / 29",
      vars: "지우기 22 번",
      layers: [
        {
          name: "처음 지운 p",
          values: [
            null,
            null,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
          ],
          write: [7, 13, 19, 25],
          caret: false,
        },
      ],
    },
    {
      title: "T5 i = 4 · 지워졌다",
      text: "칸 4 가 이미 지워져 있습니다. 4 의 배수는 더 작은 소수가 이미 지웠으므로 건너뜁니다.",
      array: [
        2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23, 24, 25, 26, 27, 28, 29, 30,
      ],
      range: [0, 28],
      out: [2, 4, 6, 7, 8, 10, 12, 13, 14, 16, 18, 19, 20, 22, 24, 25, 26, 28],
      read: [2],
      write: [],
      pointers: {
        i: 4,
      },
      calc: {
        expr: "isComposite[4]",
        result: "참",
      },
      rangeSide: "지운 칸 18 / 29",
      vars: "지우기 22 번",
      layers: [
        {
          name: "처음 지운 p",
          values: [
            null,
            null,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
          ],
          write: [],
          caret: false,
        },
      ],
    },
    {
      title: "T6 i = 5 · 지워지지 않았다",
      text: "칸 5 가 지워지지 않았습니다. 그래서 5 는 소수입니다.",
      array: [
        2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23, 24, 25, 26, 27, 28, 29, 30,
      ],
      range: [0, 28],
      out: [2, 4, 6, 7, 8, 10, 12, 13, 14, 16, 18, 19, 20, 22, 24, 25, 26, 28],
      read: [3],
      write: [],
      pointers: {
        i: 5,
      },
      calc: {
        expr: "isComposite[5]",
        result: "거짓",
      },
      rangeSide: "지운 칸 18 / 29",
      vars: "지우기 22 번",
      layers: [
        {
          name: "처음 지운 p",
          values: [
            null,
            null,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
          ],
          write: [],
          caret: false,
        },
      ],
    },
    {
      title: "T7 p = 5 · 25 부터 2 칸",
      text: "25 부터 5 씩 더해 2 칸을 지웁니다. 처음 지운 칸이 1 개, 이미 지운 칸을 다시 지운 것이 1 개입니다.",
      array: [
        2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23, 24, 25, 26, 27, 28, 29, 30,
      ],
      range: [0, 28],
      out: [2, 4, 6, 7, 8, 10, 12, 13, 14, 16, 18, 19, 20, 22, 24, 25, 26, 28],
      read: [],
      write: [23, 28],
      pointers: {
        p: 5,
        "p²": 25,
      },
      calc: {
        expr: "5 × 5",
        result: "25",
      },
      pieces: [
        {
          label: "p = 5",
          from: 23,
          to: 28,
          tone: "left",
          text: "25 부터 5 씩",
        },
      ],
      rangeSide: "지운 칸 19 / 29",
      vars: "지우기 24 번",
      layers: [
        {
          name: "처음 지운 p",
          values: [
            null,
            null,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
            5,
            2,
            3,
            2,
            null,
            2,
          ],
          write: [23],
          caret: false,
        },
      ],
    },
    {
      title: "T8 i = 6 · 36 > 30",
      text: "6 의 제곱 36 이 상한 30 을 넘어 바깥 반복이 끝납니다.",
      array: [
        2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23, 24, 25, 26, 27, 28, 29, 30,
      ],
      range: [0, 28],
      out: [
        2, 4, 6, 7, 8, 10, 12, 13, 14, 16, 18, 19, 20, 22, 23, 24, 25, 26, 28,
      ],
      read: [],
      write: [],
      pointers: {
        i: 6,
      },
      calc: {
        expr: "6 × 6",
        result: "36 > 30",
      },
      rangeSide: "지운 칸 19 / 29",
      vars: "지우기 24 번",
      layers: [
        {
          name: "처음 지운 p",
          values: [
            null,
            null,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
            5,
            2,
            3,
            2,
            null,
            2,
          ],
          write: [],
          caret: false,
        },
      ],
    },
    {
      title: "T9 남은 칸 10 개를 모은다",
      text: "2 부터 30 까지 지워지지 않은 칸 10 개를 오름차순으로 답에 담습니다.",
      array: [
        2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23, 24, 25, 26, 27, 28, 29, 30,
      ],
      range: [0, 28],
      out: [
        2, 4, 6, 7, 8, 10, 12, 13, 14, 16, 18, 19, 20, 22, 23, 24, 25, 26, 28,
      ],
      read: [],
      write: [0, 1, 3, 5, 9, 11, 15, 17, 21, 27],
      calc: null,
      rangeSide: "지운 칸 19 / 29",
      vars: "지우기 24 번",
      layers: [
        {
          name: "처음 지운 p",
          values: [
            null,
            null,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
            null,
            2,
            3,
            2,
            null,
            2,
            5,
            2,
            3,
            2,
            null,
            2,
          ],
          write: [],
          caret: false,
        },
      ],
    },
  ],
} satisfies ArrayPlayerSpec;
