/**
 * `deep.walk`(수행으로 알아보는 알고리즘) 절과 **같은 입력**을 쓴다 — `nums = [3, 4, 7, 2, -3, 1, 4, 2]`,
 * `k = 7`. `scan` 은 개수 맵에 빈 누적합을 적는 T1 과, 원소 하나씩을 처리하는 T2~T9 다.
 *
 * `player: "stage"` 가 걸음 재생 패널(`src/_viz/player/StepPlayer.tsx`)을 고르고, `stage: "array"` 가
 * 배열 무대(`arrayStage.ts`)를 고른다. 입력 배열 `nums` 위의 괄호는 지금까지 더한 앞부분 `[0, r]` 이고,
 * 그 아래 괄호는 이번 걸음이 찾은 구간이다. 맨 아래에 개수 맵(`map`, 패턴 `KeyValueTable`)을 키 줄 ·
 * 개수 줄로 쌓는다 — 자리는 첫 걸음부터 맵이 가장 커졌을 때의 키 수만큼 잡아 두고, 아직 안 넣은 자리는
 * 점선이다(SPEC §13 배열 줄). 찾은 키는 읽음, 넣거나 늘린 키는 새로 씀이고, 찾았는데 없던 키는 ▲ 줄
 * 곁말에 적는다. 이번 누적합은 값 줄 곁말, 조회 한 줄은 알약, answer 는 남는 변수다.
 *
 * `steps` 는 **인라인 배열 리터럴**이어야 한다(spread·변수 참조·함수 호출 금지).
 * 정적 계수가 실제보다 적게 세면 얇은 전개가 P3 을 그냥 지나간다. 리터럴은 그림 사이드카의
 * `simStepsFromRef()`(정본 실행에서 만든 걸음)를 글자 그대로 옮긴 것이고, 둘이 같은지는
 * `subarraySumEqualsK-guide.test.ts` 가 잰다.
 */

export const scan = {
  player: "stage",
  stage: "array",
  arrayName: "nums",
  rangeLabel: "앞부분",
  title: "subarraySumEqualsK([3, 4, 7, 2, -3, 1, 4, 2], 7)",
  result: "4",
  steps: [
    {
      title: "T1 seen.set(0, 1)",
      text: "개수 맵에 빈 누적합 0 을 한 번 적습니다. 원소를 하나도 더하지 않은 누적합 P[0] 입니다.",
      array: [3, 4, 7, 2, -3, 1, 4, 2],
      range: null,
      read: [],
      write: [],
      calc: {
        expr: "seen[0]",
        result: "1",
      },
      vars: "answer = 0",
      rangeSide: "누적합 0",
      pieces: [],
      map: {
        keyLabel: "seen 키",
        valueLabel: "개수",
        entries: [[0, 1]],
        slots: 8,
        read: [],
        write: [0],
        note: "",
      },
    },
    {
      title: "T2 r = 0",
      text: "nums[0] = 3 을 더해 누적합이 3 입니다. 찾는 키 -4 가 개수 맵에 없어 answer 는 0 그대로입니다. 키 3 을 개수 1 로 새로 넣습니다.",
      array: [3, 4, 7, 2, -3, 1, 4, 2],
      range: [0, 0],
      read: [0],
      write: [],
      calc: {
        expr: "seen.get(3 − 7)",
        result: "없음 → 0",
      },
      vars: "answer = 0",
      rangeSide: "누적합 3",
      pieces: [],
      map: {
        keyLabel: "seen 키",
        valueLabel: "개수",
        entries: [
          [0, 1],
          [3, 1],
        ],
        slots: 8,
        read: [],
        write: [3],
        note: "찾는 키 -4 · 없음",
      },
    },
    {
      title: "T3 r = 1",
      text: "nums[1] = 4 를 더해 누적합이 7 입니다. 찾는 키 0 이 개수 맵에 1 번 있어 answer 가 1 이 됩니다. 키 7 을 개수 1 로 새로 넣습니다.",
      array: [3, 4, 7, 2, -3, 1, 4, 2],
      range: [0, 1],
      read: [1],
      write: [],
      calc: {
        expr: "seen.get(7 − 7)",
        result: "1",
      },
      vars: "answer = 1",
      rangeSide: "누적합 7",
      pieces: [
        {
          label: "찾은 구간",
          from: 0,
          to: 1,
          tone: "left",
          text: "[0,1]",
        },
      ],
      map: {
        keyLabel: "seen 키",
        valueLabel: "개수",
        entries: [
          [0, 1],
          [3, 1],
          [7, 1],
        ],
        slots: 8,
        read: [0],
        write: [7],
        note: "찾는 키 0 · 개수 1",
      },
    },
    {
      title: "T4 r = 2",
      text: "nums[2] = 7 을 더해 누적합이 14 입니다. 찾는 키 7 이 개수 맵에 1 번 있어 answer 가 2 가 됩니다. 키 14 를 개수 1 로 새로 넣습니다.",
      array: [3, 4, 7, 2, -3, 1, 4, 2],
      range: [0, 2],
      read: [2],
      write: [],
      calc: {
        expr: "seen.get(14 − 7)",
        result: "1",
      },
      vars: "answer = 2",
      rangeSide: "누적합 14",
      pieces: [
        {
          label: "찾은 구간",
          from: 2,
          to: 2,
          tone: "left",
          text: "[2,2]",
        },
      ],
      map: {
        keyLabel: "seen 키",
        valueLabel: "개수",
        entries: [
          [0, 1],
          [3, 1],
          [7, 1],
          [14, 1],
        ],
        slots: 8,
        read: [7],
        write: [14],
        note: "찾는 키 7 · 개수 1",
      },
    },
    {
      title: "T5 r = 3",
      text: "nums[3] = 2 를 더해 누적합이 16 입니다. 찾는 키 9 가 개수 맵에 없어 answer 는 2 그대로입니다. 키 16 을 개수 1 로 새로 넣습니다.",
      array: [3, 4, 7, 2, -3, 1, 4, 2],
      range: [0, 3],
      read: [3],
      write: [],
      calc: {
        expr: "seen.get(16 − 7)",
        result: "없음 → 0",
      },
      vars: "answer = 2",
      rangeSide: "누적합 16",
      pieces: [],
      map: {
        keyLabel: "seen 키",
        valueLabel: "개수",
        entries: [
          [0, 1],
          [3, 1],
          [7, 1],
          [14, 1],
          [16, 1],
        ],
        slots: 8,
        read: [],
        write: [16],
        note: "찾는 키 9 · 없음",
      },
    },
    {
      title: "T6 r = 4",
      text: "nums[4] = -3 을 더해 누적합이 13 입니다. 찾는 키 6 이 개수 맵에 없어 answer 는 2 그대로입니다. 키 13 을 개수 1 로 새로 넣습니다.",
      array: [3, 4, 7, 2, -3, 1, 4, 2],
      range: [0, 4],
      read: [4],
      write: [],
      calc: {
        expr: "seen.get(13 − 7)",
        result: "없음 → 0",
      },
      vars: "answer = 2",
      rangeSide: "누적합 13",
      pieces: [],
      map: {
        keyLabel: "seen 키",
        valueLabel: "개수",
        entries: [
          [0, 1],
          [3, 1],
          [7, 1],
          [14, 1],
          [16, 1],
          [13, 1],
        ],
        slots: 8,
        read: [],
        write: [13],
        note: "찾는 키 6 · 없음",
      },
    },
    {
      title: "T7 r = 5",
      text: "nums[5] = 1 을 더해 누적합이 14 입니다. 찾는 키 7 이 개수 맵에 1 번 있어 answer 가 3 이 됩니다. 키 14 의 개수를 1 에서 2 로 늘립니다.",
      array: [3, 4, 7, 2, -3, 1, 4, 2],
      range: [0, 5],
      read: [5],
      write: [],
      calc: {
        expr: "seen.get(14 − 7)",
        result: "1",
      },
      vars: "answer = 3",
      rangeSide: "누적합 14",
      pieces: [
        {
          label: "찾은 구간",
          from: 2,
          to: 5,
          tone: "left",
          text: "[2,5]",
        },
      ],
      map: {
        keyLabel: "seen 키",
        valueLabel: "개수",
        entries: [
          [0, 1],
          [3, 1],
          [7, 1],
          [14, 2],
          [16, 1],
          [13, 1],
        ],
        slots: 8,
        read: [7],
        write: [14],
        note: "찾는 키 7 · 개수 1",
      },
    },
    {
      title: "T8 r = 6",
      text: "nums[6] = 4 를 더해 누적합이 18 입니다. 찾는 키 11 이 개수 맵에 없어 answer 는 3 그대로입니다. 키 18 을 개수 1 로 새로 넣습니다.",
      array: [3, 4, 7, 2, -3, 1, 4, 2],
      range: [0, 6],
      read: [6],
      write: [],
      calc: {
        expr: "seen.get(18 − 7)",
        result: "없음 → 0",
      },
      vars: "answer = 3",
      rangeSide: "누적합 18",
      pieces: [],
      map: {
        keyLabel: "seen 키",
        valueLabel: "개수",
        entries: [
          [0, 1],
          [3, 1],
          [7, 1],
          [14, 2],
          [16, 1],
          [13, 1],
          [18, 1],
        ],
        slots: 8,
        read: [],
        write: [18],
        note: "찾는 키 11 · 없음",
      },
    },
    {
      title: "T9 r = 7",
      text: "nums[7] = 2 를 더해 누적합이 20 입니다. 찾는 키 13 이 개수 맵에 1 번 있어 answer 가 4 가 됩니다. 키 20 을 개수 1 로 새로 넣습니다.",
      array: [3, 4, 7, 2, -3, 1, 4, 2],
      range: [0, 7],
      read: [7],
      write: [],
      calc: {
        expr: "seen.get(20 − 7)",
        result: "1",
      },
      vars: "answer = 4",
      rangeSide: "누적합 20",
      pieces: [
        {
          label: "찾은 구간",
          from: 5,
          to: 7,
          tone: "left",
          text: "[5,7]",
        },
      ],
      map: {
        keyLabel: "seen 키",
        valueLabel: "개수",
        entries: [
          [0, 1],
          [3, 1],
          [7, 1],
          [14, 2],
          [16, 1],
          [13, 1],
          [18, 1],
          [20, 1],
        ],
        slots: 8,
        read: [13],
        write: [20],
        note: "찾는 키 13 · 개수 1",
      },
    },
  ],
};
