import type {
  ArrayPlayerSpec,
  TablePlayerSpec,
} from "../../../_viz/player/StepPlayer";

/**
 * `deep.walk`(수행으로 알아보는 알고리즘) 절과 **같은 입력**을 쓴다 — `s = "abaab"`.
 * `palShort` 는 대각선을 까는 T1 과 구간 길이 2 의 T2~T5, `palLong` 은 길이 3 부터 5 까지의 T6~T11,
 * `cutFirst` 는 컷 DP 테이블을 까는 T12 와 끝 자리 1 ~ 3 의 T13~T17, `cutLast` 는 끝 자리 4 의 T18~T21 과
 * 답을 읽는 T22 다. 한 벌에 모으면 정적 필름이 스물두 장이라 DP 테이블마다, 그 안에서 다시 둘로 가른다.
 * `result` 는 판정 벌이 그 벌에서 정한 칸의 값, `cutFirst` 가 그때까지의 컷 칸, `cutLast` 가 반환값이다.
 *
 * `player: "stage"` 가 걸음 재생 패널(`src/_viz/player/StepPlayer.tsx`)을 고른다. 판정 DP 테이블 벌은
 * `stage: "table"`(2 차원 표 무대, `tableStage.ts`) — 줄 `i` · 열 `j` 이고 아래쪽 삼각형은 구간이
 * 아니라 `out`(이번 걸음 밖)이다. 걸음 하나가 판정 칸 하나이고, `read` 는 그 칸이 읽은 안쪽 칸, 표 아래
 * 문자열 줄(`strip`)에 걸린 `pieces` 가 칸이 맡는 구간과 그 안쪽이다. 컷 DP 테이블 벌은
 * `stage: "array"`(배열 무대, `arrayStage.ts`) — 문자열 위에 쥔 접두사 `[0,e]` 와 앞부분 · 마지막 조각
 * 괄호를 걸고, 아래 `layers` 에 판정 DP 테이블의 열 `e`(`pal[b][e]`)와 컷 DP 테이블(`cut`)을 쌓는다.
 * 걸음 하나가 시작 자리 `b` 하나다.
 *
 * `steps` 는 **인라인 배열 리터럴**이어야 한다(spread·변수 참조·함수 호출 금지).
 * 정적 계수가 실제보다 적게 세면 얇은 전개가 P3 을 그냥 지나간다. 리터럴은 그림 사이드카의
 * `simStepsFromRef()`(정본 실행에서 만든 걸음)를 글자 그대로 옮긴 것이고, 둘이 같은지는
 * `palindromePartitioningMinCut-guide.test.ts` 가 잰다.
 */

export const palShort = {
  player: "stage",
  stage: "table",
  rowHeads: ["i=0 · a", "i=1 · b", "i=2 · a", "i=3 · a", "i=4 · b"],
  colHeads: [0, 1, 2, 3, 4],
  colLabel: "j",
  strip: {
    label: "s",
    values: ["a", "b", "a", "a", "b"],
    side: 's = "abaab"',
  },
  title: 'palindromePartitioningMinCut("abaab")',
  result: "[F, F, T, F]",
  steps: [
    {
      title: "T1 대각선 pal[i][i] = T ②",
      text: "판정 DP 테이블을 5 × 5 로 만들고 거짓으로 채운 뒤 대각선 pal[0][0] … pal[4][4] 를 참으로 바꿉니다. 길이 1 구간은 글자 하나라 언제나 회문입니다.",
      table: [
        ["T", null, null, null, null],
        [null, "T", null, null, null],
        [null, null, "T", null, null],
        [null, null, null, "T", null],
        [null, null, null, null, "T"],
      ],
      write: [
        [0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
      ],
      out: [
        [1, 0],
        [2, 0],
        [2, 1],
        [3, 0],
        [3, 1],
        [3, 2],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
      ],
      rowSide: [
        "채움 1 / 5",
        "채움 1 / 4",
        "채움 1 / 3",
        "채움 1 / 2",
        "채움 1 / 1",
      ],
      calc: {
        expr: "pal[i][i] =",
        result: "T",
      },
      vars: "len = 1",
    },
    {
      title: 'T2 pal[0][1] "ab" = F',
      text: "구간 [0,1] \"ab\" 를 정합니다. 양 끝 s[0] = 'a' 와 s[1] = 'b' 가 다릅니다. 길이 2 라 안쪽이 빈 구간이고 안쪽 칸을 읽지 않습니다. pal[0][1] = F 를 적습니다.",
      table: [
        ["T", "F", null, null, null],
        [null, "T", null, null, null],
        [null, null, "T", null, null],
        [null, null, null, "T", null],
        [null, null, null, null, "T"],
      ],
      read: [],
      write: [[0, 1]],
      out: [
        [1, 0],
        [2, 0],
        [2, 1],
        [3, 0],
        [3, 1],
        [3, 2],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
      ],
      rowSide: [
        "채움 2 / 5",
        "채움 1 / 4",
        "채움 1 / 3",
        "채움 1 / 2",
        "채움 1 / 1",
      ],
      pieces: [
        {
          label: "구간",
          from: 0,
          to: 1,
          tone: "query",
          text: '"ab"',
          side: "pal[0][1]",
        },
      ],
      calc: {
        expr: "'a' ≠ 'b' →",
        result: "F",
      },
      vars: "len = 2",
    },
    {
      title: 'T3 pal[1][2] "ba" = F',
      text: "구간 [1,2] \"ba\" 를 정합니다. 양 끝 s[1] = 'b' 와 s[2] = 'a' 가 다릅니다. 길이 2 라 안쪽이 빈 구간이고 안쪽 칸을 읽지 않습니다. pal[1][2] = F 를 적습니다.",
      table: [
        ["T", "F", null, null, null],
        [null, "T", "F", null, null],
        [null, null, "T", null, null],
        [null, null, null, "T", null],
        [null, null, null, null, "T"],
      ],
      read: [],
      write: [[1, 2]],
      out: [
        [1, 0],
        [2, 0],
        [2, 1],
        [3, 0],
        [3, 1],
        [3, 2],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
      ],
      rowSide: [
        "채움 2 / 5",
        "채움 2 / 4",
        "채움 1 / 3",
        "채움 1 / 2",
        "채움 1 / 1",
      ],
      pieces: [
        {
          label: "구간",
          from: 1,
          to: 2,
          tone: "query",
          text: '"ba"',
          side: "pal[1][2]",
        },
      ],
      calc: {
        expr: "'b' ≠ 'a' →",
        result: "F",
      },
      vars: "len = 2",
    },
    {
      title: 'T4 pal[2][3] "aa" = T',
      text: "구간 [2,3] \"aa\" 를 정합니다. 양 끝 s[2] = 'a' 와 s[3] = 'a' 가 같습니다. 길이 2 라 안쪽이 빈 구간이고 안쪽 칸을 읽지 않습니다. pal[2][3] = T 를 적습니다.",
      table: [
        ["T", "F", null, null, null],
        [null, "T", "F", null, null],
        [null, null, "T", "T", null],
        [null, null, null, "T", null],
        [null, null, null, null, "T"],
      ],
      read: [],
      write: [[2, 3]],
      out: [
        [1, 0],
        [2, 0],
        [2, 1],
        [3, 0],
        [3, 1],
        [3, 2],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
      ],
      rowSide: [
        "채움 2 / 5",
        "채움 2 / 4",
        "채움 2 / 3",
        "채움 1 / 2",
        "채움 1 / 1",
      ],
      pieces: [
        {
          label: "구간",
          from: 2,
          to: 3,
          tone: "query",
          text: '"aa"',
          side: "pal[2][3]",
        },
      ],
      calc: {
        expr: "'a' = 'a' →",
        result: "T",
      },
      vars: "len = 2",
    },
    {
      title: 'T5 pal[3][4] "ab" = F',
      text: "구간 [3,4] \"ab\" 를 정합니다. 양 끝 s[3] = 'a' 와 s[4] = 'b' 가 다릅니다. 길이 2 라 안쪽이 빈 구간이고 안쪽 칸을 읽지 않습니다. pal[3][4] = F 를 적습니다.",
      table: [
        ["T", "F", null, null, null],
        [null, "T", "F", null, null],
        [null, null, "T", "T", null],
        [null, null, null, "T", "F"],
        [null, null, null, null, "T"],
      ],
      read: [],
      write: [[3, 4]],
      out: [
        [1, 0],
        [2, 0],
        [2, 1],
        [3, 0],
        [3, 1],
        [3, 2],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
      ],
      rowSide: [
        "채움 2 / 5",
        "채움 2 / 4",
        "채움 2 / 3",
        "채움 2 / 2",
        "채움 1 / 1",
      ],
      pieces: [
        {
          label: "구간",
          from: 3,
          to: 4,
          tone: "query",
          text: '"ab"',
          side: "pal[3][4]",
        },
      ],
      calc: {
        expr: "'a' ≠ 'b' →",
        result: "F",
      },
      vars: "len = 2",
    },
  ],
} satisfies TablePlayerSpec;

export const palLong = {
  player: "stage",
  stage: "table",
  rowHeads: ["i=0 · a", "i=1 · b", "i=2 · a", "i=3 · a", "i=4 · b"],
  colHeads: [0, 1, 2, 3, 4],
  colLabel: "j",
  strip: {
    label: "s",
    values: ["a", "b", "a", "a", "b"],
    side: 's = "abaab"',
  },
  title: 'palindromePartitioningMinCut("abaab")',
  result: "[T, F, F, F, T, F]",
  steps: [
    {
      title: 'T6 pal[0][2] "aba" = T',
      text: "구간 [0,2] \"aba\" 를 정합니다. 양 끝 s[0] = 'a' 와 s[2] = 'a' 가 같습니다. 안쪽 pal[1][1] \"b\" 는 T 입니다. pal[0][2] = T 를 적습니다.",
      table: [
        ["T", "F", "T", null, null],
        [null, "T", "F", null, null],
        [null, null, "T", "T", null],
        [null, null, null, "T", "F"],
        [null, null, null, null, "T"],
      ],
      read: [[1, 1]],
      write: [[0, 2]],
      out: [
        [1, 0],
        [2, 0],
        [2, 1],
        [3, 0],
        [3, 1],
        [3, 2],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
      ],
      rowSide: [
        "채움 3 / 5",
        "채움 2 / 4",
        "채움 2 / 3",
        "채움 2 / 2",
        "채움 1 / 1",
      ],
      pieces: [
        {
          label: "구간",
          from: 0,
          to: 2,
          tone: "query",
          text: '"aba"',
          side: "pal[0][2]",
        },
        {
          label: "안쪽",
          from: 1,
          to: 1,
          tone: "left",
          text: '"b"',
          side: "pal[1][1] = T",
        },
      ],
      calc: {
        expr: "'a' = 'a' 이고 pal[1][1] = T →",
        result: "T",
      },
      vars: "len = 3",
    },
    {
      title: 'T7 pal[1][3] "baa" = F',
      text: "구간 [1,3] \"baa\" 를 정합니다. 양 끝 s[1] = 'b' 와 s[3] = 'a' 가 다릅니다. 안쪽 pal[2][2] \"a\" 는 T 입니다. pal[1][3] = F 를 적습니다.",
      table: [
        ["T", "F", "T", null, null],
        [null, "T", "F", "F", null],
        [null, null, "T", "T", null],
        [null, null, null, "T", "F"],
        [null, null, null, null, "T"],
      ],
      read: [[2, 2]],
      write: [[1, 3]],
      out: [
        [1, 0],
        [2, 0],
        [2, 1],
        [3, 0],
        [3, 1],
        [3, 2],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
      ],
      rowSide: [
        "채움 3 / 5",
        "채움 3 / 4",
        "채움 2 / 3",
        "채움 2 / 2",
        "채움 1 / 1",
      ],
      pieces: [
        {
          label: "구간",
          from: 1,
          to: 3,
          tone: "query",
          text: '"baa"',
          side: "pal[1][3]",
        },
        {
          label: "안쪽",
          from: 2,
          to: 2,
          tone: "left",
          text: '"a"',
          side: "pal[2][2] = T",
        },
      ],
      calc: {
        expr: "'b' ≠ 'a' 이고 pal[2][2] = T →",
        result: "F",
      },
      vars: "len = 3",
    },
    {
      title: 'T8 pal[2][4] "aab" = F',
      text: "구간 [2,4] \"aab\" 를 정합니다. 양 끝 s[2] = 'a' 와 s[4] = 'b' 가 다릅니다. 안쪽 pal[3][3] \"a\" 는 T 입니다. pal[2][4] = F 를 적습니다.",
      table: [
        ["T", "F", "T", null, null],
        [null, "T", "F", "F", null],
        [null, null, "T", "T", "F"],
        [null, null, null, "T", "F"],
        [null, null, null, null, "T"],
      ],
      read: [[3, 3]],
      write: [[2, 4]],
      out: [
        [1, 0],
        [2, 0],
        [2, 1],
        [3, 0],
        [3, 1],
        [3, 2],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
      ],
      rowSide: [
        "채움 3 / 5",
        "채움 3 / 4",
        "채움 3 / 3",
        "채움 2 / 2",
        "채움 1 / 1",
      ],
      pieces: [
        {
          label: "구간",
          from: 2,
          to: 4,
          tone: "query",
          text: '"aab"',
          side: "pal[2][4]",
        },
        {
          label: "안쪽",
          from: 3,
          to: 3,
          tone: "left",
          text: '"a"',
          side: "pal[3][3] = T",
        },
      ],
      calc: {
        expr: "'a' ≠ 'b' 이고 pal[3][3] = T →",
        result: "F",
      },
      vars: "len = 3",
    },
    {
      title: 'T9 pal[0][3] "abaa" = F',
      text: "구간 [0,3] \"abaa\" 를 정합니다. 양 끝 s[0] = 'a' 와 s[3] = 'a' 가 같습니다. 안쪽 pal[1][2] \"ba\" 는 F 입니다. pal[0][3] = F 를 적습니다.",
      table: [
        ["T", "F", "T", "F", null],
        [null, "T", "F", "F", null],
        [null, null, "T", "T", "F"],
        [null, null, null, "T", "F"],
        [null, null, null, null, "T"],
      ],
      read: [[1, 2]],
      write: [[0, 3]],
      out: [
        [1, 0],
        [2, 0],
        [2, 1],
        [3, 0],
        [3, 1],
        [3, 2],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
      ],
      rowSide: [
        "채움 4 / 5",
        "채움 3 / 4",
        "채움 3 / 3",
        "채움 2 / 2",
        "채움 1 / 1",
      ],
      pieces: [
        {
          label: "구간",
          from: 0,
          to: 3,
          tone: "query",
          text: '"abaa"',
          side: "pal[0][3]",
        },
        {
          label: "안쪽",
          from: 1,
          to: 2,
          tone: "left",
          text: '"ba"',
          side: "pal[1][2] = F",
        },
      ],
      calc: {
        expr: "'a' = 'a' 이고 pal[1][2] = F →",
        result: "F",
      },
      vars: "len = 4",
    },
    {
      title: 'T10 pal[1][4] "baab" = T',
      text: "구간 [1,4] \"baab\" 를 정합니다. 양 끝 s[1] = 'b' 와 s[4] = 'b' 가 같습니다. 안쪽 pal[2][3] \"aa\" 는 T 입니다. pal[1][4] = T 를 적습니다.",
      table: [
        ["T", "F", "T", "F", null],
        [null, "T", "F", "F", "T"],
        [null, null, "T", "T", "F"],
        [null, null, null, "T", "F"],
        [null, null, null, null, "T"],
      ],
      read: [[2, 3]],
      write: [[1, 4]],
      out: [
        [1, 0],
        [2, 0],
        [2, 1],
        [3, 0],
        [3, 1],
        [3, 2],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
      ],
      rowSide: [
        "채움 4 / 5",
        "채움 4 / 4",
        "채움 3 / 3",
        "채움 2 / 2",
        "채움 1 / 1",
      ],
      pieces: [
        {
          label: "구간",
          from: 1,
          to: 4,
          tone: "query",
          text: '"baab"',
          side: "pal[1][4]",
        },
        {
          label: "안쪽",
          from: 2,
          to: 3,
          tone: "left",
          text: '"aa"',
          side: "pal[2][3] = T",
        },
      ],
      calc: {
        expr: "'b' = 'b' 이고 pal[2][3] = T →",
        result: "T",
      },
      vars: "len = 4",
    },
    {
      title: 'T11 pal[0][4] "abaab" = F',
      text: "구간 [0,4] \"abaab\" 를 정합니다. 양 끝 s[0] = 'a' 와 s[4] = 'b' 가 다릅니다. 안쪽 pal[1][3] \"baa\" 는 F 입니다. pal[0][4] = F 를 적습니다.",
      table: [
        ["T", "F", "T", "F", "F"],
        [null, "T", "F", "F", "T"],
        [null, null, "T", "T", "F"],
        [null, null, null, "T", "F"],
        [null, null, null, null, "T"],
      ],
      read: [[1, 3]],
      write: [[0, 4]],
      out: [
        [1, 0],
        [2, 0],
        [2, 1],
        [3, 0],
        [3, 1],
        [3, 2],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
      ],
      rowSide: [
        "채움 5 / 5",
        "채움 4 / 4",
        "채움 3 / 3",
        "채움 2 / 2",
        "채움 1 / 1",
      ],
      pieces: [
        {
          label: "구간",
          from: 0,
          to: 4,
          tone: "query",
          text: '"abaab"',
          side: "pal[0][4]",
        },
        {
          label: "안쪽",
          from: 1,
          to: 3,
          tone: "left",
          text: '"baa"',
          side: "pal[1][3] = F",
        },
      ],
      calc: {
        expr: "'a' ≠ 'b' 이고 pal[1][3] = F →",
        result: "F",
      },
      vars: "len = 5",
    },
  ],
} satisfies TablePlayerSpec;

export const cutFirst = {
  player: "stage",
  stage: "array",
  arrayName: "s",
  rangeLabel: "접두사",
  title: 'palindromePartitioningMinCut("abaab")',
  result: "[0, 1, 0, 1]",
  steps: [
    {
      title: "T12 cut[0] = 0",
      text: '판정 DP 테이블이 다 찼습니다. 컷 DP 테이블을 칸 5 개로 만들고 0 으로 채웁니다. cut[0] 은 글자 하나짜리 접두사 "a" 라 자를 자리가 없어, 깔아 둔 0 이 그대로 그 칸의 값입니다.',
      array: ["a", "b", "a", "a", "b"],
      range: [0, 0],
      layers: [
        {
          name: "pal[b][e]",
          values: ["T", "-", "-", "-", "-"],
          read: [],
          side: "e = 0 열",
        },
        {
          name: "cut",
          values: [0, null, null, null, null],
          read: [],
          write: [0],
        },
      ],
      calc: {
        expr: "cut[0] =",
        result: "0",
      },
      vars: null,
    },
    {
      title: "T13 e=1 · b=1 · cut[0] + 1 = 1 ④",
      text: '마지막 조각 "b" 의 pal[1][1] = T 라 후보입니다. 앞부분 "a" 의 cut[0] = 0 에 컷 하나를 더해 후보는 1 입니다. 1 < ∞ 이 참이라 ④ best 가 1 이 됩니다. 시작 자리를 다 봤으니 cut[1] = 1 을 적습니다.',
      array: ["a", "b", "a", "a", "b"],
      range: [0, 1],
      pieces: [
        {
          label: "앞부분",
          from: 0,
          to: 0,
          tone: "left",
          text: '"a"',
        },
        {
          label: "마지막 조각",
          from: 1,
          to: 1,
          tone: "right",
          text: '"b"',
        },
      ],
      layers: [
        {
          name: "pal[b][e]",
          values: ["F", "T", "-", "-", "-"],
          read: [1],
          side: "e = 1 열",
        },
        {
          name: "cut",
          values: [0, 1, null, null, null],
          read: [0],
          write: [1],
        },
      ],
      calc: {
        expr: "cut[0] + 1 = 0 + 1 =",
        result: "1",
      },
      vars: "best ∞ → 1",
    },
    {
      title: 'T14 e=2 · 접두사 "aba" 가 통째로 회문 ③',
      text: 'pal[0][2] = T 라 접두사 "aba" 가 통째로 회문입니다. ③ 후보를 하나도 세지 않고 cut[2] = 0 을 적습니다.',
      array: ["a", "b", "a", "a", "b"],
      range: [0, 2],
      pieces: [
        {
          label: "마지막 조각",
          from: 0,
          to: 2,
          tone: "right",
          text: '"aba"',
        },
      ],
      layers: [
        {
          name: "pal[b][e]",
          values: ["T", "F", "T", "-", "-"],
          read: [0],
          side: "e = 2 열",
        },
        {
          name: "cut",
          values: [0, 1, 0, null, null],
          read: [],
          write: [2],
        },
      ],
      calc: {
        expr: "pal[0][2] =",
        result: "T",
      },
      vars: null,
    },
    {
      title: 'T15 e=3 · b=1 · "baa" 는 회문이 아니다',
      text: 'pal[0][3] = F 라 후보를 셉니다. 마지막 조각 "baa" 의 pal[1][3] = F 라 후보가 아니고, best 는 ∞ 그대로입니다.',
      array: ["a", "b", "a", "a", "b"],
      range: [0, 3],
      pieces: [
        {
          label: "앞부분",
          from: 0,
          to: 0,
          tone: "left",
          text: '"a"',
        },
        {
          label: "마지막 조각",
          from: 1,
          to: 3,
          tone: "right",
          text: '"baa"',
        },
      ],
      layers: [
        {
          name: "pal[b][e]",
          values: ["F", "F", "T", "T", "-"],
          read: [1],
          side: "e = 3 열",
        },
        {
          name: "cut",
          values: [0, 1, 0, null, null],
          read: [],
          write: [],
        },
      ],
      calc: {
        expr: "pal[1][3] =",
        result: "F",
      },
      vars: "best ∞",
    },
    {
      title: "T16 e=3 · b=2 · cut[1] + 1 = 2 ④",
      text: '마지막 조각 "aa" 의 pal[2][3] = T 라 후보입니다. 앞부분 "ab" 의 cut[1] = 1 에 컷 하나를 더해 후보는 2 입니다. 2 < ∞ 이 참이라 ④ best 가 2 가 됩니다.',
      array: ["a", "b", "a", "a", "b"],
      range: [0, 3],
      pieces: [
        {
          label: "앞부분",
          from: 0,
          to: 1,
          tone: "left",
          text: '"ab"',
        },
        {
          label: "마지막 조각",
          from: 2,
          to: 3,
          tone: "right",
          text: '"aa"',
        },
      ],
      layers: [
        {
          name: "pal[b][e]",
          values: ["F", "F", "T", "T", "-"],
          read: [2],
          side: "e = 3 열",
        },
        {
          name: "cut",
          values: [0, 1, 0, null, null],
          read: [1],
          write: [],
        },
      ],
      calc: {
        expr: "cut[1] + 1 = 1 + 1 =",
        result: "2",
      },
      vars: "best ∞ → 2",
    },
    {
      title: "T17 e=3 · b=3 · cut[2] + 1 = 1 ④",
      text: '마지막 조각 "a" 의 pal[3][3] = T 라 후보입니다. 앞부분 "aba" 의 cut[2] = 0 에 컷 하나를 더해 후보는 1 입니다. 1 < 2 가 참이라 ④ best 가 1 이 됩니다. 시작 자리를 다 봤으니 cut[3] = 1 을 적습니다.',
      array: ["a", "b", "a", "a", "b"],
      range: [0, 3],
      pieces: [
        {
          label: "앞부분",
          from: 0,
          to: 2,
          tone: "left",
          text: '"aba"',
        },
        {
          label: "마지막 조각",
          from: 3,
          to: 3,
          tone: "right",
          text: '"a"',
        },
      ],
      layers: [
        {
          name: "pal[b][e]",
          values: ["F", "F", "T", "T", "-"],
          read: [3],
          side: "e = 3 열",
        },
        {
          name: "cut",
          values: [0, 1, 0, 1, null],
          read: [2],
          write: [3],
        },
      ],
      calc: {
        expr: "cut[2] + 1 = 0 + 1 =",
        result: "1",
      },
      vars: "best 2 → 1",
    },
  ],
} satisfies ArrayPlayerSpec;

export const cutLast = {
  player: "stage",
  stage: "array",
  arrayName: "s",
  rangeLabel: "접두사",
  title: 'palindromePartitioningMinCut("abaab")',
  result: "1",
  steps: [
    {
      title: "T18 e=4 · b=1 · cut[0] + 1 = 1 ④",
      text: '마지막 조각 "baab" 의 pal[1][4] = T 라 후보입니다. 앞부분 "a" 의 cut[0] = 0 에 컷 하나를 더해 후보는 1 입니다. 1 < ∞ 이 참이라 ④ best 가 1 이 됩니다.',
      array: ["a", "b", "a", "a", "b"],
      range: [0, 4],
      pieces: [
        {
          label: "앞부분",
          from: 0,
          to: 0,
          tone: "left",
          text: '"a"',
        },
        {
          label: "마지막 조각",
          from: 1,
          to: 4,
          tone: "right",
          text: '"baab"',
        },
      ],
      layers: [
        {
          name: "pal[b][e]",
          values: ["F", "T", "F", "F", "T"],
          read: [1],
          side: "e = 4 열",
        },
        {
          name: "cut",
          values: [0, 1, 0, 1, null],
          read: [0],
          write: [],
        },
      ],
      calc: {
        expr: "cut[0] + 1 = 0 + 1 =",
        result: "1",
      },
      vars: "best ∞ → 1",
    },
    {
      title: 'T19 e=4 · b=2 · "aab" 는 회문이 아니다',
      text: 'pal[0][4] = F 라 후보를 셉니다. 마지막 조각 "aab" 의 pal[2][4] = F 라 후보가 아니고, best 는 1 그대로입니다.',
      array: ["a", "b", "a", "a", "b"],
      range: [0, 4],
      pieces: [
        {
          label: "앞부분",
          from: 0,
          to: 1,
          tone: "left",
          text: '"ab"',
        },
        {
          label: "마지막 조각",
          from: 2,
          to: 4,
          tone: "right",
          text: '"aab"',
        },
      ],
      layers: [
        {
          name: "pal[b][e]",
          values: ["F", "T", "F", "F", "T"],
          read: [2],
          side: "e = 4 열",
        },
        {
          name: "cut",
          values: [0, 1, 0, 1, null],
          read: [],
          write: [],
        },
      ],
      calc: {
        expr: "pal[2][4] =",
        result: "F",
      },
      vars: "best 1",
    },
    {
      title: 'T20 e=4 · b=3 · "ab" 는 회문이 아니다',
      text: 'pal[0][4] = F 라 후보를 셉니다. 마지막 조각 "ab" 의 pal[3][4] = F 라 후보가 아니고, best 는 1 그대로입니다.',
      array: ["a", "b", "a", "a", "b"],
      range: [0, 4],
      pieces: [
        {
          label: "앞부분",
          from: 0,
          to: 2,
          tone: "left",
          text: '"aba"',
        },
        {
          label: "마지막 조각",
          from: 3,
          to: 4,
          tone: "right",
          text: '"ab"',
        },
      ],
      layers: [
        {
          name: "pal[b][e]",
          values: ["F", "T", "F", "F", "T"],
          read: [3],
          side: "e = 4 열",
        },
        {
          name: "cut",
          values: [0, 1, 0, 1, null],
          read: [],
          write: [],
        },
      ],
      calc: {
        expr: "pal[3][4] =",
        result: "F",
      },
      vars: "best 1",
    },
    {
      title: "T21 e=4 · b=4 · cut[3] + 1 = 2 ⑤",
      text: '마지막 조각 "b" 의 pal[4][4] = T 라 후보입니다. 앞부분 "abaa" 의 cut[3] = 1 에 컷 하나를 더해 후보는 2 입니다. 2 < 1 이 거짓이라 ⑤ best 는 1 그대로입니다. 시작 자리를 다 봤으니 cut[4] = 1 을 적습니다.',
      array: ["a", "b", "a", "a", "b"],
      range: [0, 4],
      pieces: [
        {
          label: "앞부분",
          from: 0,
          to: 3,
          tone: "left",
          text: '"abaa"',
        },
        {
          label: "마지막 조각",
          from: 4,
          to: 4,
          tone: "right",
          text: '"b"',
        },
      ],
      layers: [
        {
          name: "pal[b][e]",
          values: ["F", "T", "F", "F", "T"],
          read: [4],
          side: "e = 4 열",
        },
        {
          name: "cut",
          values: [0, 1, 0, 1, 1],
          read: [3],
          write: [4],
        },
      ],
      calc: {
        expr: "cut[3] + 1 = 1 + 1 =",
        result: "2",
      },
      vars: "best 1 → 1",
    },
    {
      title: "T22 cut[4] = 1 반환",
      text: '문자열 전체가 접두사 "abaab" 이고 그 칸이 cut[4] 입니다. 값 1 을 돌려줍니다.',
      array: ["a", "b", "a", "a", "b"],
      range: [0, 4],
      layers: [
        {
          name: "pal[b][e]",
          values: ["F", "T", "F", "F", "T"],
          read: [],
          side: "e = 4 열",
        },
        {
          name: "cut",
          values: [0, 1, 0, 1, 1],
          read: [4],
          write: [],
        },
      ],
      calc: {
        expr: "cut[4] =",
        result: "1",
      },
      vars: null,
    },
  ],
} satisfies ArrayPlayerSpec;
