import type { ArrayPlayerSpec } from "../../../_viz/player/StepPlayer";

/**
 * `deep.walk`(수행으로 알아보는 알고리즘) 절과 **같은 입력**을 쓴다 — 직선 여섯 개를 기울기 비감소 순서로
 * 넣고 `query(0)` · `query(-4)` · `query(4)` 를 답한다. 걸음 T1~T16 이 본문의 T1~T16 과 하나씩 짝이다.
 *
 * `player: "stage"` 가 걸음 재생 패널(`src/_viz/player/StepPlayer.tsx`)을 고르고, `stage: "array"` 가 배열
 * 무대(`arrayStage.ts`)를 고른다. 맨 위 줄은 등록할 직선을 입력 차례로 늘어놓은 것이고(쥔 구간은 지금까지
 * 읽은 직선, 버린 직선은 대시), 그 아래 `hull` 줄이 걸음 뒤의 아래 껍질을 담은 스택 띠(왼쪽이 바닥, 오른쪽이
 * 꼭대기), 맨 아래 줄이 질의 자리에서 아래 껍질의 값이다.
 *
 * `steps` 는 **인라인 배열 리터럴**이어야 한다(spread·변수 참조·함수 호출 금지). 리터럴은 그림 사이드카의
 * `simStepsFromRef()`(정본과 대조하는 걸음 기록에서 만든 걸음)를 글자 그대로 옮긴 것이고, 둘이 같은지는
 * `convexHullTrick-guide.test.ts` 가 잰다.
 */

export const hull = {
  player: "stage",
  stage: "array",
  arrayName: "등록",
  rangeLabel: "읽은 직선",
  title: "직선 여섯 개를 넣고 세 자리를 묻는다",
  result: "-3 · -8 · -8",
  steps: [
    {
      title: "T1 addLine(-2, 0) ④",
      text: "아래 껍질이 0 칸이라 판정 없이 ④ (-2, 0) 을 뒤에 붙입니다.",
      array: ["(-2, 0)", "(-1, 5)", "(0, -1)", "(0, -3)", "(2, 0)", "(2, 7)"],
      range: [0, 0],
      read: [0],
      write: [],
      out: [],
      layers: [
        {
          name: "hull",
          values: ["(-2, 0)", null, null],
          read: [],
          write: [0],
          side: "꼭대기 = (-2, 0)",
          span: 2,
        },
        {
          name: "x 에서의 값",
          values: [null, null, null],
          read: [],
          write: [],
          side: "질의 전",
          span: 2,
        },
      ],
      calc: {
        expr: "hull.length >= 2",
        result: "거짓 · 뒤에 붙인다",
      },
      vars: null,
      span: 2,
    },
    {
      title: "T2 addLine(-1, 5) ④",
      text: "아래 껍질이 1 칸이라 판정 없이 ④ (-1, 5) 를 뒤에 붙입니다.",
      array: ["(-2, 0)", "(-1, 5)", "(0, -1)", "(0, -3)", "(2, 0)", "(2, 7)"],
      range: [0, 1],
      read: [1],
      write: [],
      out: [],
      layers: [
        {
          name: "hull",
          values: ["(-2, 0)", "(-1, 5)", null],
          read: [],
          write: [1],
          side: "꼭대기 = (-1, 5)",
          span: 2,
        },
        {
          name: "x 에서의 값",
          values: [null, null, null],
          read: [],
          write: [],
          side: "질의 전",
          span: 2,
        },
      ],
      calc: {
        expr: "hull.length >= 2",
        result: "거짓 · 뒤에 붙인다",
      },
      vars: null,
      span: 2,
    },
    {
      title: "T3 addLine(0, -1) ③",
      text: "isCovered 의 두 곱이 6 >= -5 로 참이라 ③ 꼭대기 (-1, 5) 를 뺍니다. 새 꼭대기로 다시 판정합니다.",
      array: ["(-2, 0)", "(-1, 5)", "(0, -1)", "(0, -3)", "(2, 0)", "(2, 7)"],
      range: [0, 2],
      read: [2],
      write: [],
      out: [1],
      layers: [
        {
          name: "hull",
          values: ["(-2, 0)", null, null],
          read: [0],
          write: [],
          side: "꼭대기 = (-2, 0)",
          span: 2,
        },
        {
          name: "x 에서의 값",
          values: [null, null, null],
          read: [],
          write: [],
          side: "질의 전",
          span: 2,
        },
      ],
      calc: {
        expr: "isCovered: 6 >= -5",
        result: "참 · 꼭대기를 뺀다",
      },
      vars: null,
      span: 2,
    },
    {
      title: "T4 addLine(0, -1) ④",
      text: "아래 껍질이 1 칸이라 판정 없이 ④ (0, -1) 을 뒤에 붙입니다.",
      array: ["(-2, 0)", "(-1, 5)", "(0, -1)", "(0, -3)", "(2, 0)", "(2, 7)"],
      range: [0, 2],
      read: [2],
      write: [],
      out: [1],
      layers: [
        {
          name: "hull",
          values: ["(-2, 0)", "(0, -1)", null],
          read: [],
          write: [1],
          side: "꼭대기 = (0, -1)",
          span: 2,
        },
        {
          name: "x 에서의 값",
          values: [null, null, null],
          read: [],
          write: [],
          side: "질의 전",
          span: 2,
        },
      ],
      calc: {
        expr: "hull.length >= 2",
        result: "거짓 · 뒤에 붙인다",
      },
      vars: null,
      span: 2,
    },
    {
      title: "T5 addLine(0, -3) ②",
      text: "꼭대기 (0, -1) 과 기울기가 같고 -1 <= -3 이 거짓이라 ② 꼭대기를 뺍니다.",
      array: ["(-2, 0)", "(-1, 5)", "(0, -1)", "(0, -3)", "(2, 0)", "(2, 7)"],
      range: [0, 3],
      read: [3],
      write: [],
      out: [1, 2],
      layers: [
        {
          name: "hull",
          values: ["(-2, 0)", null, null],
          read: [],
          write: [],
          side: "꼭대기 = (-2, 0)",
          span: 2,
        },
        {
          name: "x 에서의 값",
          values: [null, null, null],
          read: [],
          write: [],
          side: "질의 전",
          span: 2,
        },
      ],
      calc: {
        expr: "-1 <= -3",
        result: "거짓 · 꼭대기를 뺀다",
      },
      vars: null,
      span: 2,
    },
    {
      title: "T6 addLine(0, -3) ④",
      text: "아래 껍질이 1 칸이라 판정 없이 ④ (0, -3) 을 뒤에 붙입니다.",
      array: ["(-2, 0)", "(-1, 5)", "(0, -1)", "(0, -3)", "(2, 0)", "(2, 7)"],
      range: [0, 3],
      read: [3],
      write: [],
      out: [1, 2],
      layers: [
        {
          name: "hull",
          values: ["(-2, 0)", "(0, -3)", null],
          read: [],
          write: [1],
          side: "꼭대기 = (0, -3)",
          span: 2,
        },
        {
          name: "x 에서의 값",
          values: [null, null, null],
          read: [],
          write: [],
          side: "질의 전",
          span: 2,
        },
      ],
      calc: {
        expr: "hull.length >= 2",
        result: "거짓 · 뒤에 붙인다",
      },
      vars: null,
      span: 2,
    },
    {
      title: "T7 addLine(2, 0) ④",
      text: "isCovered 의 두 곱이 -6 >= 6 로 거짓이라 아무것도 빼지 않고 ④ (2, 0) 을 뒤에 붙입니다.",
      array: ["(-2, 0)", "(-1, 5)", "(0, -1)", "(0, -3)", "(2, 0)", "(2, 7)"],
      range: [0, 4],
      read: [4],
      write: [],
      out: [1, 2],
      layers: [
        {
          name: "hull",
          values: ["(-2, 0)", "(0, -3)", "(2, 0)"],
          read: [0, 1],
          write: [2],
          side: "꼭대기 = (2, 0)",
          span: 2,
        },
        {
          name: "x 에서의 값",
          values: [null, null, null],
          read: [],
          write: [],
          side: "질의 전",
          span: 2,
        },
      ],
      calc: {
        expr: "isCovered: -6 >= 6",
        result: "거짓 · 뒤에 붙인다",
      },
      vars: null,
      span: 2,
    },
    {
      title: "T8 addLine(2, 7) ①",
      text: "꼭대기 (2, 0) 과 기울기가 같고 0 <= 7 이 참이라 ① 새 직선 (2, 7) 을 버립니다.",
      array: ["(-2, 0)", "(-1, 5)", "(0, -1)", "(0, -3)", "(2, 0)", "(2, 7)"],
      range: [0, 5],
      read: [5],
      write: [],
      out: [1, 2],
      layers: [
        {
          name: "hull",
          values: ["(-2, 0)", "(0, -3)", "(2, 0)"],
          read: [2],
          write: [],
          side: "꼭대기 = (2, 0)",
          span: 2,
        },
        {
          name: "x 에서의 값",
          values: [null, null, null],
          read: [],
          write: [],
          side: "질의 전",
          span: 2,
        },
      ],
      calc: {
        expr: "0 <= 7",
        result: "참 · 새 직선을 버린다",
      },
      vars: null,
      span: 2,
    },
    {
      title: "T9 query(0) ⑤",
      text: "후보 [0,2] 에서 mid = 1 입니다. -3 <= 0 이 참이라 ⑤ hi = 1 로 좁힙니다.",
      array: ["(-2, 0)", "(-1, 5)", "(0, -1)", "(0, -3)", "(2, 0)", "(2, 7)"],
      range: [0, 5],
      read: [],
      write: [],
      out: [1, 2, 5],
      layers: [
        {
          name: "hull",
          values: ["(-2, 0)", "(0, -3)", "(2, 0)"],
          read: [1, 2],
          write: [],
          side: "후보 [0,2] · mid = 1",
          span: 2,
        },
        {
          name: "x 에서의 값",
          values: [0, -3, 0],
          read: [1, 2],
          write: [],
          side: "x = 0",
          span: 2,
        },
      ],
      calc: {
        expr: "-3 <= 0",
        result: "참 · hi = 1",
      },
      vars: null,
      span: 2,
    },
    {
      title: "T10 query(0) ⑥",
      text: "후보 [0,1] 에서 mid = 0 입니다. 0 <= -3 이 거짓이라 ⑥ lo = 1 로 좁힙니다.",
      array: ["(-2, 0)", "(-1, 5)", "(0, -1)", "(0, -3)", "(2, 0)", "(2, 7)"],
      range: [0, 5],
      read: [],
      write: [],
      out: [1, 2, 5],
      layers: [
        {
          name: "hull",
          values: ["(-2, 0)", "(0, -3)", "(2, 0)"],
          read: [0, 1],
          write: [],
          side: "후보 [0,1] · mid = 0",
          span: 2,
        },
        {
          name: "x 에서의 값",
          values: [0, -3, 0],
          read: [0, 1],
          write: [],
          side: "x = 0",
          span: 2,
        },
      ],
      calc: {
        expr: "0 <= -3",
        result: "거짓 · lo = 1",
      },
      vars: null,
      span: 2,
    },
    {
      title: "T11 query(0) ⑦",
      text: "lo 와 hi 가 1 에서 만나 ⑦ hull[1] 의 값 -3 을 돌려줍니다.",
      array: ["(-2, 0)", "(-1, 5)", "(0, -1)", "(0, -3)", "(2, 0)", "(2, 7)"],
      range: [0, 5],
      read: [],
      write: [],
      out: [1, 2, 5],
      layers: [
        {
          name: "hull",
          values: ["(-2, 0)", "(0, -3)", "(2, 0)"],
          read: [1],
          write: [],
          side: "lo = hi = 1",
          span: 2,
        },
        {
          name: "x 에서의 값",
          values: [0, -3, 0],
          read: [1],
          write: [],
          side: "x = 0",
          span: 2,
        },
      ],
      calc: {
        expr: "1 < 1",
        result: "거짓 · 답 -3",
      },
      vars: null,
      span: 2,
    },
    {
      title: "T12 query(-4) ⑥",
      text: "후보 [0,2] 에서 mid = 1 입니다. -3 <= -8 이 거짓이라 ⑥ lo = 2 로 좁힙니다.",
      array: ["(-2, 0)", "(-1, 5)", "(0, -1)", "(0, -3)", "(2, 0)", "(2, 7)"],
      range: [0, 5],
      read: [],
      write: [],
      out: [1, 2, 5],
      layers: [
        {
          name: "hull",
          values: ["(-2, 0)", "(0, -3)", "(2, 0)"],
          read: [1, 2],
          write: [],
          side: "후보 [0,2] · mid = 1",
          span: 2,
        },
        {
          name: "x 에서의 값",
          values: [8, -3, -8],
          read: [1, 2],
          write: [],
          side: "x = -4",
          span: 2,
        },
      ],
      calc: {
        expr: "-3 <= -8",
        result: "거짓 · lo = 2",
      },
      vars: null,
      span: 2,
    },
    {
      title: "T13 query(-4) ⑦",
      text: "lo 와 hi 가 2 에서 만나 ⑦ hull[2] 의 값 -8 을 돌려줍니다.",
      array: ["(-2, 0)", "(-1, 5)", "(0, -1)", "(0, -3)", "(2, 0)", "(2, 7)"],
      range: [0, 5],
      read: [],
      write: [],
      out: [1, 2, 5],
      layers: [
        {
          name: "hull",
          values: ["(-2, 0)", "(0, -3)", "(2, 0)"],
          read: [2],
          write: [],
          side: "lo = hi = 2",
          span: 2,
        },
        {
          name: "x 에서의 값",
          values: [8, -3, -8],
          read: [2],
          write: [],
          side: "x = -4",
          span: 2,
        },
      ],
      calc: {
        expr: "2 < 2",
        result: "거짓 · 답 -8",
      },
      vars: null,
      span: 2,
    },
    {
      title: "T14 query(4) ⑤",
      text: "후보 [0,2] 에서 mid = 1 입니다. -3 <= 8 이 참이라 ⑤ hi = 1 로 좁힙니다.",
      array: ["(-2, 0)", "(-1, 5)", "(0, -1)", "(0, -3)", "(2, 0)", "(2, 7)"],
      range: [0, 5],
      read: [],
      write: [],
      out: [1, 2, 5],
      layers: [
        {
          name: "hull",
          values: ["(-2, 0)", "(0, -3)", "(2, 0)"],
          read: [1, 2],
          write: [],
          side: "후보 [0,2] · mid = 1",
          span: 2,
        },
        {
          name: "x 에서의 값",
          values: [-8, -3, 8],
          read: [1, 2],
          write: [],
          side: "x = 4",
          span: 2,
        },
      ],
      calc: {
        expr: "-3 <= 8",
        result: "참 · hi = 1",
      },
      vars: null,
      span: 2,
    },
    {
      title: "T15 query(4) ⑤",
      text: "후보 [0,1] 에서 mid = 0 입니다. -8 <= -3 이 참이라 ⑤ hi = 0 로 좁힙니다.",
      array: ["(-2, 0)", "(-1, 5)", "(0, -1)", "(0, -3)", "(2, 0)", "(2, 7)"],
      range: [0, 5],
      read: [],
      write: [],
      out: [1, 2, 5],
      layers: [
        {
          name: "hull",
          values: ["(-2, 0)", "(0, -3)", "(2, 0)"],
          read: [0, 1],
          write: [],
          side: "후보 [0,1] · mid = 0",
          span: 2,
        },
        {
          name: "x 에서의 값",
          values: [-8, -3, 8],
          read: [0, 1],
          write: [],
          side: "x = 4",
          span: 2,
        },
      ],
      calc: {
        expr: "-8 <= -3",
        result: "참 · hi = 0",
      },
      vars: null,
      span: 2,
    },
    {
      title: "T16 query(4) ⑦",
      text: "lo 와 hi 가 0 에서 만나 ⑦ hull[0] 의 값 -8 을 돌려줍니다.",
      array: ["(-2, 0)", "(-1, 5)", "(0, -1)", "(0, -3)", "(2, 0)", "(2, 7)"],
      range: [0, 5],
      read: [],
      write: [],
      out: [1, 2, 5],
      layers: [
        {
          name: "hull",
          values: ["(-2, 0)", "(0, -3)", "(2, 0)"],
          read: [0],
          write: [],
          side: "lo = hi = 0",
          span: 2,
        },
        {
          name: "x 에서의 값",
          values: [-8, -3, 8],
          read: [0],
          write: [],
          side: "x = 4",
          span: 2,
        },
      ],
      calc: {
        expr: "0 < 0",
        result: "거짓 · 답 -8",
      },
      vars: null,
      span: 2,
    },
  ],
} satisfies ArrayPlayerSpec;
