import type { ArrayPlayerSpec } from "../../../_viz/player/StepPlayer";

/**
 * `deep.walk`(수행으로 알아보는 알고리즘) 절과 **같은 입력**을 쓴다 — `a = 5, b = 33, m = 58`.
 * `walk` 는 조각 크기를 정하는 T1, 아기 걸음 표를 채우는 T2~T9, 보폭을 구하는 T10, 큰 걸음 T11~T12 다.
 *
 * `player: "stage"` 가 걸음 재생 패널(`src/_viz/player/StepPlayer.tsx`)을 고르고, `stage: "array"` 가
 * 배열 무대(`arrayStage.ts`)를 고른다. 배열 줄은 큰 걸음이 만든 값 `a^(i·n)`(칸 번호가 큰 걸음 번호 `i`,
 * 아직 안 만든 칸은 `null`)이고, 쥔 구간은 지난 큰 걸음이다. 맨 아래 `map` 이 아기 걸음 표 — 키는
 * `b·a^j`, 값은 `j` 다. 누적 곱셈 수는 무대에 자리가 없어 남는 변수(`vars`)에 둔다(SPEC §13).
 *
 * `steps` 는 **인라인 배열 리터럴**이어야 한다(spread·변수 참조·함수 호출 금지).
 * 리터럴은 그림 사이드카의 `simStepsFromRef()`(정본 실행에서 만든 걸음)를 글자 그대로 옮긴 것이고,
 * 둘이 같은지는 `babyStepGiantStep-guide.test.ts` 가 잰다.
 */

export const walk = {
  player: "stage",
  stage: "array",
  arrayName: "a^(i·n)",
  rangeLabel: "지난 큰 걸음",
  title: "babyStepGiantStep(5n, 33n, 58n)",
  result: "9",
  steps: [
    {
      title: "T1 n = 8",
      text: "a = 5, b = 33 이고 b 가 1 이 아니라 아기 걸음 표를 만듭니다. 조각 크기는 n = ⌈√58⌉ = 8 입니다.",
      array: [null, null, null, null, null, null, null, null, null],
      range: null,
      read: [],
      write: [],
      pointers: {},
      map: {
        keyLabel: "b·a^j",
        valueLabel: "j",
        entries: [],
        slots: 8,
        read: [],
        write: [],
      },
      calc: {
        expr: "⌈√58⌉",
        result: "8",
      },
      vars: "n = 8 · 곱셈 0 번",
    },
    {
      title: "T2 j = 0 · 33",
      text: "b·a^0 = 33 을 아기 걸음 표에 적습니다. 값 33 의 j 는 0 입니다.",
      array: [null, null, null, null, null, null, null, null, null],
      range: null,
      read: [],
      write: [],
      pointers: {},
      map: {
        keyLabel: "b·a^j",
        valueLabel: "j",
        entries: [[33, 0]],
        slots: 8,
        read: [],
        write: [33],
      },
      calc: {
        expr: "b mod 58",
        result: "33",
      },
      vars: "n = 8 · 곱셈 1 번",
    },
    {
      title: "T3 j = 1 · 49",
      text: "b·a^1 = 49 를 아기 걸음 표에 적습니다. 값 49 의 j 는 1 입니다.",
      array: [null, null, null, null, null, null, null, null, null],
      range: null,
      read: [],
      write: [],
      pointers: {},
      map: {
        keyLabel: "b·a^j",
        valueLabel: "j",
        entries: [
          [33, 0],
          [49, 1],
        ],
        slots: 8,
        read: [],
        write: [49],
      },
      calc: {
        expr: "33 · 5 mod 58",
        result: "49",
      },
      vars: "n = 8 · 곱셈 2 번",
    },
    {
      title: "T4 j = 2 · 13",
      text: "b·a^2 = 13 을 아기 걸음 표에 적습니다. 값 13 의 j 는 2 입니다.",
      array: [null, null, null, null, null, null, null, null, null],
      range: null,
      read: [],
      write: [],
      pointers: {},
      map: {
        keyLabel: "b·a^j",
        valueLabel: "j",
        entries: [
          [33, 0],
          [49, 1],
          [13, 2],
        ],
        slots: 8,
        read: [],
        write: [13],
      },
      calc: {
        expr: "49 · 5 mod 58",
        result: "13",
      },
      vars: "n = 8 · 곱셈 3 번",
    },
    {
      title: "T5 j = 3 · 7",
      text: "b·a^3 = 7 을 아기 걸음 표에 적습니다. 값 7 의 j 는 3 입니다.",
      array: [null, null, null, null, null, null, null, null, null],
      range: null,
      read: [],
      write: [],
      pointers: {},
      map: {
        keyLabel: "b·a^j",
        valueLabel: "j",
        entries: [
          [33, 0],
          [49, 1],
          [13, 2],
          [7, 3],
        ],
        slots: 8,
        read: [],
        write: [7],
      },
      calc: {
        expr: "13 · 5 mod 58",
        result: "7",
      },
      vars: "n = 8 · 곱셈 4 번",
    },
    {
      title: "T6 j = 4 · 35",
      text: "b·a^4 = 35 를 아기 걸음 표에 적습니다. 값 35 의 j 는 4 입니다.",
      array: [null, null, null, null, null, null, null, null, null],
      range: null,
      read: [],
      write: [],
      pointers: {},
      map: {
        keyLabel: "b·a^j",
        valueLabel: "j",
        entries: [
          [33, 0],
          [49, 1],
          [13, 2],
          [7, 3],
          [35, 4],
        ],
        slots: 8,
        read: [],
        write: [35],
      },
      calc: {
        expr: "7 · 5 mod 58",
        result: "35",
      },
      vars: "n = 8 · 곱셈 5 번",
    },
    {
      title: "T7 j = 5 · 1",
      text: "b·a^5 = 1 을 아기 걸음 표에 적습니다. 값 1 의 j 는 5 입니다.",
      array: [null, null, null, null, null, null, null, null, null],
      range: null,
      read: [],
      write: [],
      pointers: {},
      map: {
        keyLabel: "b·a^j",
        valueLabel: "j",
        entries: [
          [33, 0],
          [49, 1],
          [13, 2],
          [7, 3],
          [35, 4],
          [1, 5],
        ],
        slots: 8,
        read: [],
        write: [1],
      },
      calc: {
        expr: "35 · 5 mod 58",
        result: "1",
      },
      vars: "n = 8 · 곱셈 6 번",
    },
    {
      title: "T8 j = 6 · 5",
      text: "b·a^6 = 5 를 아기 걸음 표에 적습니다. 값 5 의 j 는 6 입니다.",
      array: [null, null, null, null, null, null, null, null, null],
      range: null,
      read: [],
      write: [],
      pointers: {},
      map: {
        keyLabel: "b·a^j",
        valueLabel: "j",
        entries: [
          [33, 0],
          [49, 1],
          [13, 2],
          [7, 3],
          [35, 4],
          [1, 5],
          [5, 6],
        ],
        slots: 8,
        read: [],
        write: [5],
      },
      calc: {
        expr: "1 · 5 mod 58",
        result: "5",
      },
      vars: "n = 8 · 곱셈 7 번",
    },
    {
      title: "T9 j = 7 · 25",
      text: "b·a^7 = 25 를 아기 걸음 표에 적습니다. 값 25 의 j 는 7 입니다.",
      array: [null, null, null, null, null, null, null, null, null],
      range: null,
      read: [],
      write: [],
      pointers: {},
      map: {
        keyLabel: "b·a^j",
        valueLabel: "j",
        entries: [
          [33, 0],
          [49, 1],
          [13, 2],
          [7, 3],
          [35, 4],
          [1, 5],
          [5, 6],
          [25, 7],
        ],
        slots: 8,
        read: [],
        write: [25],
      },
      calc: {
        expr: "5 · 5 mod 58",
        result: "25",
      },
      vars: "n = 8 · 곱셈 8 번",
    },
    {
      title: "T10 stride = 53",
      text: "보폭 stride = 5^8 mod 58 = 53 을 반복 제곱으로 구합니다(곱셈 5 번). 큰 걸음은 a^0 = 1 에서 출발합니다.",
      array: [1, null, null, null, null, null, null, null, null],
      range: [0, 0],
      read: [],
      write: [0],
      pointers: {
        i: 0,
      },
      map: {
        keyLabel: "b·a^j",
        valueLabel: "j",
        entries: [
          [33, 0],
          [49, 1],
          [13, 2],
          [7, 3],
          [35, 4],
          [1, 5],
          [5, 6],
          [25, 7],
        ],
        slots: 8,
        read: [],
        write: [],
      },
      calc: {
        expr: "5^8 mod 58",
        result: "53",
      },
      vars: "n = 8 · 곱셈 13 번",
    },
    {
      title: "T11 i = 1 · 53 ②",
      text: "giant = 53 이 아기 걸음 표에 없습니다. ② i 를 하나 늘립니다.",
      array: [1, 53, null, null, null, null, null, null, null],
      range: [0, 1],
      read: [],
      write: [1],
      pointers: {
        i: 1,
      },
      map: {
        keyLabel: "b·a^j",
        valueLabel: "j",
        entries: [
          [33, 0],
          [49, 1],
          [13, 2],
          [7, 3],
          [35, 4],
          [1, 5],
          [5, 6],
          [25, 7],
        ],
        slots: 8,
        read: [],
        write: [],
        note: "찾는 값 53 · 없음",
      },
      calc: {
        expr: "1 · 53 mod 58",
        result: "53",
      },
      vars: "n = 8 · 곱셈 14 번",
    },
    {
      title: "T12 i = 2 · 25 ①",
      text: "giant = 25 가 아기 걸음 표에 j = 7 로 있습니다. ① x = 2·8 − 7 = 9 를 돌려줍니다.",
      array: [1, 53, 25, null, null, null, null, null, null],
      range: [0, 2],
      read: [],
      write: [2],
      pointers: {
        i: 2,
      },
      map: {
        keyLabel: "b·a^j",
        valueLabel: "j",
        entries: [
          [33, 0],
          [49, 1],
          [13, 2],
          [7, 3],
          [35, 4],
          [1, 5],
          [5, 6],
          [25, 7],
        ],
        slots: 8,
        read: [25],
        write: [],
        note: "찾는 값 25 · j = 7",
      },
      calc: {
        expr: "53 · 53 mod 58",
        result: "25",
      },
      vars: "x = 9 · 곱셈 15 번",
    },
  ],
} satisfies ArrayPlayerSpec;
