import type { ArrayPlayerSpec } from "../../../_viz/player/StepPlayer";

/**
 * `deep.walk`(수행으로 알아보는 알고리즘) 절과 **같은 입력**을 쓴다 — `s = "ababbaa"`. 걸음은 T1~T17
 * 전부다 — 자리 넓히기 · 넓힌 문자열의 자리 15 개를 차례로 한 걸음씩 · 답 잘라 내기.
 *
 * `player: "stage"` 가 걸음 재생 패널(`src/_viz/player/StepPlayer.tsx`)을 고르고, `stage: "array"` 가 배열
 * 무대(`arrayStage.ts`)를 고른다. 값 줄은 넓힌 문자열 `t` 이고, `layers` 가 반지름 배열 `p` 한 줄이다 — 둘 다
 * 칸 번호가 `t` 의 자리다. 쥔 구간은 그 자리에 들어올 때 기억해 둔 가장 오른쪽 회문 `[c − p[c], r]` 이고,
 * `pieces` 는 이번 자리의 회문과 대칭 자리의 회문이다. 읽은 칸은 맞대 본 글자와 대칭 자리의 반지름이다.
 *
 * `steps` 는 **인라인 배열 리터럴**이어야 한다(spread·변수 참조·함수 호출 금지).
 * 정적 계수가 실제보다 적게 세면 얇은 전개가 P3 을 그냥 지나간다. 리터럴은 그림 사이드카의
 * `simStepsFromRef()`(정본 실행에서 만든 걸음)를 글자 그대로 옮긴 것이고, 둘이 같은지는
 * `longestPalindrome-guide.test.ts` 가 잰다.
 */

export const palindromeWalk = {
  player: "stage",
  stage: "array",
  arrayName: "t",
  rangeLabel: "가장 오른쪽 회문",
  title: 'longestPalindrome("ababbaa")',
  result: '"abba"',
  steps: [
    {
      title: "T1 자리를 넓힌다",
      text: "글자 7 개 사이와 양 끝에 구분자를 끼웁니다. 넓힌 문자열은 t = #a#b#a#b#b#a#a# 이고 자리가 15 개입니다. c 와 r 은 0 에서 시작합니다.",
      array: [
        "#",
        "a",
        "#",
        "b",
        "#",
        "a",
        "#",
        "b",
        "#",
        "b",
        "#",
        "a",
        "#",
        "a",
        "#",
      ],
      range: [0, 0],
      rangeSide: "c = 0 · r = 0",
      read: [],
      write: [],
      layers: [
        {
          name: "p",
          values: [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [],
        },
      ],
      calc: {
        expr: "m = 2n + 1",
        result: "15",
      },
      vars: "글자 비교 누적 0 번",
    },
    {
      title: "T2 자리 0 — 구간 밖 · 반지름 0",
      text: "i = 0 이 r = 0 보다 작지 않아 구간 밖입니다. 0 에서 시작합니다. 왼쪽이 문자열 밖이라 멈춥니다. p[0] = 0 을 적습니다.",
      array: [
        "#",
        "a",
        "#",
        "b",
        "#",
        "a",
        "#",
        "b",
        "#",
        "b",
        "#",
        "a",
        "#",
        "a",
        "#",
      ],
      range: [0, 0],
      rangeSide: "c = 0 · r = 0",
      read: [],
      write: [],
      pointers: {
        i: 0,
      },
      layers: [
        {
          name: "p",
          values: [
            0,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [0],
        },
      ],
      calc: {
        expr: "i = 0 ≥ r = 0",
        result: "0 에서 시작",
      },
      vars: "글자 비교 누적 0 번 · best = 0",
    },
    {
      title: "T3 자리 1 — 구간 밖 · 넓혀서 반지름 1",
      text: "i = 1 이 r = 0 보다 작지 않아 구간 밖입니다. 0 에서 시작합니다. 글자가 같은 쌍 1 개로 반지름이 1 이 됩니다. 왼쪽이 문자열 밖이라 멈춥니다. p[1] = 1 을 적습니다. i + p[i] = 2 가 r 보다 커서 c = 1, r = 2 로 옮깁니다. 가장 긴 자리가 1 로 바뀝니다.",
      array: [
        "#",
        "a",
        "#",
        "b",
        "#",
        "a",
        "#",
        "b",
        "#",
        "b",
        "#",
        "a",
        "#",
        "a",
        "#",
      ],
      range: [0, 0],
      rangeSide: "c = 0 · r = 0",
      read: [0, 2],
      write: [],
      pointers: {
        i: 1,
      },
      pieces: [
        {
          label: "자리 1",
          from: 0,
          to: 2,
          tone: "left",
          text: "p[1] = 1",
        },
      ],
      layers: [
        {
          name: "p",
          values: [
            0,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [1],
        },
      ],
      calc: {
        expr: "i = 1 ≥ r = 0",
        result: "0 에서 시작",
      },
      vars: "글자 비교 누적 1 번 · best = 1",
    },
    {
      title: "T4 자리 2 — 구간 밖 · 반지름 0",
      text: "i = 2 가 r = 2 보다 작지 않아 구간 밖입니다. 0 에서 시작합니다. t[1] = a 와 t[3] = b 가 달라 멈춥니다. p[2] = 0 을 적습니다.",
      array: [
        "#",
        "a",
        "#",
        "b",
        "#",
        "a",
        "#",
        "b",
        "#",
        "b",
        "#",
        "a",
        "#",
        "a",
        "#",
      ],
      range: [0, 2],
      rangeSide: "c = 1 · r = 2",
      read: [1, 3],
      write: [],
      pointers: {
        i: 2,
      },
      layers: [
        {
          name: "p",
          values: [
            0,
            1,
            0,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [2],
        },
      ],
      calc: {
        expr: "i = 2 ≥ r = 2",
        result: "0 에서 시작",
      },
      vars: "글자 비교 누적 2 번 · best = 1",
    },
    {
      title: "T5 자리 3 — 구간 밖 · 넓혀서 반지름 3",
      text: "i = 3 이 r = 2 보다 작지 않아 구간 밖입니다. 0 에서 시작합니다. 글자가 같은 쌍 3 개로 반지름이 3 이 됩니다. 왼쪽이 문자열 밖이라 멈춥니다. p[3] = 3 을 적습니다. i + p[i] = 6 이 r 보다 커서 c = 3, r = 6 으로 옮깁니다. 가장 긴 자리가 3 으로 바뀝니다.",
      array: [
        "#",
        "a",
        "#",
        "b",
        "#",
        "a",
        "#",
        "b",
        "#",
        "b",
        "#",
        "a",
        "#",
        "a",
        "#",
      ],
      range: [0, 2],
      rangeSide: "c = 1 · r = 2",
      read: [0, 1, 2, 4, 5, 6],
      write: [],
      pointers: {
        i: 3,
      },
      pieces: [
        {
          label: "자리 3",
          from: 0,
          to: 6,
          tone: "left",
          text: "p[3] = 3",
        },
      ],
      layers: [
        {
          name: "p",
          values: [
            0,
            1,
            0,
            3,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [3],
        },
      ],
      calc: {
        expr: "i = 3 ≥ r = 2",
        result: "0 에서 시작",
      },
      vars: "글자 비교 누적 5 번 · best = 3",
    },
    {
      title: "T6 자리 4 — 대칭 값 그대로 · 반지름 0",
      text: "i = 4 가 r = 6 보다 작아 구간 안입니다. 대칭 자리 2 × 3 − 4 = 2 의 반지름 0 과 남은 칸 2 중 작은 0 을 이어받습니다. t[3] = b 와 t[5] = a 가 달라 멈춥니다. p[4] = 0 을 적습니다.",
      array: [
        "#",
        "a",
        "#",
        "b",
        "#",
        "a",
        "#",
        "b",
        "#",
        "b",
        "#",
        "a",
        "#",
        "a",
        "#",
      ],
      range: [0, 6],
      rangeSide: "c = 3 · r = 6",
      read: [3, 5],
      write: [],
      pointers: {
        "2c−i": 2,
        c: 3,
        i: 4,
      },
      layers: [
        {
          name: "p",
          values: [
            0,
            1,
            0,
            3,
            0,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [2],
          write: [4],
        },
      ],
      calc: {
        expr: "min(r − i, p[2c − i]) = min(2, 0)",
        result: "0",
      },
      vars: "글자 비교 누적 6 번 · best = 3",
    },
    {
      title: "T7 자리 5 — 오른쪽 끝과 같음 · 넓혀서 반지름 3",
      text: "i = 5 가 r = 6 보다 작아 구간 안입니다. 대칭 자리 2 × 3 − 5 = 1 의 반지름 1 과 남은 칸 1 중 작은 1 을 이어받습니다. 글자가 같은 쌍 2 개로 반지름이 3 이 됩니다. t[1] = a 와 t[9] = b 가 달라 멈춥니다. p[5] = 3 을 적습니다. i + p[i] = 8 이 r 보다 커서 c = 5, r = 8 로 옮깁니다.",
      array: [
        "#",
        "a",
        "#",
        "b",
        "#",
        "a",
        "#",
        "b",
        "#",
        "b",
        "#",
        "a",
        "#",
        "a",
        "#",
      ],
      range: [0, 6],
      rangeSide: "c = 3 · r = 6",
      read: [1, 2, 3, 7, 8, 9],
      write: [],
      pointers: {
        "2c−i": 1,
        c: 3,
        i: 5,
      },
      pieces: [
        {
          label: "자리 5",
          from: 2,
          to: 8,
          tone: "left",
          text: "p[5] = 3",
        },
        {
          label: "대칭 1",
          from: 0,
          to: 2,
          tone: "right",
          text: "p[1] = 1",
        },
      ],
      layers: [
        {
          name: "p",
          values: [
            0,
            1,
            0,
            3,
            0,
            3,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [1],
          write: [5],
        },
      ],
      calc: {
        expr: "min(r − i, p[2c − i]) = min(1, 1)",
        result: "1",
      },
      vars: "글자 비교 누적 9 번 · best = 3",
    },
    {
      title: "T8 자리 6 — 대칭 값 그대로 · 반지름 0",
      text: "i = 6 이 r = 8 보다 작아 구간 안입니다. 대칭 자리 2 × 5 − 6 = 4 의 반지름 0 과 남은 칸 2 중 작은 0 을 이어받습니다. t[5] = a 와 t[7] = b 가 달라 멈춥니다. p[6] = 0 을 적습니다.",
      array: [
        "#",
        "a",
        "#",
        "b",
        "#",
        "a",
        "#",
        "b",
        "#",
        "b",
        "#",
        "a",
        "#",
        "a",
        "#",
      ],
      range: [2, 8],
      rangeSide: "c = 5 · r = 8",
      read: [5, 7],
      write: [],
      pointers: {
        "2c−i": 4,
        c: 5,
        i: 6,
      },
      layers: [
        {
          name: "p",
          values: [
            0,
            1,
            0,
            3,
            0,
            3,
            0,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [4],
          write: [6],
        },
      ],
      calc: {
        expr: "min(r − i, p[2c − i]) = min(2, 0)",
        result: "0",
      },
      vars: "글자 비교 누적 10 번 · best = 3",
    },
    {
      title: "T9 자리 7 — 오른쪽 끝에 잘림 · 반지름 1",
      text: "i = 7 이 r = 8 보다 작아 구간 안입니다. 대칭 자리 2 × 5 − 7 = 3 의 반지름 3 과 남은 칸 1 중 작은 1 을 이어받습니다. t[5] = a 와 t[9] = b 가 달라 멈춥니다. p[7] = 1 을 적습니다.",
      array: [
        "#",
        "a",
        "#",
        "b",
        "#",
        "a",
        "#",
        "b",
        "#",
        "b",
        "#",
        "a",
        "#",
        "a",
        "#",
      ],
      range: [2, 8],
      rangeSide: "c = 5 · r = 8",
      read: [5, 9],
      write: [],
      pointers: {
        "2c−i": 3,
        c: 5,
        i: 7,
      },
      pieces: [
        {
          label: "자리 7",
          from: 6,
          to: 8,
          tone: "left",
          text: "p[7] = 1",
        },
        {
          label: "대칭 3",
          from: 0,
          to: 6,
          tone: "right",
          text: "p[3] = 3",
        },
      ],
      layers: [
        {
          name: "p",
          values: [
            0,
            1,
            0,
            3,
            0,
            3,
            0,
            1,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [3],
          write: [7],
        },
      ],
      calc: {
        expr: "min(r − i, p[2c − i]) = min(1, 3)",
        result: "1",
      },
      vars: "글자 비교 누적 11 번 · best = 3",
    },
    {
      title: "T10 자리 8 — 구간 밖 · 넓혀서 반지름 4",
      text: "i = 8 이 r = 8 보다 작지 않아 구간 밖입니다. 0 에서 시작합니다. 글자가 같은 쌍 4 개로 반지름이 4 가 됩니다. t[3] = b 와 t[13] = a 가 달라 멈춥니다. p[8] = 4 를 적습니다. i + p[i] = 12 가 r 보다 커서 c = 8, r = 12 로 옮깁니다. 가장 긴 자리가 8 로 바뀝니다.",
      array: [
        "#",
        "a",
        "#",
        "b",
        "#",
        "a",
        "#",
        "b",
        "#",
        "b",
        "#",
        "a",
        "#",
        "a",
        "#",
      ],
      range: [2, 8],
      rangeSide: "c = 5 · r = 8",
      read: [3, 4, 5, 6, 7, 9, 10, 11, 12, 13],
      write: [],
      pointers: {
        i: 8,
      },
      pieces: [
        {
          label: "자리 8",
          from: 4,
          to: 12,
          tone: "left",
          text: "p[8] = 4",
        },
      ],
      layers: [
        {
          name: "p",
          values: [
            0,
            1,
            0,
            3,
            0,
            3,
            0,
            1,
            4,
            null,
            null,
            null,
            null,
            null,
            null,
          ],
          read: [],
          write: [8],
        },
      ],
      calc: {
        expr: "i = 8 ≥ r = 8",
        result: "0 에서 시작",
      },
      vars: "글자 비교 누적 16 번 · best = 8",
    },
    {
      title: "T11 자리 9 — 대칭 값 그대로 · 반지름 1",
      text: "i = 9 가 r = 12 보다 작아 구간 안입니다. 대칭 자리 2 × 8 − 9 = 7 의 반지름 1 과 남은 칸 3 중 작은 1 을 이어받습니다. t[7] = b 와 t[11] = a 가 달라 멈춥니다. p[9] = 1 을 적습니다.",
      array: [
        "#",
        "a",
        "#",
        "b",
        "#",
        "a",
        "#",
        "b",
        "#",
        "b",
        "#",
        "a",
        "#",
        "a",
        "#",
      ],
      range: [4, 12],
      rangeSide: "c = 8 · r = 12",
      read: [7, 11],
      write: [],
      pointers: {
        "2c−i": 7,
        c: 8,
        i: 9,
      },
      pieces: [
        {
          label: "자리 9",
          from: 8,
          to: 10,
          tone: "left",
          text: "p[9] = 1",
        },
        {
          label: "대칭 7",
          from: 6,
          to: 8,
          tone: "right",
          text: "p[7] = 1",
        },
      ],
      layers: [
        {
          name: "p",
          values: [0, 1, 0, 3, 0, 3, 0, 1, 4, 1, null, null, null, null, null],
          read: [7],
          write: [9],
        },
      ],
      calc: {
        expr: "min(r − i, p[2c − i]) = min(3, 1)",
        result: "1",
      },
      vars: "글자 비교 누적 17 번 · best = 8",
    },
    {
      title: "T12 자리 10 — 대칭 값 그대로 · 반지름 0",
      text: "i = 10 이 r = 12 보다 작아 구간 안입니다. 대칭 자리 2 × 8 − 10 = 6 의 반지름 0 과 남은 칸 2 중 작은 0 을 이어받습니다. t[9] = b 와 t[11] = a 가 달라 멈춥니다. p[10] = 0 을 적습니다.",
      array: [
        "#",
        "a",
        "#",
        "b",
        "#",
        "a",
        "#",
        "b",
        "#",
        "b",
        "#",
        "a",
        "#",
        "a",
        "#",
      ],
      range: [4, 12],
      rangeSide: "c = 8 · r = 12",
      read: [9, 11],
      write: [],
      pointers: {
        "2c−i": 6,
        c: 8,
        i: 10,
      },
      layers: [
        {
          name: "p",
          values: [0, 1, 0, 3, 0, 3, 0, 1, 4, 1, 0, null, null, null, null],
          read: [6],
          write: [10],
        },
      ],
      calc: {
        expr: "min(r − i, p[2c − i]) = min(2, 0)",
        result: "0",
      },
      vars: "글자 비교 누적 18 번 · best = 8",
    },
    {
      title: "T13 자리 11 — 오른쪽 끝에 잘림 · 반지름 1",
      text: "i = 11 이 r = 12 보다 작아 구간 안입니다. 대칭 자리 2 × 8 − 11 = 5 의 반지름 3 과 남은 칸 1 중 작은 1 을 이어받습니다. t[9] = b 와 t[13] = a 가 달라 멈춥니다. p[11] = 1 을 적습니다.",
      array: [
        "#",
        "a",
        "#",
        "b",
        "#",
        "a",
        "#",
        "b",
        "#",
        "b",
        "#",
        "a",
        "#",
        "a",
        "#",
      ],
      range: [4, 12],
      rangeSide: "c = 8 · r = 12",
      read: [9, 13],
      write: [],
      pointers: {
        "2c−i": 5,
        c: 8,
        i: 11,
      },
      pieces: [
        {
          label: "자리 11",
          from: 10,
          to: 12,
          tone: "left",
          text: "p[11] = 1",
        },
        {
          label: "대칭 5",
          from: 2,
          to: 8,
          tone: "right",
          text: "p[5] = 3",
        },
      ],
      layers: [
        {
          name: "p",
          values: [0, 1, 0, 3, 0, 3, 0, 1, 4, 1, 0, 1, null, null, null],
          read: [5],
          write: [11],
        },
      ],
      calc: {
        expr: "min(r − i, p[2c − i]) = min(1, 3)",
        result: "1",
      },
      vars: "글자 비교 누적 19 번 · best = 8",
    },
    {
      title: "T14 자리 12 — 구간 밖 · 넓혀서 반지름 2",
      text: "i = 12 가 r = 12 보다 작지 않아 구간 밖입니다. 0 에서 시작합니다. 글자가 같은 쌍 2 개로 반지름이 2 가 됩니다. 오른쪽이 문자열 밖이라 멈춥니다. p[12] = 2 를 적습니다. i + p[i] = 14 가 r 보다 커서 c = 12, r = 14 로 옮깁니다.",
      array: [
        "#",
        "a",
        "#",
        "b",
        "#",
        "a",
        "#",
        "b",
        "#",
        "b",
        "#",
        "a",
        "#",
        "a",
        "#",
      ],
      range: [4, 12],
      rangeSide: "c = 8 · r = 12",
      read: [10, 11, 13, 14],
      write: [],
      pointers: {
        i: 12,
      },
      pieces: [
        {
          label: "자리 12",
          from: 10,
          to: 14,
          tone: "left",
          text: "p[12] = 2",
        },
      ],
      layers: [
        {
          name: "p",
          values: [0, 1, 0, 3, 0, 3, 0, 1, 4, 1, 0, 1, 2, null, null],
          read: [],
          write: [12],
        },
      ],
      calc: {
        expr: "i = 12 ≥ r = 12",
        result: "0 에서 시작",
      },
      vars: "글자 비교 누적 21 번 · best = 8",
    },
    {
      title: "T15 자리 13 — 오른쪽 끝과 같음 · 반지름 1",
      text: "i = 13 이 r = 14 보다 작아 구간 안입니다. 대칭 자리 2 × 12 − 13 = 11 의 반지름 1 과 남은 칸 1 중 작은 1 을 이어받습니다. 오른쪽이 문자열 밖이라 멈춥니다. p[13] = 1 을 적습니다.",
      array: [
        "#",
        "a",
        "#",
        "b",
        "#",
        "a",
        "#",
        "b",
        "#",
        "b",
        "#",
        "a",
        "#",
        "a",
        "#",
      ],
      range: [10, 14],
      rangeSide: "c = 12 · r = 14",
      read: [],
      write: [],
      pointers: {
        "2c−i": 11,
        c: 12,
        i: 13,
      },
      pieces: [
        {
          label: "자리 13",
          from: 12,
          to: 14,
          tone: "left",
          text: "p[13] = 1",
        },
        {
          label: "대칭 11",
          from: 10,
          to: 12,
          tone: "right",
          text: "p[11] = 1",
        },
      ],
      layers: [
        {
          name: "p",
          values: [0, 1, 0, 3, 0, 3, 0, 1, 4, 1, 0, 1, 2, 1, null],
          read: [11],
          write: [13],
        },
      ],
      calc: {
        expr: "min(r − i, p[2c − i]) = min(1, 1)",
        result: "1",
      },
      vars: "글자 비교 누적 21 번 · best = 8",
    },
    {
      title: "T16 자리 14 — 구간 밖 · 반지름 0",
      text: "i = 14 가 r = 14 보다 작지 않아 구간 밖입니다. 0 에서 시작합니다. 오른쪽이 문자열 밖이라 멈춥니다. p[14] = 0 을 적습니다.",
      array: [
        "#",
        "a",
        "#",
        "b",
        "#",
        "a",
        "#",
        "b",
        "#",
        "b",
        "#",
        "a",
        "#",
        "a",
        "#",
      ],
      range: [10, 14],
      rangeSide: "c = 12 · r = 14",
      read: [],
      write: [],
      pointers: {
        i: 14,
      },
      layers: [
        {
          name: "p",
          values: [0, 1, 0, 3, 0, 3, 0, 1, 4, 1, 0, 1, 2, 1, 0],
          read: [],
          write: [14],
        },
      ],
      calc: {
        expr: "i = 14 ≥ r = 14",
        result: "0 에서 시작",
      },
      vars: "글자 비교 누적 21 번 · best = 8",
    },
    {
      title: "T17 답을 잘라 낸다",
      text: '가장 긴 자리는 8 이고 반지름은 4 입니다. 시작 자리 (8 − 4) / 2 = 2 에서 4 글자를 잘라 낸 답은 "abba" 입니다. 글자 비교는 모두 21 번입니다.',
      array: [
        "#",
        "a",
        "#",
        "b",
        "#",
        "a",
        "#",
        "b",
        "#",
        "b",
        "#",
        "a",
        "#",
        "a",
        "#",
      ],
      range: [10, 14],
      rangeSide: "c = 12 · r = 14",
      read: [],
      write: [],
      layers: [
        {
          name: "p",
          values: [0, 1, 0, 3, 0, 3, 0, 1, 4, 1, 0, 1, 2, 1, 0],
          read: [8],
          write: [],
        },
      ],
      pieces: [
        {
          label: "답",
          from: 4,
          to: 12,
          tone: "left",
          text: '"abba"',
        },
      ],
      calc: {
        expr: "(8 − p[8]) / 2 = (8 − 4) / 2",
        result: "2",
      },
      vars: "글자 비교 누적 21 번",
    },
  ],
} satisfies ArrayPlayerSpec;
