import type { ArrayPlayerSpec } from "../../../_viz/player/StepPlayer";

/**
 * `deep.walk`(수행으로 알아보는 알고리즘) 절과 **같은 입력**을 쓴다 — `A = [4, 4, 4, 2, 2, 1, 1, 3, 5]`, `k = 3`.
 * `build` 는 빈도 버킷을 채우는 T1~T15(① 세기 · 버킷 만들기 · ② 담기), `collect` 는 큰 버킷부터
 * 모으는 T16~T20(③④⑤) 이다.
 *
 * `player: "stage"` 가 걸음 재생 패널(`src/_viz/player/StepPlayer.tsx`)을 고르고, `stage: "array"` 가
 * 배열 무대(`arrayStage.ts`)를 고른다. 무대의 값 줄은 입력 `A` 이고(세는 동안만 쥔 구간이다),
 * `layers` 의 첫 줄이 빈도 버킷 `slot`, 둘째 줄이 답 `result`, `map` 이 등장 횟수 맵 `freq` 다.
 * 버킷 줄의 칸 번호가 곧 버킷 번호(등장 횟수)라 무대 눈금을 그대로 읽는다.
 *
 * `steps` 는 **인라인 배열 리터럴**이어야 한다(spread·변수 참조·함수 호출 금지).
 * 정적 계수가 실제보다 적게 세면 얇은 전개가 P3 을 그냥 지나간다. 리터럴은 그림 사이드카의
 * `simStepsFromRef()`(정본 실행과 대조한 기록에서 만든 걸음)를 글자 그대로 옮긴 것이고, 둘이 같은지는
 * `topKFrequent-guide.test.ts` 가 잰다.
 */

export const build = {
  player: "stage",
  stage: "array",
  arrayName: "A",
  rangeLabel: "입력",
  title: "topKFrequent([4, 4, 4, 2, 2, 1, 1, 3, 5], 3) — 빈도 버킷 채우기",
  result: "slot[3] = [4] · slot[2] = [2 1] · slot[1] = [3 5]",
  steps: [
    {
      title: "T1 ① A[0] = 4 — freq 0 → 1",
      text: "값 4 는 처음 봅니다. freq.get(4) 가 없어 0 에서 시작해 1 로 둡니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: [0, 8],
      rangeSide: "읽음 1 / 9",
      read: [0],
      write: [],
      pointers: {
        i: 0,
      },
      layers: [
        {
          name: "버킷",
          values: [null, null, null, null, null, null, null, null, null, null],
          side: "만들기 전",
        },
        {
          name: "답",
          values: [null, null, null],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [[4, 1]],
        slots: 5,
        write: [4],
        note: "4 새 항목",
      },
      calc: {
        expr: "(freq.get(4) ?? 0) + 1",
        result: "1",
      },
      vars: null,
    },
    {
      title: "T2 ① A[1] = 4 — freq 1 → 2",
      text: "값 4 는 이미 있습니다. 앞에 센 1 에 1 을 더해 2 로 고칩니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: [0, 8],
      rangeSide: "읽음 2 / 9",
      read: [1],
      write: [],
      pointers: {
        i: 1,
      },
      layers: [
        {
          name: "버킷",
          values: [null, null, null, null, null, null, null, null, null, null],
          side: "만들기 전",
        },
        {
          name: "답",
          values: [null, null, null],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [[4, 2]],
        slots: 5,
        write: [4],
        note: "4 있음",
      },
      calc: {
        expr: "(freq.get(4) ?? 0) + 1",
        result: "2",
      },
      vars: null,
    },
    {
      title: "T3 ① A[2] = 4 — freq 2 → 3",
      text: "값 4 는 이미 있습니다. 앞에 센 2 에 1 을 더해 3 으로 고칩니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: [0, 8],
      rangeSide: "읽음 3 / 9",
      read: [2],
      write: [],
      pointers: {
        i: 2,
      },
      layers: [
        {
          name: "버킷",
          values: [null, null, null, null, null, null, null, null, null, null],
          side: "만들기 전",
        },
        {
          name: "답",
          values: [null, null, null],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [[4, 3]],
        slots: 5,
        write: [4],
        note: "4 있음",
      },
      calc: {
        expr: "(freq.get(4) ?? 0) + 1",
        result: "3",
      },
      vars: null,
    },
    {
      title: "T4 ① A[3] = 2 — freq 0 → 1",
      text: "값 2 는 처음 봅니다. freq.get(2) 가 없어 0 에서 시작해 1 로 둡니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: [0, 8],
      rangeSide: "읽음 4 / 9",
      read: [3],
      write: [],
      pointers: {
        i: 3,
      },
      layers: [
        {
          name: "버킷",
          values: [null, null, null, null, null, null, null, null, null, null],
          side: "만들기 전",
        },
        {
          name: "답",
          values: [null, null, null],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [
          [4, 3],
          [2, 1],
        ],
        slots: 5,
        write: [2],
        note: "2 새 항목",
      },
      calc: {
        expr: "(freq.get(2) ?? 0) + 1",
        result: "1",
      },
      vars: null,
    },
    {
      title: "T5 ① A[4] = 2 — freq 1 → 2",
      text: "값 2 는 이미 있습니다. 앞에 센 1 에 1 을 더해 2 로 고칩니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: [0, 8],
      rangeSide: "읽음 5 / 9",
      read: [4],
      write: [],
      pointers: {
        i: 4,
      },
      layers: [
        {
          name: "버킷",
          values: [null, null, null, null, null, null, null, null, null, null],
          side: "만들기 전",
        },
        {
          name: "답",
          values: [null, null, null],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [
          [4, 3],
          [2, 2],
        ],
        slots: 5,
        write: [2],
        note: "2 있음",
      },
      calc: {
        expr: "(freq.get(2) ?? 0) + 1",
        result: "2",
      },
      vars: null,
    },
    {
      title: "T6 ① A[5] = 1 — freq 0 → 1",
      text: "값 1 은 처음 봅니다. freq.get(1) 가 없어 0 에서 시작해 1 로 둡니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: [0, 8],
      rangeSide: "읽음 6 / 9",
      read: [5],
      write: [],
      pointers: {
        i: 5,
      },
      layers: [
        {
          name: "버킷",
          values: [null, null, null, null, null, null, null, null, null, null],
          side: "만들기 전",
        },
        {
          name: "답",
          values: [null, null, null],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [
          [4, 3],
          [2, 2],
          [1, 1],
        ],
        slots: 5,
        write: [1],
        note: "1 새 항목",
      },
      calc: {
        expr: "(freq.get(1) ?? 0) + 1",
        result: "1",
      },
      vars: null,
    },
    {
      title: "T7 ① A[6] = 1 — freq 1 → 2",
      text: "값 1 은 이미 있습니다. 앞에 센 1 에 1 을 더해 2 로 고칩니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: [0, 8],
      rangeSide: "읽음 7 / 9",
      read: [6],
      write: [],
      pointers: {
        i: 6,
      },
      layers: [
        {
          name: "버킷",
          values: [null, null, null, null, null, null, null, null, null, null],
          side: "만들기 전",
        },
        {
          name: "답",
          values: [null, null, null],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [
          [4, 3],
          [2, 2],
          [1, 2],
        ],
        slots: 5,
        write: [1],
        note: "1 있음",
      },
      calc: {
        expr: "(freq.get(1) ?? 0) + 1",
        result: "2",
      },
      vars: null,
    },
    {
      title: "T8 ① A[7] = 3 — freq 0 → 1",
      text: "값 3 은 처음 봅니다. freq.get(3) 가 없어 0 에서 시작해 1 로 둡니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: [0, 8],
      rangeSide: "읽음 8 / 9",
      read: [7],
      write: [],
      pointers: {
        i: 7,
      },
      layers: [
        {
          name: "버킷",
          values: [null, null, null, null, null, null, null, null, null, null],
          side: "만들기 전",
        },
        {
          name: "답",
          values: [null, null, null],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [
          [4, 3],
          [2, 2],
          [1, 2],
          [3, 1],
        ],
        slots: 5,
        write: [3],
        note: "3 새 항목",
      },
      calc: {
        expr: "(freq.get(3) ?? 0) + 1",
        result: "1",
      },
      vars: null,
    },
    {
      title: "T9 ① A[8] = 5 — freq 0 → 1",
      text: "값 5 는 처음 봅니다. freq.get(5) 가 없어 0 에서 시작해 1 로 둡니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: [0, 8],
      rangeSide: "읽음 9 / 9",
      read: [8],
      write: [],
      pointers: {
        i: 8,
      },
      layers: [
        {
          name: "버킷",
          values: [null, null, null, null, null, null, null, null, null, null],
          side: "만들기 전",
        },
        {
          name: "답",
          values: [null, null, null],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [
          [4, 3],
          [2, 2],
          [1, 2],
          [3, 1],
          [5, 1],
        ],
        slots: 5,
        write: [5],
        note: "5 새 항목",
      },
      calc: {
        expr: "(freq.get(5) ?? 0) + 1",
        result: "1",
      },
      vars: null,
    },
    {
      title: "T10 빈도 버킷 10 개를 만든다",
      text: "등장 횟수는 1 이상 9 이하입니다. 버킷 번호 0 부터 9 까지 10 개를 빈 목록으로 만듭니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: null,
      rangeSide: "세기 끝",
      read: [],
      write: [],
      layers: [
        {
          name: "버킷",
          values: ["[]", "[]", "[]", "[]", "[]", "[]", "[]", "[]", "[]", "[]"],
          write: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
          side: "값 든 버킷 0 / 10",
        },
        {
          name: "답",
          values: [null, null, null],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [
          [4, 3],
          [2, 2],
          [1, 2],
          [3, 1],
          [5, 1],
        ],
        slots: 5,
        note: "항목 5 개",
      },
      calc: {
        expr: "Array.from({ length: 10 }, () => [])",
        result: "버킷 0 … 9",
      },
      vars: null,
    },
    {
      title: "T11 ② 값 4 를 버킷 3 에 담는다",
      text: "freq 에서 값 4 의 등장 횟수 3 을 읽어, 그 수를 버킷 번호로 씁니다. 버킷 3 의 목록은 이제 [4] 입니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: null,
      rangeSide: "세기 끝",
      read: [],
      write: [],
      layers: [
        {
          name: "버킷",
          values: ["[]", "[]", "[]", "[4]", "[]", "[]", "[]", "[]", "[]", "[]"],
          write: [3],
          side: "값 든 버킷 1 / 10",
        },
        {
          name: "답",
          values: [null, null, null],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [
          [4, 3],
          [2, 2],
          [1, 2],
          [3, 1],
          [5, 1],
        ],
        slots: 5,
        read: [4],
        note: "freq[4] = 3",
      },
      calc: {
        expr: "slot[3].push(4)",
        result: "[4]",
      },
      vars: null,
    },
    {
      title: "T12 ② 값 2 를 버킷 2 에 담는다",
      text: "freq 에서 값 2 의 등장 횟수 2 를 읽어, 그 수를 버킷 번호로 씁니다. 버킷 2 의 목록은 이제 [2] 입니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: null,
      rangeSide: "세기 끝",
      read: [],
      write: [],
      layers: [
        {
          name: "버킷",
          values: [
            "[]",
            "[]",
            "[2]",
            "[4]",
            "[]",
            "[]",
            "[]",
            "[]",
            "[]",
            "[]",
          ],
          write: [2],
          side: "값 든 버킷 2 / 10",
        },
        {
          name: "답",
          values: [null, null, null],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [
          [4, 3],
          [2, 2],
          [1, 2],
          [3, 1],
          [5, 1],
        ],
        slots: 5,
        read: [2],
        note: "freq[2] = 2",
      },
      calc: {
        expr: "slot[2].push(2)",
        result: "[2]",
      },
      vars: null,
    },
    {
      title: "T13 ② 값 1 을 버킷 2 에 담는다",
      text: "freq 에서 값 1 의 등장 횟수 2 를 읽어, 그 수를 버킷 번호로 씁니다. 버킷 2 의 목록은 이제 [2 1] 입니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: null,
      rangeSide: "세기 끝",
      read: [],
      write: [],
      layers: [
        {
          name: "버킷",
          values: [
            "[]",
            "[]",
            "[2 1]",
            "[4]",
            "[]",
            "[]",
            "[]",
            "[]",
            "[]",
            "[]",
          ],
          write: [2],
          side: "값 든 버킷 2 / 10",
        },
        {
          name: "답",
          values: [null, null, null],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [
          [4, 3],
          [2, 2],
          [1, 2],
          [3, 1],
          [5, 1],
        ],
        slots: 5,
        read: [1],
        note: "freq[1] = 2",
      },
      calc: {
        expr: "slot[2].push(1)",
        result: "[2 1]",
      },
      vars: null,
    },
    {
      title: "T14 ② 값 3 을 버킷 1 에 담는다",
      text: "freq 에서 값 3 의 등장 횟수 1 을 읽어, 그 수를 버킷 번호로 씁니다. 버킷 1 의 목록은 이제 [3] 입니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: null,
      rangeSide: "세기 끝",
      read: [],
      write: [],
      layers: [
        {
          name: "버킷",
          values: [
            "[]",
            "[3]",
            "[2 1]",
            "[4]",
            "[]",
            "[]",
            "[]",
            "[]",
            "[]",
            "[]",
          ],
          write: [1],
          side: "값 든 버킷 3 / 10",
        },
        {
          name: "답",
          values: [null, null, null],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [
          [4, 3],
          [2, 2],
          [1, 2],
          [3, 1],
          [5, 1],
        ],
        slots: 5,
        read: [3],
        note: "freq[3] = 1",
      },
      calc: {
        expr: "slot[1].push(3)",
        result: "[3]",
      },
      vars: null,
    },
    {
      title: "T15 ② 값 5 를 버킷 1 에 담는다",
      text: "freq 에서 값 5 의 등장 횟수 1 을 읽어, 그 수를 버킷 번호로 씁니다. 버킷 1 의 목록은 이제 [3 5] 입니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: null,
      rangeSide: "세기 끝",
      read: [],
      write: [],
      layers: [
        {
          name: "버킷",
          values: [
            "[]",
            "[3 5]",
            "[2 1]",
            "[4]",
            "[]",
            "[]",
            "[]",
            "[]",
            "[]",
            "[]",
          ],
          write: [1],
          side: "값 든 버킷 3 / 10",
        },
        {
          name: "답",
          values: [null, null, null],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [
          [4, 3],
          [2, 2],
          [1, 2],
          [3, 1],
          [5, 1],
        ],
        slots: 5,
        read: [5],
        note: "freq[5] = 1",
      },
      calc: {
        expr: "slot[1].push(5)",
        result: "[3 5]",
      },
      vars: null,
    },
  ],
} satisfies ArrayPlayerSpec;

export const collect = {
  player: "stage",
  stage: "array",
  arrayName: "A",
  rangeLabel: "입력",
  title: "topKFrequent([4, 4, 4, 2, 2, 1, 1, 3, 5], 3) — 큰 버킷부터 모으기",
  result: "[4 2 1]",
  steps: [
    {
      title: "T16 ③ 버킷 9 … 4 는 비었다",
      text: "버킷 번호를 9 부터 하나씩 내립니다. 버킷 6 개가 빈 목록이라 안쪽 반복이 한 번도 실행되지 않고, 답은 0 개 그대로입니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: null,
      rangeSide: "세기 끝",
      read: [],
      write: [],
      layers: [
        {
          name: "버킷",
          values: [
            "[]",
            "[3 5]",
            "[2 1]",
            "[4]",
            "[]",
            "[]",
            "[]",
            "[]",
            "[]",
            "[]",
          ],
          read: [9, 8, 7, 6, 5, 4],
          side: "값 든 버킷 3 / 10",
        },
        {
          name: "답",
          values: [null, null, null],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [
          [4, 3],
          [2, 2],
          [1, 2],
          [3, 1],
          [5, 1],
        ],
        slots: 5,
        note: "항목 5 개",
      },
      calc: {
        expr: "slot[9] … slot[4]",
        result: "모두 빈 목록",
      },
      vars: "f = 9 … 4",
    },
    {
      title: "T17 ④ 버킷 3 의 값 4 를 답에 담는다",
      text: "버킷 3 의 값 4 를 답에 담습니다. 1 === 3 이 거짓이라 계속합니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: null,
      rangeSide: "세기 끝",
      read: [],
      write: [],
      layers: [
        {
          name: "버킷",
          values: [
            "[]",
            "[3 5]",
            "[2 1]",
            "[4]",
            "[]",
            "[]",
            "[]",
            "[]",
            "[]",
            "[]",
          ],
          read: [3],
          side: "값 든 버킷 3 / 10",
        },
        {
          name: "답",
          values: [4, null, null],
          write: [0],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [
          [4, 3],
          [2, 2],
          [1, 2],
          [3, 1],
          [5, 1],
        ],
        slots: 5,
        note: "항목 5 개",
      },
      calc: {
        expr: "result.length === k",
        result: "1 === 3 거짓",
      },
      vars: "f = 3",
    },
    {
      title: "T18 ④ 버킷 2 의 값 2 를 답에 담는다",
      text: "버킷 2 의 값 2 를 답에 담습니다. 2 === 3 이 거짓이라 계속합니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: null,
      rangeSide: "세기 끝",
      read: [],
      write: [],
      layers: [
        {
          name: "버킷",
          values: [
            "[]",
            "[3 5]",
            "[2 1]",
            "[4]",
            "[]",
            "[]",
            "[]",
            "[]",
            "[]",
            "[]",
          ],
          read: [2],
          side: "값 든 버킷 3 / 10",
        },
        {
          name: "답",
          values: [4, 2, null],
          write: [1],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [
          [4, 3],
          [2, 2],
          [1, 2],
          [3, 1],
          [5, 1],
        ],
        slots: 5,
        note: "항목 5 개",
      },
      calc: {
        expr: "result.length === k",
        result: "2 === 3 거짓",
      },
      vars: "f = 2",
    },
    {
      title: "T19 ⑤ 버킷 2 의 값 1 에서 답이 찬다",
      text: "값 1 을 담자 답이 3 개가 됐습니다. 3 === 3 이 참이라 버킷 2 안에서 멈춥니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: null,
      rangeSide: "세기 끝",
      read: [],
      write: [],
      layers: [
        {
          name: "버킷",
          values: [
            "[]",
            "[3 5]",
            "[2 1]",
            "[4]",
            "[]",
            "[]",
            "[]",
            "[]",
            "[]",
            "[]",
          ],
          read: [2],
          side: "값 든 버킷 3 / 10",
        },
        {
          name: "답",
          values: [4, 2, 1],
          write: [2],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [
          [4, 3],
          [2, 2],
          [1, 2],
          [3, 1],
          [5, 1],
        ],
        slots: 5,
        note: "항목 5 개",
      },
      calc: {
        expr: "result.length === k",
        result: "3 === 3 참",
      },
      vars: "f = 2",
    },
    {
      title: "T20 ③ 바깥 조건이 거짓 — 끝",
      text: "f 를 1 로 내린 뒤 바깥 조건을 봅니다. 3 < 3 이 거짓이라 버킷 1 부터는 보지 않고 답 [4 2 1] 을 돌려줍니다.",
      array: [4, 4, 4, 2, 2, 1, 1, 3, 5],
      range: null,
      rangeSide: "세기 끝",
      read: [],
      write: [],
      layers: [
        {
          name: "버킷",
          values: [
            "[]",
            "[3 5]",
            "[2 1]",
            "[4]",
            "[]",
            "[]",
            "[]",
            "[]",
            "[]",
            "[]",
          ],
          read: [],
          side: "값 든 버킷 3 / 10",
        },
        {
          name: "답",
          values: [4, 2, 1],
        },
      ],
      map: {
        keyLabel: "값 v",
        valueLabel: "freq",
        entries: [
          [4, 3],
          [2, 2],
          [1, 2],
          [3, 1],
          [5, 1],
        ],
        slots: 5,
        note: "항목 5 개",
      },
      calc: {
        expr: "f >= 1 && result.length < k",
        result: "1 >= 1 && 3 < 3 → 거짓",
      },
      vars: "f = 1",
    },
  ],
} satisfies ArrayPlayerSpec;
