import type { Frame } from "#guide-sim";

/**
 * `deep.walk`(수행으로 알아보는 알고리즘) 절과 **같은 입력**을 쓴다. 프레임 수는 그 절의
 * T# 단계 수(10)를 넘지 않는다 — P3 이 그 관계를 잰다.
 *
 * **뷰가 둘이다** — `graph` 는 정점의 상태(레벨을 못 받음 · 레벨을 받음 · 지금 지나는 중 ·
 * 처리 끝)와 간선의 **잔여 용량**을 그리고, `keyValue` 는 그 순간의 보낸 양 · 레벨 배열 ·
 * 역방향 잔여 용량 · 갈래를 적는다. 그래프 그림만으로는 **역방향 잔여 용량**이 안 보이는데
 * 이 편의 T7 이 그 간선으로 유량을 되돌리므로, 두 패널이 함께 있어야 한 프레임이 완결된다.
 * 같은 짝을 `maxFlow`·`bfsShortestPath` 도 쓴다.
 *
 * **간선은 원래 간선 아홉 개만 그린다.** 역방향 항목을 같은 자리에 하나 더 그리면 선과 숫자가
 * 겹쳐 어느 쪽 값인지 갈리지 않는다. 역방향 잔여 용량은 `keyValue` 패널이 적고, 역방향으로
 * 지나가는 걸음(T7)은 `activeEdge` 로 그 선을 강조한 뒤 `detail` 이 방향을 밝힌다.
 *
 * 좌표는 0~100 정규화다. 소스 0 을 왼쪽 끝에, 싱크 6 을 오른쪽 끝에 두고, 마지막 프레임에서
 * 컷의 경계가 정점 5 앞을 지나도록 5 와 6 을 오른쪽에 몰아 두었다.
 *
 * `steps` 는 **인라인 배열 리터럴**이어야 한다(spread·변수 참조·함수 호출 금지).
 * 정적 계수가 실제보다 적게 세면 얇은 전개가 P3 을 그냥 지나간다.
 */
export const minCutWalk = {
  view: ["graph", "keyValue"] as const,
  title:
    "minCut(7, [[0,1,5],[1,2,3],[2,5,3],[0,3,4],[3,2,5],[1,4,6],[4,5,4],[5,6,12],[5,3,2]], 0, 6)",
  result: "{ cut: 7 }",
  steps: [
    {
      title: "T1 잔여 그래프를 만든다",
      detail:
        "간선 아홉 개마다 정방향(잔여 = 용량)과 역방향(잔여 0)을 짝지어 항목 18 개를 만든다.",
      nodes: [
        { id: 0, x: 5, y: 50 },
        { id: 1, x: 27, y: 20 },
        { id: 2, x: 50, y: 60 },
        { id: 3, x: 27, y: 80 },
        { id: 4, x: 52, y: 10 },
        { id: 5, x: 76, y: 42 },
        { id: 6, x: 95, y: 52 },
      ],
      edges: [
        { from: 0, to: 1, weight: 5, directed: true },
        { from: 1, to: 2, weight: 3, directed: true },
        { from: 2, to: 5, weight: 3, directed: true },
        { from: 0, to: 3, weight: 4, directed: true },
        { from: 3, to: 2, weight: 5, directed: true },
        { from: 1, to: 4, weight: 6, directed: true },
        { from: 4, to: 5, weight: 4, directed: true },
        { from: 5, to: 6, weight: 12, directed: true },
        { from: 5, to: 3, weight: 2, directed: true },
      ],
      nodeStatus: { 0: "active", 6: "frontier" },
      entries: [
        { label: "보낸 양", value: "0" },
        { label: "level", value: "아직 없다" },
        { label: "역방향 잔여", value: "전부 0" },
        { label: "갈래", value: "—" },
      ],
    },
    {
      title: "T2 라운드 1 — BFS 로 레벨을 매긴다",
      detail:
        "잔여 용량이 있는 간선만 지나며 소스로부터의 최단 간선 수를 적는다. 싱크의 레벨이 4 다.",
      nodes: [
        { id: 0, x: 5, y: 50 },
        { id: 1, x: 27, y: 20 },
        { id: 2, x: 50, y: 60 },
        { id: 3, x: 27, y: 80 },
        { id: 4, x: 52, y: 10 },
        { id: 5, x: 76, y: 42 },
        { id: 6, x: 95, y: 52 },
      ],
      edges: [
        { from: 0, to: 1, weight: 5, directed: true },
        { from: 1, to: 2, weight: 3, directed: true },
        { from: 2, to: 5, weight: 3, directed: true },
        { from: 0, to: 3, weight: 4, directed: true },
        { from: 3, to: 2, weight: 5, directed: true },
        { from: 1, to: 4, weight: 6, directed: true },
        { from: 4, to: 5, weight: 4, directed: true },
        { from: 5, to: 6, weight: 12, directed: true },
        { from: 5, to: 3, weight: 2, directed: true },
      ],
      nodeStatus: {
        0: "visited",
        1: "frontier",
        2: "frontier",
        3: "frontier",
        4: "frontier",
        5: "frontier",
        6: "frontier",
      },
      nodeValue: { 0: 0, 1: 1, 2: 2, 3: 1, 4: 2, 5: 3, 6: 4 },
      entries: [
        { label: "보낸 양", value: "0" },
        { label: "level", value: "[0, 1, 2, 1, 2, 3, 4]" },
        { label: "역방향 잔여", value: "전부 0" },
        { label: "갈래", value: "① 레벨을 적고 큐 뒤에 넣는다" },
      ],
    },
    {
      title: "T3 경로 0 → 1 → 2 → 5 → 6 으로 3 만큼",
      detail:
        "레벨이 한 칸씩 오르는 간선만 따라간다. 병목은 min(5, 3, 3, 12) = 3 이다.",
      nodes: [
        { id: 0, x: 5, y: 50 },
        { id: 1, x: 27, y: 20 },
        { id: 2, x: 50, y: 60 },
        { id: 3, x: 27, y: 80 },
        { id: 4, x: 52, y: 10 },
        { id: 5, x: 76, y: 42 },
        { id: 6, x: 95, y: 52 },
      ],
      edges: [
        { from: 0, to: 1, weight: 2, directed: true },
        { from: 1, to: 2, weight: 0, directed: true },
        { from: 2, to: 5, weight: 0, directed: true },
        { from: 0, to: 3, weight: 4, directed: true },
        { from: 3, to: 2, weight: 5, directed: true },
        { from: 1, to: 4, weight: 6, directed: true },
        { from: 4, to: 5, weight: 4, directed: true },
        { from: 5, to: 6, weight: 9, directed: true },
        { from: 5, to: 3, weight: 2, directed: true },
      ],
      nodeStatus: {
        0: "active",
        1: "active",
        2: "active",
        5: "active",
        6: "active",
      },
      nodeValue: { 0: 0, 1: 1, 2: 2, 3: 1, 4: 2, 5: 3, 6: 4 },
      activeEdge: { from: 2, to: 5 },
      entries: [
        { label: "보낸 양", value: "3" },
        { label: "level", value: "[0, 1, 2, 1, 2, 3, 4]" },
        { label: "역방향 잔여", value: "1→0 = 3 · 2→1 = 3 · 5→2 = 3" },
        { label: "갈래", value: "②③④⑤ 내려가서 싱크에 닿고 갱신한다" },
      ],
    },
    {
      title: "T4 경로 0 → 1 → 4 → 5 → 6 으로 2 만큼",
      detail:
        "1 → 2 가 포화라 1 에서 다음 간선 1 → 4 로 옮긴다. 병목은 min(2, 6, 4, 9) = 2 다.",
      nodes: [
        { id: 0, x: 5, y: 50 },
        { id: 1, x: 27, y: 20 },
        { id: 2, x: 50, y: 60 },
        { id: 3, x: 27, y: 80 },
        { id: 4, x: 52, y: 10 },
        { id: 5, x: 76, y: 42 },
        { id: 6, x: 95, y: 52 },
      ],
      edges: [
        { from: 0, to: 1, weight: 0, directed: true },
        { from: 1, to: 2, weight: 0, directed: true },
        { from: 2, to: 5, weight: 0, directed: true },
        { from: 0, to: 3, weight: 4, directed: true },
        { from: 3, to: 2, weight: 5, directed: true },
        { from: 1, to: 4, weight: 4, directed: true },
        { from: 4, to: 5, weight: 2, directed: true },
        { from: 5, to: 6, weight: 7, directed: true },
        { from: 5, to: 3, weight: 2, directed: true },
      ],
      nodeStatus: {
        0: "active",
        1: "active",
        2: "visited",
        4: "active",
        5: "active",
        6: "active",
      },
      nodeValue: { 0: 0, 1: 1, 2: 2, 3: 1, 4: 2, 5: 3, 6: 4 },
      activeEdge: { from: 4, to: 5 },
      entries: [
        { label: "보낸 양", value: "5" },
        { label: "level", value: "[0, 1, 2, 1, 2, 3, 4]" },
        { label: "역방향 잔여", value: "1→0 = 5 · 4→1 = 2 · 5→4 = 2" },
        { label: "갈래", value: "②③④⑤ 포화된 간선을 건너뛰고 흘린다" },
      ],
    },
    {
      title: "T5 라운드 1 의 경로가 소진됐다",
      detail:
        "0 → 1 이 포화이고 0 → 3 → 2 로 내려가도 2 의 남은 간선이 조건에 안 맞아 0 이 올라온다.",
      nodes: [
        { id: 0, x: 5, y: 50 },
        { id: 1, x: 27, y: 20 },
        { id: 2, x: 50, y: 60 },
        { id: 3, x: 27, y: 80 },
        { id: 4, x: 52, y: 10 },
        { id: 5, x: 76, y: 42 },
        { id: 6, x: 95, y: 52 },
      ],
      edges: [
        { from: 0, to: 1, weight: 0, directed: true },
        { from: 1, to: 2, weight: 0, directed: true },
        { from: 2, to: 5, weight: 0, directed: true },
        { from: 0, to: 3, weight: 4, directed: true },
        { from: 3, to: 2, weight: 5, directed: true },
        { from: 1, to: 4, weight: 4, directed: true },
        { from: 4, to: 5, weight: 2, directed: true },
        { from: 5, to: 6, weight: 7, directed: true },
        { from: 5, to: 3, weight: 2, directed: true },
      ],
      nodeStatus: {
        0: "visited",
        1: "visited",
        2: "visited",
        3: "visited",
        4: "visited",
        5: "visited",
        6: "visited",
      },
      nodeValue: { 0: 0, 1: 1, 2: 2, 3: 1, 4: 2, 5: 3, 6: 4 },
      entries: [
        { label: "보낸 양", value: "5" },
        { label: "level", value: "[0, 1, 2, 1, 2, 3, 4]" },
        { label: "역방향 잔여", value: "2→1 = 3 · 5→2 = 3 · 5→4 = 2" },
        { label: "갈래", value: "②⑤ 간선을 다 옮겨 0 이 올라온다" },
      ],
    },
    {
      title: "T6 라운드 2 — 레벨을 다시 매긴다",
      detail:
        "0 → 1 이 포화라 0 → 3 → 2 로 들어가고, 역방향 잔여 2 → 1 을 지나 1 에 레벨 3 이 붙는다.",
      nodes: [
        { id: 0, x: 5, y: 50 },
        { id: 1, x: 27, y: 20 },
        { id: 2, x: 50, y: 60 },
        { id: 3, x: 27, y: 80 },
        { id: 4, x: 52, y: 10 },
        { id: 5, x: 76, y: 42 },
        { id: 6, x: 95, y: 52 },
      ],
      edges: [
        { from: 0, to: 1, weight: 0, directed: true },
        { from: 1, to: 2, weight: 0, directed: true },
        { from: 2, to: 5, weight: 0, directed: true },
        { from: 0, to: 3, weight: 4, directed: true },
        { from: 3, to: 2, weight: 5, directed: true },
        { from: 1, to: 4, weight: 4, directed: true },
        { from: 4, to: 5, weight: 2, directed: true },
        { from: 5, to: 6, weight: 7, directed: true },
        { from: 5, to: 3, weight: 2, directed: true },
      ],
      nodeStatus: {
        0: "visited",
        1: "frontier",
        2: "frontier",
        3: "frontier",
        4: "frontier",
        5: "frontier",
        6: "frontier",
      },
      nodeValue: { 0: 0, 1: 3, 2: 2, 3: 1, 4: 4, 5: 5, 6: 6 },
      entries: [
        { label: "보낸 양", value: "5" },
        { label: "level", value: "[0, 3, 2, 1, 4, 5, 6]" },
        { label: "역방향 잔여", value: "2→1 = 3 으로 레벨이 이어진다" },
        { label: "갈래", value: "① 역방향 간선에도 레벨을 적는다" },
      ],
    },
    {
      title: "T7 경로 0 → 3 → 2 → 1 → 4 → 5 → 6 으로 2 만큼",
      detail:
        "2 → 1 은 역방향 간선이다. 라운드 1 에서 1 → 2 로 보낸 3 중 2 를 되돌려 4 쪽으로 보낸다.",
      nodes: [
        { id: 0, x: 5, y: 50 },
        { id: 1, x: 27, y: 20 },
        { id: 2, x: 50, y: 60 },
        { id: 3, x: 27, y: 80 },
        { id: 4, x: 52, y: 10 },
        { id: 5, x: 76, y: 42 },
        { id: 6, x: 95, y: 52 },
      ],
      edges: [
        { from: 0, to: 1, weight: 0, directed: true },
        { from: 1, to: 2, weight: 2, directed: true },
        { from: 2, to: 5, weight: 0, directed: true },
        { from: 0, to: 3, weight: 2, directed: true },
        { from: 3, to: 2, weight: 3, directed: true },
        { from: 1, to: 4, weight: 2, directed: true },
        { from: 4, to: 5, weight: 0, directed: true },
        { from: 5, to: 6, weight: 5, directed: true },
        { from: 5, to: 3, weight: 2, directed: true },
      ],
      nodeStatus: {
        0: "active",
        1: "active",
        2: "active",
        3: "active",
        4: "active",
        5: "active",
        6: "active",
      },
      nodeValue: { 0: 0, 1: 3, 2: 2, 3: 1, 4: 4, 5: 5, 6: 6 },
      activeEdge: { from: 1, to: 2 },
      entries: [
        { label: "보낸 양", value: "7" },
        { label: "level", value: "[0, 3, 2, 1, 4, 5, 6]" },
        {
          label: "역방향 잔여",
          value: "2→1 = 1 로 줄고 1→2 = 2 가 되살아난다",
        },
        { label: "갈래", value: "②③④⑤ 역방향 간선으로 내려간다" },
      ],
    },
    {
      title: "T8 라운드 2 의 경로가 소진됐다",
      detail: "4 → 5 가 포화라 같은 레벨 배치로는 더 갈 수 없다.",
      nodes: [
        { id: 0, x: 5, y: 50 },
        { id: 1, x: 27, y: 20 },
        { id: 2, x: 50, y: 60 },
        { id: 3, x: 27, y: 80 },
        { id: 4, x: 52, y: 10 },
        { id: 5, x: 76, y: 42 },
        { id: 6, x: 95, y: 52 },
      ],
      edges: [
        { from: 0, to: 1, weight: 0, directed: true },
        { from: 1, to: 2, weight: 2, directed: true },
        { from: 2, to: 5, weight: 0, directed: true },
        { from: 0, to: 3, weight: 2, directed: true },
        { from: 3, to: 2, weight: 3, directed: true },
        { from: 1, to: 4, weight: 2, directed: true },
        { from: 4, to: 5, weight: 0, directed: true },
        { from: 5, to: 6, weight: 5, directed: true },
        { from: 5, to: 3, weight: 2, directed: true },
      ],
      nodeStatus: {
        0: "visited",
        1: "visited",
        2: "visited",
        3: "visited",
        4: "visited",
        5: "visited",
        6: "visited",
      },
      nodeValue: { 0: 0, 1: 3, 2: 2, 3: 1, 4: 4, 5: 5, 6: 6 },
      entries: [
        { label: "보낸 양", value: "7" },
        { label: "level", value: "[0, 3, 2, 1, 4, 5, 6]" },
        { label: "역방향 잔여", value: "5→4 = 4 · 5→2 = 3 · 2→1 = 1" },
        { label: "갈래", value: "②⑤ 간선을 다 옮겨 0 이 올라온다" },
      ],
    },
    {
      title: "T9 라운드 3 — BFS 가 싱크에 레벨을 못 적는다",
      detail:
        "2 → 5 와 4 → 5 가 둘 다 포화라 정점 5 와 6 이 레벨을 못 받는다. 반복이 끝난다.",
      nodes: [
        { id: 0, x: 5, y: 50 },
        { id: 1, x: 27, y: 20 },
        { id: 2, x: 50, y: 60 },
        { id: 3, x: 27, y: 80 },
        { id: 4, x: 52, y: 10 },
        { id: 5, x: 76, y: 42 },
        { id: 6, x: 95, y: 52 },
      ],
      edges: [
        { from: 0, to: 1, weight: 0, directed: true },
        { from: 1, to: 2, weight: 2, directed: true },
        { from: 2, to: 5, weight: 0, directed: true },
        { from: 0, to: 3, weight: 2, directed: true },
        { from: 3, to: 2, weight: 3, directed: true },
        { from: 1, to: 4, weight: 2, directed: true },
        { from: 4, to: 5, weight: 0, directed: true },
        { from: 5, to: 6, weight: 5, directed: true },
        { from: 5, to: 3, weight: 2, directed: true },
      ],
      nodeStatus: {
        0: "visited",
        1: "visited",
        2: "visited",
        3: "visited",
        4: "visited",
        5: "default",
        6: "default",
      },
      nodeValue: { 0: 0, 1: 3, 2: 2, 3: 1, 4: 4, 5: -1, 6: -1 },
      entries: [
        { label: "보낸 양", value: "7" },
        { label: "level", value: "[0, 3, 2, 1, 4, -1, -1]" },
        { label: "소스 쪽 무리", value: "{0, 1, 2, 3, 4}" },
        { label: "갈래", value: "⑥ 싱크에 레벨이 없어 반복을 끝낸다" },
      ],
    },
    {
      title: "T10 원래 간선 아홉 개를 판정해 더한다",
      detail:
        "레벨이 적힌 정점에서 없는 정점으로 건너가는 2 → 5 와 4 → 5 만 더해 컷 용량 7 이 나온다.",
      nodes: [
        { id: 0, x: 5, y: 50 },
        { id: 1, x: 27, y: 20 },
        { id: 2, x: 50, y: 60 },
        { id: 3, x: 27, y: 80 },
        { id: 4, x: 52, y: 10 },
        { id: 5, x: 76, y: 42 },
        { id: 6, x: 95, y: 52 },
      ],
      edges: [
        { from: 0, to: 1, weight: 0, directed: true },
        { from: 1, to: 2, weight: 2, directed: true },
        { from: 2, to: 5, weight: 0, directed: true },
        { from: 0, to: 3, weight: 2, directed: true },
        { from: 3, to: 2, weight: 3, directed: true },
        { from: 1, to: 4, weight: 2, directed: true },
        { from: 4, to: 5, weight: 0, directed: true },
        { from: 5, to: 6, weight: 5, directed: true },
        { from: 5, to: 3, weight: 2, directed: true },
      ],
      nodeStatus: {
        0: "visited",
        1: "visited",
        2: "visited",
        3: "visited",
        4: "visited",
        5: "default",
        6: "default",
      },
      nodeValue: { 0: 0, 1: 3, 2: 2, 3: 1, 4: 4, 5: -1, 6: -1 },
      activeEdge: { from: 4, to: 5 },
      entries: [
        { label: "컷 용량", value: "7" },
        { label: "level", value: "[0, 3, 2, 1, 4, -1, -1]" },
        { label: "컷에 드는 간선", value: "2→5 (3) · 4→5 (4)" },
        { label: "갈래", value: "⑦ 건너가는 원래 간선의 용량을 더한다" },
      ],
    },
  ] satisfies Frame[],
};
