import type { ArrayPlayerSpec } from "../../../_viz/player/StepPlayer";

/**
 * `deep.walk`(수행으로 알아보는 알고리즘) 절과 **같은 입력**을 쓴다 — `s = "banana"`. 걸음은 T1~T9 전부다 —
 * 첫 순위 · (바퀴마다) 쌍 만들기 · 뒤 성분 정렬 · 앞 성분 정렬 · 순위 다시 매기기.
 *
 * `player: "stage"` 가 걸음 재생 패널(`src/_viz/player/StepPlayer.tsx`)을 고르고, `stage: "array"` 가 배열
 * 무대(`arrayStage.ts`)를 고른다. 값 줄은 문자열 `s` 의 글자이고, `layers` 가 조각 길이마다의 순위 배열
 * 층과 그 바퀴의 뒤 성분 줄이다. 접미사 배열 `sa` 는 칸 번호가 사전순 자리 `k` 라 문자열 자리와 같은
 * 눈금에 두지 않고 `map`(키 `k` · 값 `sa[k]`)으로 맨 아래에 둔다. 쌍을 만드는 걸음의 `pieces` 는 자리 1 의
 * 앞 조각과 뒤 조각이다.
 *
 * `steps` 는 **인라인 배열 리터럴**이어야 한다(spread·변수 참조·함수 호출 금지).
 * 정적 계수가 실제보다 적게 세면 얇은 전개가 P3 을 그냥 지나간다. 리터럴은 그림 사이드카의
 * `simStepsFromRef()`(정본 실행에서 만든 걸음)를 글자 그대로 옮긴 것이고, 둘이 같은지는
 * `suffixArray-guide.test.ts` 가 잰다.
 */

export const saDoubling = {
  player: "stage",
  stage: "array",
  arrayName: "s",
  rangeLabel: "문자열",
  title: 'suffixArray("banana")',
  result: "[5, 3, 1, 0, 4, 2]",
  steps: [
    {
      title: "T1 첫 순위를 글자 코드로",
      text: "길이 1 조각의 순위를 글자 코드로 둡니다. a = 97, b = 98, n = 110 이라 대소가 사전순과 같습니다. sa 는 자리 번호 그대로입니다.",
      array: ["b", "a", "n", "a", "n", "a"],
      range: [0, 5],
      rangeSide: "글자를 읽는다",
      read: [0, 1, 2, 3, 4, 5],
      write: [],
      layers: [
        {
          name: "길이 1 순위",
          values: [98, 97, 110, 97, 110, 97],
          read: [],
          write: [0, 1, 2, 3, 4, 5],
        },
        {
          name: "길이 2 순위",
          values: [null, null, null, null, null, null],
          read: [],
          write: [],
        },
        {
          name: "길이 4 순위",
          values: [null, null, null, null, null, null],
          read: [],
          write: [],
        },
        {
          name: "뒤 성분",
          values: [null, null, null, null, null, null],
          read: [],
          write: [],
          side: "아직 없음",
        },
      ],
      map: {
        keyLabel: "k",
        valueLabel: "sa[k]",
        entries: [
          [0, 0],
          [1, 1],
          [2, 2],
          [3, 3],
          [4, 4],
          [5, 5],
        ],
        slots: 6,
        read: [],
        write: [0, 1, 2, 3, 4, 5],
        note: "자리 번호 그대로",
      },
      calc: null,
      vars: null,
    },
    {
      title: "T2 gap = 1 · 쌍 만들기",
      text: "자리마다 앞 성분 rank[i] 와 뒤 성분 rank[i+1] + 1 을 잇습니다. 자리 5 는 i+1 이 문자열 끝을 넘어 뒤 성분이 0 입니다.",
      array: ["b", "a", "n", "a", "n", "a"],
      range: [0, 5],
      rangeSide: "gap = 1 · span = 128",
      read: [],
      write: [],
      layers: [
        {
          name: "길이 1 순위",
          values: [98, 97, 110, 97, 110, 97],
          read: [0, 1, 2, 3, 4, 5],
          write: [],
        },
        {
          name: "길이 2 순위",
          values: [null, null, null, null, null, null],
          read: [],
          write: [],
        },
        {
          name: "길이 4 순위",
          values: [null, null, null, null, null, null],
          read: [],
          write: [],
        },
        {
          name: "뒤 성분",
          values: [98, 111, 98, 111, 98, 0],
          read: [],
          write: [0, 1, 2, 3, 4, 5],
          side: "gap = 1",
        },
      ],
      pieces: [
        {
          label: "앞 조각",
          from: 1,
          to: 1,
          tone: "left",
          text: "자리 1 의 앞 성분 97",
        },
        {
          label: "뒤 조각",
          from: 2,
          to: 2,
          tone: "right",
          text: "뒤 성분 110 + 1",
        },
      ],
      map: {
        keyLabel: "k",
        valueLabel: "sa[k]",
        entries: [
          [0, 0],
          [1, 1],
          [2, 2],
          [3, 3],
          [4, 4],
          [5, 5],
        ],
        slots: 6,
        read: [],
        write: [],
      },
      calc: {
        expr: "자리 1 의 쌍",
        result: "(97, 111)",
      },
      vars: null,
    },
    {
      title: "T3 gap = 1 · 뒤 성분으로 정렬",
      text: "뒤 성분으로 안정 정렬합니다. sa 가 [5, 0, 2, 4, 1, 3] 이 됩니다.",
      array: ["b", "a", "n", "a", "n", "a"],
      range: [0, 5],
      rangeSide: "gap = 1 · span = 128",
      read: [],
      write: [],
      layers: [
        {
          name: "길이 1 순위",
          values: [98, 97, 110, 97, 110, 97],
          read: [],
          write: [],
        },
        {
          name: "길이 2 순위",
          values: [null, null, null, null, null, null],
          read: [],
          write: [],
        },
        {
          name: "길이 4 순위",
          values: [null, null, null, null, null, null],
          read: [],
          write: [],
        },
        {
          name: "뒤 성분",
          values: [98, 111, 98, 111, 98, 0],
          read: [0, 1, 2, 3, 4, 5],
          write: [],
          side: "gap = 1",
        },
      ],
      map: {
        keyLabel: "k",
        valueLabel: "sa[k]",
        entries: [
          [0, 5],
          [1, 0],
          [2, 2],
          [3, 4],
          [4, 1],
          [5, 3],
        ],
        slots: 6,
        read: [],
        write: [0, 1, 3, 4, 5],
      },
      calc: null,
      vars: null,
    },
    {
      title: "T4 gap = 1 · 앞 성분으로 정렬",
      text: "그 줄을 앞 성분으로 다시 안정 정렬합니다. sa 가 [5, 1, 3, 0, 2, 4] 이 됩니다.",
      array: ["b", "a", "n", "a", "n", "a"],
      range: [0, 5],
      rangeSide: "gap = 1 · span = 128",
      read: [],
      write: [],
      layers: [
        {
          name: "길이 1 순위",
          values: [98, 97, 110, 97, 110, 97],
          read: [0, 1, 2, 3, 4, 5],
          write: [],
        },
        {
          name: "길이 2 순위",
          values: [null, null, null, null, null, null],
          read: [],
          write: [],
        },
        {
          name: "길이 4 순위",
          values: [null, null, null, null, null, null],
          read: [],
          write: [],
        },
        {
          name: "뒤 성분",
          values: [98, 111, 98, 111, 98, 0],
          read: [],
          write: [],
          side: "gap = 1",
        },
      ],
      map: {
        keyLabel: "k",
        valueLabel: "sa[k]",
        entries: [
          [0, 5],
          [1, 1],
          [2, 3],
          [3, 0],
          [4, 2],
          [5, 4],
        ],
        slots: 6,
        read: [],
        write: [1, 2, 3, 4, 5],
      },
      calc: null,
      vars: null,
    },
    {
      title: "T5 gap = 1 · 순위 다시 매기기",
      text: "이웃한 두 자리의 쌍이 다를 때만 순위를 올립니다. 같은 쌍이 2 곳이라 span = 4 고, n = 6 보다 작아 gap 을 2 로 올립니다.",
      array: ["b", "a", "n", "a", "n", "a"],
      range: [0, 5],
      rangeSide: "gap = 1 · span = 4",
      read: [],
      write: [],
      layers: [
        {
          name: "길이 1 순위",
          values: [98, 97, 110, 97, 110, 97],
          read: [0, 1, 2, 3, 4, 5],
          write: [],
        },
        {
          name: "길이 2 순위",
          values: [2, 1, 3, 1, 3, 0],
          read: [],
          write: [0, 1, 2, 3, 4, 5],
        },
        {
          name: "길이 4 순위",
          values: [null, null, null, null, null, null],
          read: [],
          write: [],
        },
        {
          name: "뒤 성분",
          values: [98, 111, 98, 111, 98, 0],
          read: [0, 1, 2, 3, 4, 5],
          write: [],
          side: "gap = 1",
        },
      ],
      map: {
        keyLabel: "k",
        valueLabel: "sa[k]",
        entries: [
          [0, 5],
          [1, 1],
          [2, 3],
          [3, 0],
          [4, 2],
          [5, 4],
        ],
        slots: 6,
        read: [0, 1, 2, 3, 4, 5],
        write: [],
        note: "이웃한 두 칸의 쌍을 비교한다",
      },
      calc: {
        expr: "span = top + 1",
        result: "4",
      },
      vars: null,
    },
    {
      title: "T6 gap = 2 · 쌍 만들기",
      text: "자리마다 앞 성분 rank[i] 와 뒤 성분 rank[i+2] + 1 을 잇습니다. 자리 4 · 5 는 i+2 가 문자열 끝을 넘어 뒤 성분이 0 입니다.",
      array: ["b", "a", "n", "a", "n", "a"],
      range: [0, 5],
      rangeSide: "gap = 2 · span = 4",
      read: [],
      write: [],
      layers: [
        {
          name: "길이 1 순위",
          values: [98, 97, 110, 97, 110, 97],
          read: [],
          write: [],
        },
        {
          name: "길이 2 순위",
          values: [2, 1, 3, 1, 3, 0],
          read: [0, 1, 2, 3, 4, 5],
          write: [],
        },
        {
          name: "길이 4 순위",
          values: [null, null, null, null, null, null],
          read: [],
          write: [],
        },
        {
          name: "뒤 성분",
          values: [4, 2, 4, 1, 0, 0],
          read: [],
          write: [0, 1, 2, 3, 4, 5],
          side: "gap = 2",
        },
      ],
      pieces: [
        {
          label: "앞 조각",
          from: 1,
          to: 2,
          tone: "left",
          text: "자리 1 의 앞 성분 1",
        },
        {
          label: "뒤 조각",
          from: 3,
          to: 4,
          tone: "right",
          text: "뒤 성분 1 + 1",
        },
      ],
      map: {
        keyLabel: "k",
        valueLabel: "sa[k]",
        entries: [
          [0, 5],
          [1, 1],
          [2, 3],
          [3, 0],
          [4, 2],
          [5, 4],
        ],
        slots: 6,
        read: [],
        write: [],
      },
      calc: {
        expr: "자리 1 의 쌍",
        result: "(1, 2)",
      },
      vars: null,
    },
    {
      title: "T7 gap = 2 · 뒤 성분으로 정렬",
      text: "뒤 성분으로 안정 정렬합니다. sa 가 [5, 4, 3, 1, 0, 2] 이 됩니다.",
      array: ["b", "a", "n", "a", "n", "a"],
      range: [0, 5],
      rangeSide: "gap = 2 · span = 4",
      read: [],
      write: [],
      layers: [
        {
          name: "길이 1 순위",
          values: [98, 97, 110, 97, 110, 97],
          read: [],
          write: [],
        },
        {
          name: "길이 2 순위",
          values: [2, 1, 3, 1, 3, 0],
          read: [],
          write: [],
        },
        {
          name: "길이 4 순위",
          values: [null, null, null, null, null, null],
          read: [],
          write: [],
        },
        {
          name: "뒤 성분",
          values: [4, 2, 4, 1, 0, 0],
          read: [0, 1, 2, 3, 4, 5],
          write: [],
          side: "gap = 2",
        },
      ],
      map: {
        keyLabel: "k",
        valueLabel: "sa[k]",
        entries: [
          [0, 5],
          [1, 4],
          [2, 3],
          [3, 1],
          [4, 0],
          [5, 2],
        ],
        slots: 6,
        read: [],
        write: [1, 3, 4, 5],
      },
      calc: null,
      vars: null,
    },
    {
      title: "T8 gap = 2 · 앞 성분으로 정렬",
      text: "그 줄을 앞 성분으로 다시 안정 정렬합니다. sa 가 [5, 3, 1, 0, 4, 2] 이 됩니다.",
      array: ["b", "a", "n", "a", "n", "a"],
      range: [0, 5],
      rangeSide: "gap = 2 · span = 4",
      read: [],
      write: [],
      layers: [
        {
          name: "길이 1 순위",
          values: [98, 97, 110, 97, 110, 97],
          read: [],
          write: [],
        },
        {
          name: "길이 2 순위",
          values: [2, 1, 3, 1, 3, 0],
          read: [0, 1, 2, 3, 4, 5],
          write: [],
        },
        {
          name: "길이 4 순위",
          values: [null, null, null, null, null, null],
          read: [],
          write: [],
        },
        {
          name: "뒤 성분",
          values: [4, 2, 4, 1, 0, 0],
          read: [],
          write: [],
          side: "gap = 2",
        },
      ],
      map: {
        keyLabel: "k",
        valueLabel: "sa[k]",
        entries: [
          [0, 5],
          [1, 3],
          [2, 1],
          [3, 0],
          [4, 4],
          [5, 2],
        ],
        slots: 6,
        read: [],
        write: [1, 2, 3, 4],
      },
      calc: null,
      vars: null,
    },
    {
      title: "T9 gap = 2 · 순위 다시 매기기",
      text: "이웃한 두 자리의 쌍이 다를 때만 순위를 올립니다. 같은 쌍이 0 곳이라 span = 6 이고, n = 6 과 같아 멈춥니다.",
      array: ["b", "a", "n", "a", "n", "a"],
      range: [0, 5],
      rangeSide: "gap = 2 · span = 6",
      read: [],
      write: [],
      layers: [
        {
          name: "길이 1 순위",
          values: [98, 97, 110, 97, 110, 97],
          read: [],
          write: [],
        },
        {
          name: "길이 2 순위",
          values: [2, 1, 3, 1, 3, 0],
          read: [0, 1, 2, 3, 4, 5],
          write: [],
        },
        {
          name: "길이 4 순위",
          values: [3, 2, 5, 1, 4, 0],
          read: [],
          write: [0, 1, 2, 3, 4, 5],
        },
        {
          name: "뒤 성분",
          values: [4, 2, 4, 1, 0, 0],
          read: [0, 1, 2, 3, 4, 5],
          write: [],
          side: "gap = 2",
        },
      ],
      map: {
        keyLabel: "k",
        valueLabel: "sa[k]",
        entries: [
          [0, 5],
          [1, 3],
          [2, 1],
          [3, 0],
          [4, 4],
          [5, 2],
        ],
        slots: 6,
        read: [0, 1, 2, 3, 4, 5],
        write: [],
        note: "이웃한 두 칸의 쌍을 비교한다",
      },
      calc: {
        expr: "span = top + 1",
        result: "6",
      },
      vars: null,
    },
  ],
} satisfies ArrayPlayerSpec;
